### ISSUE TITLE
Need Automated way of keeping Nuspecs up to date

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-extensions#100]
Too often we're moving to a new required version of the SDK or other packages but forgetting to reflect that in the nuspec.

One simple way to handle this is to write a static analysis test that reads the nuspecs and package files and does some comparisons.

We should employ this same strategy across all our WebJobs repos.

**Comment by brettsam** [comment]
Any objections if I take this one?
