### ISSUE TITLE
Extending blob bindings

### ISSUE THREAD

**Issue by sixpi** [Azure/azure-webjobs-sdk-extensions#112]
Hi, not sure if I should put this issue here or in the main webjobs SDK repo. I would like to allow `BlobAttribute` to bind to a new argument type, similar to the example for Tables in the sample. However, it seems that the equivalent to `ITableArgument` (`IBlobArgument`) is not a public interface, so currently this is not possible.

**Comment by mathewc** [comment]
What argument type? Please provide more details on your exact scenario, and the code you'd like to be able to write. I think this might already be possible for you via the existing `ICloudBlobStreamBinder<T>` mechanism. Basically you can implement this interface to do the conversion to your Type, and we'll dynamically discover and register your implementations.

**Comment by sixpi** [comment]
I would like to bind to something like an `ICollector`/`IAsyncCollector`, but for blobs. I know that you can bind to a CloudBlobContainer, but this is harder to test against, and not as concise as using an `ICollector` for queue messages. Ideally I could call something like `IBlobCollector.Add(blobName, blobContent)`, maybe having variants for the different types of blobs.
