### ISSUE TITLE
Restarting/redeploy WebJob can cause DailySchedule to run twice

### ISSUE THREAD

**Issue by Thnslj** [Azure/azure-webjobs-sdk-extensions#132]
Using  `<package id="Microsoft.Azure.WebJobs.Extensions" version="2.0.0-beta1-10332" targetFramework="net461" />`

I have a DailySchedule running each day at 1 AM.
```
internal class BackupScheduler : DailySchedule
{
   public BackupScheduler() : base("01:00:00")
      {
      }
}
```
Sometimes the System.Timers.Timer will trigger the job before 1AM
![Azure WebJobs Dashboard](http://i.imgur.com/pnJUiDK.png)

The status file written to  `azure-webjobs-hosts\timers\{hostid\{functionId}\status}` Looks like this:
`{"Last":"2016-07-28T00:59:59.8690904+00:00","Next":"2016-07-28T01:00:00"}`

The "Next" value is wrongly calculated to only a few milliseconds after the "Last" run. This is not a problem if the process keeps running, because (as I understand) the status file is only read on startup.

But if the WebJobs is redeployed or simply restarted. The `CheckPastDueAsync` in `ScheduleMonitor` will find that the timer IS past due and should be started.

I have fixed it locally with a hack; But this should be fixed in a proper way.
```
    internal class BackupScheduler : DailySchedule
    {
        public BackupScheduler() : base("01:00:00")
        {
        }

        public override DateTime GetNextOccurrence(DateTime currentTime)
        {
            TimeSpan threshold = TimeSpan.FromSeconds(10);
            DateTime nextOccurrence = base.GetNextOccurrence(currentTime);

            if (currentTime + threshold <= nextOccurrence)
            {
                return nextOccurrence;
            }
            return nextOccurrence.AddDays(1);
        }
    }

```

**Comment by davidebbo** [comment]
@brettsam this looks a lot like the issue you were investigating, no?

**Comment by brettsam** [comment]
Yes! Thank you for the details @Thnslj, this helps enormously. I think I know what's going on now -- it's possible for a timer to fire just before its 'officially' scheduled time (as we've written it in the blob). So if you've said you want it to run every day at midnight and we fire the timer just before midnight on the 1st, we'll calculate that the next run should still be at midnight on the 1st -- because that's the next midnight that we see. It doesn't affect anything if the site remains running but once it restarts, it consults the status blob and sees that it's past due so it runs again.

I'll look into a proper fix.

**Comment by shyamal890** [comment]
@brettsam Seems absolutely similar to my comment on https://github.com/Azure/azure-webjobs-sdk-extensions/issues/40#issuecomment-233281946

**Comment by davidebbo** [comment]
@shyamal890 yep, it probably is the same root issue.

**Comment by brettsam** [comment]
@shyamal890 -- yes, this looks the same. I've assigned myself to #40 as well. I've been looking at it today and there's a chance that we run the timer twice without restarts. I'm testing a fix for this now.

**Comment by mattwoberts** [comment]
Happy to test this for you guys when you get anywhere, cheers for the efforts

**Comment by mathewc** [comment]
Thanks @Thnslj for the detailed investigation on this :)

**Comment by shyamal890** [comment]
@brettsam Any updates on this?

**Comment by Thnslj** [comment]
No problem, glad I could help.

**Comment by brettsam** [comment]
This is now in and the new package is on MyGet. Give it a try and let us know if you find any issues. Thanks!

**Comment by shyamal890** [comment]
Looking forward to updated Nuget package, seems like it hasn't been updated yet.

**Comment by brettsam** [comment]
The fix is in v1.0.0-beta1-10348 on myget: http://myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.Extensions/2.0.0-beta1-10348

See here for info on setting this up as a feed: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds

**Comment by mattwoberts** [comment]
:+1: All working for me now, awesome stuff!

**Comment by shyamal890** [comment]
@brettsam Today, I swapped a stopped webapp slot to production and this issue reoccurred. This issue is not yet resolved fully.

**Comment by brettsam** [comment]
Which version was the stopped webapp using? Do you have any logs that may help us debug?

**Comment by mattwoberts** [comment]
Weird, I've done about 5 swaps since using this version, the issue hasn't come back for me...

**Comment by mattwoberts** [comment]
Could it be that the webjob you swapped OUT ran also - do you prevent jobs from running out of production?

**Comment by shyamal890** [comment]
Ok, so I tried recreating the issue however wasn't able to do so. I guess it may have happened as the older slot may have had an older version of plugin.
