### ISSUE TITLE
Please include Changelog

### ISSUE THREAD

**Issue by shyamal890** [Azure/azure-webjobs-sdk-extensions#139]
Please consider adding changelog. I was trying to find whether there were any breaking changes to deal with when updating from v1.0.1 to v2.0.0beta but couldn't find any resource.

**Comment by mathewc** [comment]
Our change log lives in the core WebJobs SDK repo here: https://github.com/Azure/azure-webjobs-sdk/wiki/Release-Notes. I haven't added a section yet for the 2.0.0-beta1 release. I'll do that today.

**Comment by mathewc** [comment]
I've added a section for the in progress 2.0.0-beta1 release at the link above.
