### ISSUE TITLE
Move to latest SendGrid packages

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-extensions#142]
We're currently on a very old version of the SendGrid SDK (6.3.4) and the latest stable is 8.0.2.

**Comment by gorillapower** [comment]
This is a big problem for us as half our projects use the new SendGrid SDK >7.x.x and WebJobs requires <= SendGrid SDK 6.3.4. Its causing us a bit of a dependency nightmare. Is there a time frame on when this is scheduled to be complete?

**Comment by mathewc** [comment]
Yes we'll be getting to this soon. I tried before when moving other dependencies, and there were a lot of non trivial breaking changes, so I backed that out.

**Comment by mathewc** [comment]
@gorillapower This has been done. Once @brettsam publishes the packages to myget, you can start using the beta packages if you wish. We've addressed all their breaking changes.

**Comment by gorillapower** [comment]
Awesome thanks all.

**Comment by brettsam** [comment]
They're up already. Anything after 10369: https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.Extensions.SendGrid/2.0.0-beta1-10369

**Comment by mathewc** [comment]
Note that you will have to absorb all the breaking changes as well - you can see our updated samples in this repo for guidance.

**Comment by mguinness** [comment]
Any word on when the dependency on SendGrid SDK 6.3.4 will be removed for the latest stable version of Microsoft.Azure.WebJobs.Extensions.SendGrid in NuGet?  I'm unable to use the beta version from MyGet in production and would like some guidance on when the new version will become a release.
