### ISSUE TITLE
Azure Web Job Timmer trigger exception

### ISSUE THREAD

**Issue by mihaivader** [Azure/azure-webjobs-sdk-extensions#146]
I'm trying to run a triggered azure web job using azure-webjobs-sdk-extensions (https://github.com/Azure/azure-webjobs-sdk-extensions)

```
JobHostConfiguration config = new JobHostConfiguration();
config.UseTimers();

JobHost host = new JobHost(config);
host.Call(typeof(Functions).GetMethod("CronJob"));
host.RunAndBlock();

public static void CronJob([TimerTrigger("0 */5 * * * *")] TimerInfo timer)
{
    Console.WriteLine("Cron job fired!");
}
```

But I'm getting this exception.

`Microsoft.Azure.WebJobs.Host System.ObjectDisposedException`

I've also tried downloding the sample projects from that gitbug repo, but even with those TimerTrigger examples I'm getting the same exception.

Any ideas? 
Thanks

**Comment by brettsam** [comment]
If you debug the app, do you see a different error? I see an InvalidOperationException with: `Missing value for trigger parameter 'timer'.`.
Try removing the call to `host.Call(typeof(Functions).GetMethod("CronJob"));`. That is meant for directly invoking the method without using any trigger.

**Comment by mihaivader** [comment]
Did that and it's working. Thanks :)
