### ISSUE TITLE
Add Email Trigger

### ISSUE THREAD

**Issue by rfreire** [Azure/azure-webjobs-sdk-extensions#148]
Be able to provide POP3 credentials for an email account to trigger when new email was received.
Something like:
[EmailTrigger("hostname", "username", "password", "whenfromaddress")] emailInfo

Or maybe to be able to provide config keys instead of actual values to avoid having passwords in code.

**Comment by christopheranderson** [comment]
You should be able to use services like SendGrid to send WebHook requests on this.

Unfortunately, we're not likely to do this as a built in extension, so I'm closing this for now.
