### ISSUE TITLE
Using WebHookTriggers in Scaled Out Web Job

### ISSUE THREAD

**Issue by sunmorgus** [Azure/azure-webjobs-sdk-extensions#153]
I'm attempting to use the WebHookTrigger attribute on my Web Job in a scaled out environment. I've got my Function decorated with the  This works wonderfully if there is only one instance of the app service, but if I scale the app service out to 2 instances, then I intermittently get a 500 Internal Server Error when attempting to call the Web Job. I've tried attaching Visual Studio to the web job, but nothing ever get's thrown. One thing I have noticed, when receiving the 500 error, the error page shows that is is calling the Web Job with a "~1" at the beginning of the address. I assume this means it's attempting to hit the second instance of the web job, but it can't. Is there something I need to do to make this work properly?

#### Repro steps

Provide the steps required to reproduce the problem

1. Deploy a WebJob with a WebHookTrigger function to an Azure App Service configured for more than one instance.
2. Call the WebHookTrigger, you'll intermittently get a 500 Internal Server Error with no other details.

#### Expected behavior

WebHookTrigger request should complete successfully.

#### Actual behavior

A 500 Internal Server Error is thrown.

#### Known workarounds

Setting the Azure App Service to run on only one instance prevents the 500 from occurring.

#### Related information 

Provide any related information 

* Package version: 1.0.0-beta4

**Comment by mathewc** [comment]
WebHookTrigger was an experimental feature that we've actually removed. You'll see we no longer have docs etc. on this. Please see [this issue](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/46) for details. Going forward, the way we recommend people do WebJob + WebHook scenarios is with [Azure Functions](https://azure.microsoft.com/en-us/services/functions/).

**Comment by atsarkar1978** [comment]
Hi Mathew,
hope you are doing good.
As you are expert in the Azure Webjob and Azure Function area, would like to know from you if I can initiate an Azure Webjob or Azure function via webhook from a Azure SQL Database trigger?
your suggestion will help me to take a architectural decission
