### ISSUE TITLE
[NotificationHub]Add option to enable debug send

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-extensions#156]
Please provide a succinct description of the issue.

NotificationHubClient has an option to [EnableTestSend](https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-push-notification-fixer/). If this property is set, NotificationHubs gives detailed error message if sending push fails for some reason. Exposing this property in NH extension would help customers debug most common config issues while sending Push

**Comment by mathewc** [comment]
Are you saying this would be a new property on the NH config object, exposed via host.json settings?

**Comment by pragnagopa** [comment]
Yes. We can create [NotificationHubClient](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.NotificationHubs/Services/NotificationHubClientService.cs#L19) with EnableTestSend

**Comment by christopheranderson** [comment]
Are you working on this now, Pragna?

**Comment by pragnagopa** [comment]
Yes. Will work on it this week.
