### ISSUE TITLE
Are the README SendGrid examples incorrect? (need to use out parameter?)

### ISSUE THREAD

**Issue by JLRishe** [Azure/azure-webjobs-sdk-extensions#157]
I am currently using the Sept. 26 nightly of Microsoft.Azure.WebJobs.Extensions.SendGrid, and when I try to use the SendGrid binding as it is shown in the README, I encounter the following error:

> System.InvalidOperationException: Can't bind SendGrid to type 'SendGrid.Helpers.Mail.Mail'.

From looking at the SendGrid samples, it looks like they use `out` parameters when binding to a `Mail` or `JObject`, and when I change my code to do so, it does indeed work.

Does the README need to be updated, or is it expected for the SendGrid binding to work without `out`?

**Comment by brettsam** [comment]
`out` is required for these -- the README was wrong. I've updated it. Thanks for pointing that out!
