### ISSUE TITLE
Add support for DocumentDB trigger binding

### ISSUE THREAD

**Issue by Biment** [Azure/azure-webjobs-sdk-extensions#160]
DocumentDB trigger binding can be a great feature for the use cases which require reacting to changes in the collections.

**Comment by christopheranderson** [comment]
This is something we've started investigating. Will likely land after GA of Functions and 2.0.0 of WebJobs SDK.

**Comment by stephlocke** [comment]
There is now an API of deltas for DocDB that could be used for this:
https://azure.microsoft.com/en-us/blog/introducing-change-feed-support-in-azure-documentdb/

**Comment by mathewc** [comment]
Yep - we'll be working with the DocDB team to get a trigger binding in place :)

**Comment by vip32** [comment]
any ETA?
