### ISSUE TITLE
Update NuSpec SendGrid version to include < v9

### ISSUE THREAD

**Issue by xt0rted** [Azure/azure-webjobs-sdk-extensions#170]
The new betas are set to `>= 8.0.5`, this should be updated to include `< 9.0.0`. There's a new version in development which is going to remove all the dynamics and the dependency on `SendGrid.CSharp.HTTP.Client`. There aren't any releases yet (that I'm aware of) but there is a v9 branch [in their repo](https://github.com/sendgrid/sendgrid-csharp/tree/v9beta) with development on it.

**Comment by brettsam** [comment]
Thanks for the heads-up @xt0rted! I know we've bumped into issues with people updating to incompatible versions, so this will help in the future.

**Comment by davidebbo** [comment]
It's often best to avoid upper bounds in nuget specs, unless we are absolutely sure that the breaking change makes it unusable. My old post on this topic covers this: http://blog.davidebbo.com/2011/01/nuget-versioning-part-2-core-algorithm.html

**Comment by brettsam** [comment]
I checked it out before doing the work -- it looks like it's a significant breaking change to the dynamic client API we use:

- Our code: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.SendGrid/Client/SendGridClient.cs#L22
- Their issue: https://github.com/sendgrid/sendgrid-csharp/issues/303 (with lots of linked issues/PRs)

On top of that, we just got bit by this with someone using an older SendGrid extension and trying to move forward between the v2 and v3 SendGrid APIs: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/169. If we see more confusion around that one, we may want to go back and generate a new build just to prevent upgrades there, too.

**Comment by davidebbo** [comment]
Fair.
