### ISSUE TITLE
TimerTrigger Running twice on Azure Scale out plan

### ISSUE THREAD

**Issue by Yitzchok** [Azure/azure-webjobs-sdk-extensions#177]
I have a webjob that uses the TimerTrigger and is running on 4 instances using Azure Scale out.

Sometimes the time triggers start getting triggered by two server at the same time and once it starts it continues until I restart the webjob.

What I am suspecting is a TimeZone problem that is caused after I connect a dev instance which isn't setup as UTC since.

Sometimes it's triggered from the dev instance and sometimes from the webjob instance while other times the dups are both Azure WebJob instances

Here are the function invocations samples
[WebJob_dev.txt](https://github.com/Azure/azure-webjobs-sdk-extensions/files/622999/WebJob_dev.txt)
[WebJob_WebJob.txt](https://github.com/Azure/azure-webjobs-sdk-extensions/files/622998/WebJob_WebJob.txt)

**Comment by christopheranderson** [comment]
Can you try the pre-release version of the extension to see if it repros? (this might be a bit of work, but we've fixed many of the timer trigger issues in that pre-release)

**Comment by Yitzchok** [comment]
This problem is with Microsoft.Azure.WebJobs.Extensions 2.0.0-beta2.

1.0.1 gave me much more issues with timer which seem to be resolved.

**Comment by christopheranderson** [comment]
Awesome. Thanks for trying the latest.

Could you provide more details about your environment? You mention dev; are you running multiple versions of your WebJobs? I'd expect that if they are sharing a storage account, they each try to grab a lock. 

@mathewc - you should take a look at this one since he's on the latest.

**Comment by Yitzchok** [comment]
Dev environment uses the same storage account as the WebJob is using The dev environment uses EST and webapp should be using UTC (I didn't set WEBSITE_TIME_ZONE)

**Comment by Yitzchok** [comment]
I just checked the Function invocation logs and I see that this problem happens even without connecting the Dev environment at all.

**Comment by brettsam** [comment]
Can you help me verify your setup:
- A single TimerTrigger running on multiple instances in Azure -- and this is a single WebJob (i.e. you didn't create two WebJobs in Azure)
- You see the timer fire on different instances at the same time.

As Chris mentioned above, each instance should be trying to grab a lock to guarantee that only one is running. I'm trying to understand why this wouldn't be happening. Those locks exist in your Azure storage account in the `azure-webjobs-hosts` container and they live under the path `locks\{hostId}\{functionName}.Listener`. 

If you stop all of your WebJobs (production, dev, etc), and then run it in VS on your local machine (I saw a 'VS WebJob' in your logs) with Verbose logging turned on, do you see logs indicating that a Singleton lock was acquired?

**Comment by Yitzchok** [comment]
- Single WebJob with multiple azure scale out instances
- Times fire about the same time ("whenUtc": "2016-12-05T18:59:22.9111242Z" and "whenUtc": "2016-12-05T18:59:22.0945575Z")

Azure lock files are locked and this is from the trace log

12/5/2016 8:46:30 PM: Waiting for Singleton lock (adb2da6283ed4f35a041278f33ba8540/Server.Functions.StartImport.Run.Listener)

**Comment by brettsam** [comment]
Does the log ever say `Singleton lock acquired`, or does it say `Unable to acquire Singleton lock`?

How many lock files do you see for this Timer trigger? I believe there should only be one.

**Comment by Yitzchok** [comment]
Singleton lock acquired (adb2da6283ed4f35a041278f33ba8540/Server.Functions.StartImport.Run.Listener) 

I have a lock for every timer no dups

**Comment by brettsam** [comment]
Ok, thanks for clarifying. Let's see if we can get some verbose logs from your WebJob running in Azure that you can share with me. Can you turn on `Application Logging (Filesystem)` and set it to 'Verbose' in the Azure portal for your app? It's under 'Diagnostic logs' in the menu.

Then, wait until you see the duplicate trigger firing again. Then navigate to https://{yoursite}.scm.azurewebsites.net/DebugConsole and navigate to `D:\home\LogFiles\SiteExtensions\Kudu`. You should see 1 log file for each instance that you're running. Would you mind posting those here -- or even sending them directly to me (my email is in my Github profile). That'll give me a better idea of what could be happening.

**Comment by Yitzchok** [comment]
File only get to 128KB file size

**Comment by brettsam** [comment]
It should roll over to a new file after that. I end up seeing multiple log files for each instance after running for a while. Have you been able to catch a duplicate trigger yet?

**Comment by Yitzchok** [comment]
It rolls over for 2 files that not much.

No duplicate trigger as of now

**Comment by Yitzchok** [comment]
No duplicate triggers meanwhile that nice but I really didn't change anything

**Comment by lindydonna** [comment]
@Yitzchok Please reopen if you hit this issue again.
