### ISSUE TITLE
UseEventHub extension

### ISSUE THREAD

**Issue by sjmneves** [Azure/azure-webjobs-sdk-extensions#179]
Working with Iot Hub and Iot Devices.
I need a webjob to run two methods simultaneously. One to process Device messages (ProcessDeviceMessages) and another one to process Device feedback (ProcessOperationMessages).

On my Webjob project I have this code in Program.cs:
``` csharp
JobHostConfiguration config = new JobHostConfiguration();
var eventHubConfig = new EventHubConfiguration
string eventHubName = "iothub-ehub-...";
eventHubConfig.AddReceiver(eventHubName, "Endpoint=sb://ihsuproddbres035dednamespace.servicebus.windows.net/;SharedAc...");
config.UseEventHub(eventHubConfig);

var host = new JobHost(config);

// setup "no attribute" methods
host.Call(typeof(OperationsMonitoringProcessor).GetMethod("ProcessOperationMessages"));

// The following code ensures that the WebJob will be running continuously
host.RunAndBlock();
```
These are the processors:
```
public static async void ProcessDeviceMessages([EventHubTrigger("iothub-ehub-...")] EventData[] eventDataBatch, TextWriter log)
{ ... }

[NoAutomaticTrigger]
public static async Task ProcessOperationMessages()
{ ... }
```
#### Repro steps

1 - With the above code, only Device feedback is processed on  ProcessOperationMessages

2 - If I remove this line:
host.Call(typeof(OperationsMonitoringProcessor).GetMethod("ProcessOperationMessages"));
Only Device messages are processed by ProcessDeviceMessages

#### Expected behavior

Both methods ProcessDeviceMessages and ProcessOperationMessages need to run simultaneously and continuously!

**Comment by lindydonna** [comment]
This is by design. When using the attribute `NoAutomaticTrigger`, you have to call `JobHost.Call` to actually invoke the function. `NoAutomaticTrigger` is not about registration, it's about invocation.

**Comment by josesimoes** [comment]
This means that one can't have both an ```NoAutomaticTrigger``` and a "triggered" method on the same webjob?

**Comment by brettsam** [comment]
You can have `[NoAutomaticTrigger]` and triggers in the same job. `[NoAutomaticTrigger]` tells the host that no trigger should ever fire this function. The only way for it to run is by calling `host.Call()`. Any other functions that have triggers will run fine as-is, but ones with `[NoAutomaticTrigger]` require manual calls to run.

In the example above:
- `ProcessDeviceMessages` will run whenever an message is sent to the registered Event Hub.
- `ProcessOperationMessages` will run whenever someone calls `host.Call(typeof(OperationsMonitoringProcessor).GetMethod("ProcessOperationMessages"))` and it will run one time for each call.

**Comment by sjmneves** [comment]
Yes, you are write, the problem was at ProcessOperationMessages, it cannot be a Task. I switched it to a void and it works now. Thanks
