### ISSUE TITLE
TimerTrigger does not allow lookups for schedule expressions in Functions

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-extensions#181]
Using WebJobs, you are able to use something like `%Cron_Schedule%` to provide a lookup for your schedule expression. This currently does not work in functions. 

The reason is because the `ScriptBindingProvider` tries to early-validate the string before the attribute is created. This disallows anything that is not a Cron expression: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions/Extensions/CoreExtensionsScriptBindingProvider.cs#L76

Issue originally reported here: https://social.msdn.microsoft.com/Forums/en-US/81e07785-a4ea-4bf7-aa0f-44faa592b39d/storing-timer-trigger-cron-expression-in-application-settings?forum=AzureFunctions

**Comment by brettsam** [comment]
@mathewc -- Do you remember why we're doing early validation here? It prevents you from using "%%" in your schedule, which WebJobs supports.

**Comment by mathewc** [comment]
The reason this early validation was put in place was because we only want to support cron expressions in Functions, not the TimeSpan format. The fact that this prevents %% resolution was an unintended casualty. If we can move this validation later, that would be fine.

**Comment by aloysiustany** [comment]
Is this fixed @brettsam ? I am still unable to set %apsettingkey% in azure function from portal

**Comment by ssabbi** [comment]
It worked, Thanks @mathewc
