### ISSUE TITLE
ErrorMonitor not sending emails

### ISSUE THREAD

**Issue by sharpcoder28** [Azure/azure-webjobs-sdk-extensions#189]
I'm using the 2.0 sdk and it's not sending emails.

```csharp
public static void ErrorMonitor(
           [ErrorTrigger("00:00:01", 1)] TraceFilter filter, TextWriter log,
           [SendGrid(
                To = "bgit@bluegracegroup.com")]
            out Mail message)
        {           
            log.WriteLine(filter.GetDetailedMessage(5));

            var env = CloudConfigurationManager.GetSetting("Environment");

            message = new Mail();
            message.Subject = $"TeleVOIPs WebJob Error ({env})";
            message.AddContent(new Content("text/plain", filter.GetDetailedMessage(5)));

        }
```

AzureWebJobsSendGridApiKey app setting like before.

These are my packages

<package id="Dapper" version="1.50.2" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.Azure.KeyVault.Core" version="2.0.4" targetFramework="net452" />
  <package id="Microsoft.Azure.ServiceBus.EventProcessorHost" version="2.2.6" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Core" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Extensions" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Extensions.SendGrid" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Script.Extensibility" version="1.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Data.Edm" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Data.OData" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Data.Services.Client" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Tpl.Dataflow" version="4.5.24" targetFramework="net452" />
  <package id="Microsoft.Web.WebJobs.Publish" version="1.0.12" targetFramework="net452" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net452" />
  <package id="ncrontab" version="3.2.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="Sendgrid" version="8.0.5" targetFramework="net452" />
  <package id="SendGrid.CSharp.HTTP.Client" version="3.0.0" targetFramework="net452" />
  <package id="System.Spatial" version="5.8.1" targetFramework="net452" />
  <package id="WindowsAzure.ServiceBus" version="3.4.1" targetFramework="net452" />
  <package id="WindowsAzure.Storage" version="8.0.1" targetFramework="net452" />

**Comment by sharpcoder28** [comment]
`
<package id="Dapper" version="1.50.2" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.Azure.KeyVault.Core" version="2.0.4" targetFramework="net452" />
  <package id="Microsoft.Azure.ServiceBus.EventProcessorHost" version="2.2.6" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Core" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Extensions" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Extensions.SendGrid" version="2.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Azure.WebJobs.Script.Extensibility" version="1.0.0-beta2" targetFramework="net452" />
  <package id="Microsoft.Data.Edm" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Data.OData" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Data.Services.Client" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Tpl.Dataflow" version="4.5.24" targetFramework="net452" />
  <package id="Microsoft.Web.WebJobs.Publish" version="1.0.12" targetFramework="net452" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net452" />
  <package id="ncrontab" version="3.2.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="Sendgrid" version="8.0.5" targetFramework="net452" />
  <package id="SendGrid.CSharp.HTTP.Client" version="3.0.0" targetFramework="net452" />
  <package id="System.Spatial" version="5.8.1" targetFramework="net452" />
  <package id="WindowsAzure.ServiceBus" version="3.4.1" targetFramework="net452" />
  <package id="WindowsAzure.Storage" version="8.0.1" targetFramework="net452" />
`

**Comment by mathewc** [comment]
I believe you're missing the "using" statement for the Core extension which ErrorTrigger is a part of. Add `config.UseCore()` to your startup code:

```csharp
            var config = new JobHostConfiguration();
            config.UseCore();
            config.UseSendGrid();
```

**Comment by sharpcoder28** [comment]
No, here is my code

`
var config = new JobHostConfiguration();

            if (config.IsDevelopment)
            {
                config.UseDevelopmentSettings();
            }

            config.UseCore();
            config.UseTimers();
            config.UseSendGrid(new SendGridConfiguration()
            {
                FromAddress = new Email("BGMonitoring@bluegracegroup.com")
            });

            var host = new JobHost(config);
            // The following code ensures that the WebJob will be running continuously
            host.RunAndBlock();
`

**Comment by sharpcoder28** [comment]
``

**Comment by sharpcoder28** [comment]
Sorry false alarm. I changed the from email which is going to a different folder /facepalm
