### ISSUE TITLE
Singleton behavior for TimerTrigger not working

### ISSUE THREAD

**Issue by flagbug** [Azure/azure-webjobs-sdk-extensions#193]
#### Repro steps

Provide the steps required to reproduce the problem

I have a `TimerTrigger` declared like this:

```csharp
public static async Task DoMyStuff(
    [TimerTrigger("06:00:00", RunOnStartup = true)] TimerInfo timer, 
    [Queue("thequeue")] ICollector<ReceiptMessage> collector, 
    TextWriter logger)
```` 
in an App Service environment that has two instances

#### Expected behavior

According to the `TimeTrigger` wiki:
> Behind the scenes, TimerTrigger uses the Singleton feature of the WebJobs SDK to ensure that only a single instance of your triggered function is running at any given time.

So I expect that the timer is fired every 6 hours, but only once

#### Actual behavior

The timer is fired two times every 6 hours (once on every instance it seems)

#### Related information 

Log output:

```
[02/10/2017 16:10:43 > af2b06: SYS INFO] Status changed to Starting
[02/10/2017 16:10:43 > af2b06: SYS INFO] WebJob singleton setting is False
[02/10/2017 16:10:45 > af2b06: SYS INFO] Run script 'Obolus.ReceiptProcessor.exe' with script host - 'WindowsScriptHost'
[02/10/2017 16:10:45 > af2b06: SYS INFO] Status changed to Running
[02/10/2017 16:10:49 > 764549: SYS INFO] Status changed to Starting
[02/10/2017 16:10:50 > 764549: SYS INFO] WebJob singleton setting is False
[02/10/2017 16:10:51 > 764549: SYS INFO] Run script 'Obolus.ReceiptProcessor.exe' with script host - 'WindowsScriptHost'
[02/10/2017 16:10:51 > 764549: SYS INFO] Status changed to Running
[02/10/2017 16:10:51 > af2b06: INFO] Found the following functions:
```

**Comment by brettsam** [comment]
Some questions:
- Is the function succeeding each time?
- What version of WebJobs.Extensions are you using?
- Could you temporarily enable Verbose logging so that we can see if the Singleton lock is getting acquired correctly? `config.Tracing.ConsoleLevel = TraceLevel.Verbose;`

**Comment by flagbug** [comment]
@brettsam 

> Is the function succeeding each time?
Jup!

> What version of WebJobs.Extensions are you using?
`2.0.0-beta2`

> Could you temporarily enable Verbose logging so that we can see if the Singleton lock is getting acquired correctly? config.Tracing.ConsoleLevel = TraceLevel.Verbose;
Sure, I'll see what I can do!

**Comment by mathewc** [comment]
Also, please provide more details on your deployment setup. You're running this in a continuous webjob with AlwaysOn enabled?

Anything special about the way you configure JobHostConfiguration.HostId? Usually you don't set that value and it is defaulted to a stable ID based on the assembly full name of the JobHost assembly. The locking is based on that HostId, so if for some reason you were using different IDs across host instances, that could cause problems.

I do notice that you have `RunOnStartup = true` specified. That might be causing you issues - it will cause it to be run immediately when each instance starts up, then on schedule thereafter. Why do you have that set to true?

**Comment by flagbug** [comment]
Sorry for taking so long to respond:

> You're running this in a continuous webjob with AlwaysOn enabled?

Yup!

> Anything special about the way you configure JobHostConfiguration.HostId? Usually you don't set that value and it is defaulted to a stable ID based on the assembly full name of the JobHost assembly. The locking is based on that HostId, so if for some reason you were using different IDs across host instances, that could cause problems.

Nope, I don't configure this manually

> I do notice that you have RunOnStartup = true specified. That might be causing you issues - it will cause it to be run immediately when each instance starts up, then on schedule thereafter. Why do you have that set to true?

I want the job to run immediately for two purposes:
- Debugging the WebJob, where I don't want to wait until the timer fires
- I want the WebJob to run immediately after deployment, so any fixes are visible immediately

**Comment by mathewc** [comment]
To clarify: setting `RunOnStartup = true` won't change the fact that the timer will only run on a single instance - you are correct that the singleton aspect is maintained. I was just pointing out that with this set, you can get schedule executions that aren't on your schedule.

Your logs above don't show the timer firing on two different instances - I don't see any timer fires in your logs. Can you share those?
