### ISSUE TITLE
DocDB input binding can update POCOs even if they haven't changed

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-extensions#198]
If you do something like this, we shouldn't be sending an update, but we are:

```
public static void ReadDocument(            
    [DocumentDB("ItemDb", "ItemCollection", Id = "1d0aaaa9-5458-460e-b82a-032c79d2acd1")] Item item)
    {            
    }
```

The fix is to switch how we store the 'previous object' when checking if it hasn't changed. Looking into it now.

**Comment by christopheranderson** [comment]
@brettsam - can we close?
