### ISSUE TITLE
New NuGet pre-release

### ISSUE THREAD

**Issue by mejje** [Azure/azure-webjobs-sdk-extensions#21]
Hi, when can we expect a new NuGet pre-release with the UseReceiver WebHooks stuff?

https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.WebHooks/Config/WebHooksConfiguration.cs#L47 referenced in bottom part of docs at https://github.com/Azure/azure-webjobs-sdk-extensions#webhooks (AspNet.WebHooks.Receivers)

**Comment by mathewc** [comment]
What change are you looking to see? I just uploaded **1.0.0-beta1-10168** on Friday. The sample app in this repo includes running samples ([see here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Samples/WebHookSamples.cs)), and the Wiki ([see here](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/WebHooks-Walkthrough)) includes a walkthrough.

**Comment by mejje** [comment]
The [UseReceiver](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.WebHooks/Config/WebHooksConfiguration.cs#L47) method is not present in the [NuGet package](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.WebHooks/1.0.0-beta1), and it's the only release I can see?

**Comment by mathewc** [comment]
The UseReceiver integration came after the nuget.org beta1 package was published. You can always access the latest bits by pulling from the "nightlies" feed ([instructions here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)).
