### ISSUE TITLE
TimerTrigger but no functions found

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-webjobs-sdk-extensions#22]
I am trialling the new extensions, specifically the `TimerTrigger` in a continuous WebJob.

I get the message "No functions found. Try making job classes and methods public." and my method declaration looks like:

```c#
public async Task RetrievePrices([TimerTrigger("0 0 1 * * ?", RunOnStartup = true)] TimerInfo timer, TextWriter log)
```

I had removed the `NoAutomaticTrigger` attribute as I though the `TimerTrigger` attribute would take care of this now?

I also changed the `JobHost` in `Main` to call `RunAndBlock()` now being a continuous job rather than the `host.Call` that was previously with a scheduled job.

**Comment by mathewc** [comment]
You have to register the Timer extension via `config.UseTimers()` in your startup code. Please see the [readme]{https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/README.md) for an example - it shows how to do this. All extensions use this "using" pattern for registration.

**Comment by damienpontifex** [comment]
Ahh thanks. I skipped straight to the timer jobs section and missed the intro.
