### ISSUE TITLE
Expose Http Helpers

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-extensions#226]
Currently there are some extension methods, utility helpers and other logic that is duplicated between the Functions codebase and the Http binding. We should share code where possible, exposing helpers as needed from the http binding package.

**Comment by christopheranderson** [comment]
@mathewc - is this done?

**Comment by mathewc** [comment]
I spot checked in dev and nothing is jumping out at me. We'll just close this and handle anything we end up doing double maintenance on as we run into them.
