### ISSUE TITLE
Firing WebJob Function via Dashboard - wrong Date format

### ISSUE THREAD

**Issue by xoxoxexe** [Azure/azure-webjobs-sdk-extensions#23]
Trying to execute a Trigger Function manually i was requested to enter TimerTrigger value.
Requested format is ISO yyyy-mm-ddThh:mm:ssZ
Suggested string in the Textbox was 12/08/2015 11:46:33 +00:00. That is the first issue.
The second is: even entering the Date in requested ISO format it crashes with InvalidCastException.
I'm able to run this function on our the dev account without ever manipulating the date string, it just never works on the second account. 
![1](https://cloud.githubusercontent.com/assets/2676328/11655975/317a9ec4-9db2-11e5-9fa5-822c64fbc545.png)
![2](https://cloud.githubusercontent.com/assets/2676328/11655976/3437c006-9db2-11e5-832c-34e1c5f0902d.png)
![3](https://cloud.githubusercontent.com/assets/2676328/11655978/35d80a60-9db2-11e5-9bb9-b348d997be65.png)

**Comment by xoxoxexe** [comment]
Small addition : Azure fires the mentioned function at the scheduled time without any issues.

**Comment by mathewc** [comment]
You're running an old version of the Extensions package. Please upgrade to v1.1.0 which we just recently released. You should no longer see the "Enter an ISO date" prompt. Basically any value you do enter here is not even used - you should no longer get errors if you do enter a value though. The reason this input value is not used is unlike other triggers like queues, there is actually no trigger input -  scheduled timer jobs just fire on schedule.
