### ISSUE TITLE
TimerTrigger and Conitnuous jobs scaling

### ISSUE THREAD

**Issue by ashavibapat** [Azure/azure-webjobs-sdk-extensions#230]
Please provide a succinct description of the issue.
I have created a continuous job and have used the timertrigger to run it every 2 minutes.
So will the scaling of webjobs as many as app service instances not work due to this?
If I have 5 instance count set for the web app holding the webjob,ther eis still only 1 webjob instance running.Is this expected?

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by christopheranderson** [comment]
Timer trigger works like a singleton, so it will run on one of your instances.
