### ISSUE TITLE
Document that TimerTrigger uses INameResolver

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-webjobs-sdk-extensions#232]
Should be some documentation that TimerTrigger can use a variable for the schedule definition which is passed to the INameResolver e.g.

       public async Task Schedule([TimerTrigger("%schedule1%")] TimerInfo timer)
        {
            await scheduler.Schedule();
        }

Was about to request the feature and found out it just works :-)

**Comment by paulbatum** [comment]
This issue was moved to Azure/Azure-Functions#417
