### ISSUE TITLE
Feature Request - REST API to return function status in TimerTrigger webjob

### ISSUE THREAD

**Issue by chinarosesz** [Azure/azure-webjobs-sdk-extensions#235]
I finished trying out TimerTrigger. I like the fact that I can have multiple functions (child webjobs) in a parent webjob. I learned that the parent webjob has to be continuous, which is not a problem, however, we rely a lot on monitoring to know when a webjob fails. So if a function in the parent webjob fails, I'm not sure how to go about detecting the status and use Application Insights to raise an alert.
With the manual triggered webjob, I can monitor when the status becomes failed, success, or is running using the REST API. Since using TimerTrigger, the status will always be running even if one of functions fails.
The only solution that I can come up with is to use Application Insights to raise an alert if there is more than one exceptions being thrown in one of the functions.

**Comment by christopheranderson** [comment]
Our plan going forward is to recommend using Application Insights. If there anything we can do to make it easy to detect your scenario within App Insights, please open a new issue with the relevant details.
