### ISSUE TITLE
[.NET Core] - Migrate DocumentDB extension project

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-extensions#240]
Issue to track migration of the WebJobs.Extension.DocumentDB project to .NET Standard 2.0

 - [ ] Migrate project
 - [ ] Setup build / artifacts publishing

**Comment by pshukla03** [comment]
is CosmosDB trigger supported in Azure Functions for C# in .Net Core

**Comment by brettsam** [comment]
Not yet. We're waiting on the [ChangeFeedProcessor](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.ChangeFeedProcessor/) to be supported. Once it is, we'll get it running in the core build.

**Comment by michael-watson** [comment]
Any updates here @brettsam ? Looks like `ChangeFeedProcessor` was updated to supported 2.0

**Comment by brettsam** [comment]
Yeah, this has been done for a while but I didn't link to this issue: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/319
