### ISSUE TITLE
[.NET Core] - Migrate SendGrid extension project

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-extensions#243]
Issue to track migration of the WebJobs.Extension.SendGrid project to .NET Standard 2.0

 - [x] Migrate project
 - [x] Setup build / artifacts publishing

**Comment by xt0rted** [comment]
I've been working with this and the SendGrid library (the newer version that changed the api yet again, ref: #191). Once this is ready to be worked on, assuming I have the time, I could take a shot at doing this task. It'd be useful preparation for migrating my own projects over which depend on this.
