### ISSUE TITLE
TimerTrigger - TimeSpan "24:00:00" - The next 5 occurrences as being 24 days apart

### ISSUE THREAD

**Issue by CrazyTuna** [Azure/azure-webjobs-sdk-extensions#247]
I am using a TimeTrigger to pol information from a database.

    public async Task ProcessChangeRequest([TimerTrigger("24:00:00")] TimerInfo timer, TextWriter log, CancellationToken token)
    {

    }

The next 5 occurences as being 24 days apart. I would have expected that next schedule will be 24hours apart.    
I am using nuget package `Microsoft.Azure.WebJobs.Extensions v2.0.0`.    
Am I doing something wrong ?

**Comment by mathewc** [comment]
This is due to the way TimeSpan.Parse works. If you pass it "24:00:00" strangely enough it will give you back a TimeSpan of duration **24 days**. Not sure if this is their intended behavior or a bug on their side.

Anyhow, for your purposes, to get 24 hours you can use "1.00:00" (specifying 1 day).
