### ISSUE TITLE
HttpOutputAttribute is missing

### ISSUE THREAD

**Issue by daulet** [Azure/azure-webjobs-sdk-extensions#251]
There is no HttpOutputAttribute provided either by Microsoft.Azure.WebJobs.Extensions or Microsoft.Azure.WebJobs.Extensions.Http packages to decorate function methods and/or their return value. According to [function bindings doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#http-response-output-binding) it is possible to have two different HTTP Output bindings: plain HTTP 200 or custom one. Having HttpOutputAttribute would allow distinguishing between the two.

**Comment by lindydonna** [comment]
The Visual Studio tooling will always produce an HTTP output binding, which allows you to customize the response.
