### ISSUE TITLE
Custom Binding attribute with Name property

### ISSUE THREAD

**Issue by daulet** [Azure/azure-webjobs-sdk-extensions#254]
If you declare a custom binding attribute type that has a "Name" property, the value of the property will be overridden with parameter name, instead of configured value. Say I have a function declared as:

Run([CustomBinding(Name = "MyName")] string parameterName) 

Then CustomBinding.Name == "parameterName", instead of expected "MyName"

**Comment by christopheranderson** [comment]
@mathewc / @MikeStall - comments?

**Comment by MikeStall** [comment]
That's unfortunately correct. Avoid the name property and use something more specific.

**Comment by christopheranderson** [comment]
Closing: won't fix
