### ISSUE TITLE
TimerTrigger won't work

### ISSUE THREAD

**Issue by jcmontx** [Azure/azure-webjobs-sdk-extensions#259]
I have this very simple webjob

```
 class Program
    {
        static void Main(string[] args)
        {
            JobHostConfiguration config = new JobHostConfiguration
            {
                StorageConnectionString = "mykey",
                DashboardConnectionString = "mykey"
            };

            config.UseTimers();

            JobHost host = new JobHost(config);
            host.RunAndBlock();
        }



        public static void EmailsConsumer([TimerTrigger("00:30:00", RunOnStartup = true)]TimerInfo ti)
        {
            //do something
        }
    }
```

And for some reason it won't work 
![image](https://user-images.githubusercontent.com/10617099/28842243-4830de16-76d3-11e7-93f0-1b9e2ab11907.png)

Am I doing something wrong or is it a bug?

**Comment by christopheranderson** [comment]
Does it work if you: (either/or)
1. Make program public?
2. Move your method to a new public class?

**Comment by jcmontx** [comment]
@christopheranderson thank you! I was sure it was some trivial thing I was missing.

**Comment by christopheranderson** [comment]
Just curious, which one did it?

**Comment by jcmontx** [comment]
Actually both. I first tried the first one and it work. Then moved it all to a class.
