### ISSUE TITLE
WebJob-publish-settings.json scheduler settings vs TimerAttribute scheduler settings

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk-extensions#26]
Hi :wave:

I just noticed that my webjob has the `webjob-publish-settings.json` file [which looks like it has some scheduling settings](http://schemastore.org/schemas/json/webjob-publish-settings.json) in there.

How do these settings compare to the `TimerAttribute` settings? I get that the `TimerAttribute` has CRON settings (which is awesome) .. so what scenario's would u want to set the values in the `...settings.json` file?

**Comment by mathewc** [comment]
So there are actually currently 3 ways of doing scheduled/cron jobs in Azure WebJobs currently. The first was the one you're referring to, which relies on the external Azure Scheduler. The VS tooling will actually guide you that route if you choose to schedule a job in the wizard. It will end up creating Azure Scheduler resources, which will invoke your job via HTTP. See [this post](http://blog.davidebbo.com/2015/05/scheduled-webjob.html) for some nitty gritty details.

Now if you're already using the WebJobs SDK for other reasons, then you might as well use the inbuilt TimerTrigger expression.

There is a third mechanism which also doesn't use Azure Scheduler. See the "scheduled job" section [here](https://github.com/projectkudu/kudu/wiki/Web-jobs).

Before you say anything, yes I know this is a lot of different ways of doing things, and may be confusing :) It is what it is :) You know,

**Comment by PureKrome** [comment]
:smile: :+1: Thank you, again !
