### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by JohanKustner** [Azure/azure-webjobs-sdk-extensions#263]
When building in Visual Studio, a CS8002 warning occurs:

Warning	CS8002	Referenced assembly 'Microsoft.Azure.WebJobs.Extensions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

When running an Azure Web Job, the Azure Web Job continuously fails to start with the following error:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.WebJobs.Extensions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by christopheranderson** [comment]
We don't strong name extensions. We have no plans on starting to strong name it.

**Comment by JohanKustner** [comment]
Hi Christopher,

 

Is that not generally considered bad practice for publicly distributed assemblies? The problem is that I am strong-naming my assembly, which references your assembly. I then get a compiler warning and a run-time error, as per my post. I do not have this problem with the other Azure Web Job assemblies, as they are strong-named. Any particular reason why you cannot strong-name it?

 

Kind Regards,

 

 

Johan Küstner

**Comment by JohanKustner** [comment]
Really!?

 

Kind Regards,

 

 

Johan Küstner
