### ISSUE TITLE
Host should log when explicit host ID causes triggers to not run

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-extensions#264]
For Timer, Cosmos DB, and Event Hub, customers can get tripped up if they set an explicit host ID, because only one host can get a lock at a time. For Timer in particular, I've seen several customer issues, including a recent CRI, that were all caused by the host ID problem.

I suggest that in these cases we log a message such as:

> Host ID has been customized in host.json. Unable to get a lock for trigger X

This will enable CSS and customers to diagnose the problem on their own.

**Comment by christopheranderson** [comment]
Should just always provide a warning, on the primary, when we start with a hardcoded host id.
