### ISSUE TITLE
Can we use a newer version of WindowsAzure.Storage?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk-extensions#27]
Given that a new nightly build is available (as of issue #25 ), I'm trying to add the 3x packages but I cannot because `Microsoft.Azure.WebJobs` has a dependency on `WindowsAzure.Storage >= 4.3.0 <= 5.0.2`.

I'm on `WindowsAzure.Storage v 6.2.0` :/

Is it possible to update?

**Comment by mathewc** [comment]
This is an SDK core issue, and we have an issue for it already [here](https://github.com/Azure/azure-webjobs-sdk/issues/565).

**Comment by PureKrome** [comment]
:+1:
