### ISSUE TITLE
TimerTrigger, next occurrences is wrong

### ISSUE THREAD

**Issue by thejaff2** [Azure/azure-webjobs-sdk-extensions#271]
Microsoft.Azure.WebJobs v2.0.0

The "...next 5 occurrences of the schedule.." printout is calculated from the exiting of the function, but the true schedule is based from the entering of the function. Example below:

```
public static void TestTimerJob([TimerTrigger("00:00:20", UseMonitor = false, RunOnStartup = true)] TimerInfo timer, TraceWriter log)
        {
            log.Info($"Running TestTimerJob() at {DateTime.Now}");
            Thread.Sleep(new TimeSpan(0, 0, 5)); // Sleep for 5 seconds
        }
```

Yields the following output:
```

Executing 'Test.TestTimerJob' (Reason='Timer fired at 2017-08-16T15:45:00.2416955+02:00', Id=59e93cce-6608-46f0-8bc6-f10637c657f0)
Running TestTimerJob() at 2017-08-16 15:45:00
Executed 'Test.TestTimerJob' (Succeeded, Id=59e93cce-6608-46f0-8bc6-f10637c657f0)
The next 5 occurrences of the schedule will be:
2017-08-16 15:45:26
2017-08-16 15:45:46
2017-08-16 15:46:06
2017-08-16 15:46:26
2017-08-16 15:46:46
Job host started
Executing 'Test.TestTimerJob' (Reason='Timer fired at 2017-08-16T15:45:20.2318854+02:00', Id=266645f7-5d71-4bce-8699-6c163ad3f9be)
Running TestTimerJob() at 2017-08-16 15:45:20
Executed 'Test.TestTimerJob' (Succeeded, Id=266645f7-5d71-4bce-8699-6c163ad3f9be)
```

As you see, the first execution is at approx 15:45:00. With a 5 second delay and 20 second interval it prints that the next occurrence will be at 15:45:26, but the true next execution is at 15:45:20.

**Comment by mathewc** [comment]
The next occurrences that are printed out on startup are computed from a single point in time. The schedule can only be computed based on the schedule expression specified in the trigger. We can't know how long your function may run. E.g. you might have a random delay in your function - when we print the expected schedule, of course we can't know what the true schedule will be in that case.

**Comment by thejaff2** [comment]
Ok, are you saying is that the "true" schedule is computed from the start of the function when the function is triggered the first time (ok and expected), but the "next occurrences" printout is computed at the end of the function (and thus will always be misleading if the function takes more than one second)? 
That is what I gather from the example above:

Interval: 00:00:20
First occurrence: 15:45:00
Function takes 5 seconds
Next occurrence printout: 15:45:26
Next occurrence (true): 15:45:20

If so, the printout should at least be removed so as not to confuse developers when debugging.
