### ISSUE TITLE
Allow HTTP Trigger to bind to both request and poco 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-extensions#273]
Support this: https://github.com/Azure/Azure-Functions/issues/401

ScriptBinding has some extra binding magic to support this. That should be in the http extension instead so that it works in all cases.  It currently does not work in direct  SDK cases, which includes Functions VS Tooling.

**Comment by NicolasHumann** [comment]
+1 !!!
I really need this feature as well !

**Comment by TheeJamesLee** [comment]
For reference:

Assuming that you are using the HttpRequestMessage to get headers/query parameters and/or for creating the response back. If so, this will achieve what you need:

`public static async Task<HttpResponseMessage> Run([HttpTrigger(...)]POCO req, IDictionary<string, string> headers, IDictionary<string, string> query)`

(then just build a response back rather then using the helpers off HttpRequestMessage)

The HttpTrigger will bind the Header and Query dictionaries to the 2 dictionaries in the signature above, which is what we do for what we need.

If we need anything more detailed then we just use the main http request object and in the function deserialize the object.

**Comment by MikeStall** [comment]
We need to fix this (and document it so people know about it!). Script + CSX supports it.

**Comment by MikeStall** [comment]
In the CSX path, this is handled here: https://github.com/Azure/azure-webjobs-sdk-script/blob/918b057707acfb842659c9dad3cef0193fae1330/src/WebJobs.Script.WebHost/WebScriptHostManager.cs#L354

**Comment by MikeStall** [comment]
Resolved with https://github.com/Azure/azure-webjobs-sdk-extensions/pull/284

**Comment by baio** [comment]
btw It still not working with core at the moment (

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="RegisterOrgFun.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.8" />
    <PackageReference Include="System.Configuration" Version="2.0.5" />
    <PackageReference Include="FSharp.Core" Version="4.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain.fsproj" />
    <ProjectReference Include="..\..\Utils\Utils.fsproj" />
  </ItemGroup>

</Project>

```

```
[2/23/2018 10:21:57 PM] Reading host configuration file 'C:\dev\doer\doer-hive\DoerUsers\RegisterOrgFun\bin\Debug\netcoreapp2.0\host.json'
[2/23/2018 10:21:57 PM] Host configuration file read:
[2/23/2018 10:21:57 PM] {}
[2/23/2018 10:21:58 PM] Generating 1 job function(s)
[2/23/2018 10:21:58 PM] Starting Host (HostId=desktop5f41kfm-532994629, Version=2.0.11415.0, ProcessId=836, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[2/23/2018 10:21:58 PM] A ScriptHost error has occurred
[2/23/2018 10:21:58 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'Main.run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'req' to type HttpRequest. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

**Comment by ianisms** [comment]
Not working with core 2.2:

        public HttpResponseMessage CreateRoleDefinition(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "roleDefinitions")]
            RoleDefinition roleDefinition,
            HttpRequestMessage req,
            ILogger log)

CreateRoleDefinition: Microsoft.Azure.WebJobs.Host: Error indexing method 'CreateRoleDefinition'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'req' to type HttpRequestMessage. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
