### ISSUE TITLE
Assemblies should be strong named

### ISSUE THREAD

**Issue by JohanKustner** [Azure/azure-webjobs-sdk-extensions#274]
I have raised this issue again, as my previous issue was closed.

I appreciate that this is an open source project, but it is a Microsoft project as well and I am horrified that there are no plans to strong name this assembly.

If you do not appreciate the benefits of strong naming an assembly, then I must say that I am quite concerned.

Surely, you can create a separate branch with a strong named version.

I'll reiterate the issue below:

When building in Visual Studio, a CS8002 warning occurs:

Warning CS8002 Referenced assembly 'Microsoft.Azure.WebJobs.Extensions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

When running an Azure Web Job, the Azure Web Job continuously fails to start with the following error:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.WebJobs.Extensions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by christopheranderson** [comment]
I'm assuming you need to strong name your assembly, which is why you're getting that error. Could you detail what your scenario is for needing to use strong naming?

**Comment by JohanKustner** [comment]
I’d say it is best practice. Code Analysis and Compiler Warnings will always suggest you sign your assemblies. There is very good reason for this and it should be common knowledge and common practice.

**Comment by JohanKustner** [comment]
The specific Code Analysis Warning is CA2210. See https://msdn.microsoft.com/en-us/library/ms182127.aspx.

 

Can I suggest that you read Framework Design Guidelines: Conventions, Idioms, and Patterns for Reusable .NET Libraries (Microsoft Windows Development Series) 2nd Edition by Krzysztof Cwalina and Brad Abrams.

**Comment by christopheranderson** [comment]
It is quite common today for Libraries not to do Strong Naming, including other libraries from Microsoft. After reviewing this with other experts inside of Microsoft, we've decided to not Strong Name our libraries anymore for WebJobs (WebJobs 3.0 will not be strong named). If you can provide a concrete reason for us to do it, we can look into it, but this is something we're confident is no longer a best practice for our scenarios. We do code sign most of our libraries for security reasons, but strong naming doesn't have any practical purposes to us and makes it much harder for people to contribute to us.
