### ISSUE TITLE
DocumentDB in function parameters is always null

### ISSUE THREAD

**Issue by juchom** [Azure/azure-webjobs-sdk-extensions#277]
Could you please confirm if this part of the [documentation](https://github.com/Azure/azure-webjobs-sdk-extensions#documentdb) is still valid?

```
public static void DocumentClient(
    [QueueTrigger("sample")] QueueData trigger,
    [DocumentDB] DocumentClient client,
    TraceWriter log)
{
    var collectionUri = UriFactory.CreateDocumentCollectionUri("ItemDb", "ItemCollection");
    var documents = client.CreateDocumentQuery(collectionUri);

    foreach (Document d in documents)
    {
        log.Info(d.Id);
    }
}
```

I have something very similar in my code:

```
        [FunctionName("Function3")]
        public static void Run([BlobTrigger("mycontainer/{name}", Connection = "AzureWebJobsStorage")]TextReader myBlob, string name,
            [DocumentDB("DDB", "DBCollection", Id = "Id", PartitionKey = "/PartKey")] DocumentClient client, TraceWriter log)
        {
            log.Info($"C# Blob trigger function Processed blob\n Name:{name} \n Size");
        }
```

The client variable is always null. I'm sure the runtime is trying to resolve it because if I don't give the connection string or if some properties in the DocumentDB attribute are missing I have errors.

What am I doing wrong?

I'm using VS 15.3.2
Microsoft.NET.Sdk.Functions 1.0.2
Microsoft.Azure.WebJobs.Extensions.DocumentDB 1.0.0

**Comment by brettsam** [comment]
Is this running locally? If so, you're likely hitting https://github.com/Azure/azure-webjobs-sdk-script/issues/1783. See if you can follow the steps there and get yourself working again.

**Comment by juchom** [comment]
@brettsam Thanks brett this solves the issue.
