### ISSUE TITLE
Need 2.1 beta nightly build

### ISSUE THREAD

**Issue by Mirou117** [Azure/azure-webjobs-sdk-extensions#279]
Hi, I wanna know when 2.1 release gonna be on nuget package. I see only 3.0 beta. 
I need a nightly build from 2.1 beta . thank u.

**Comment by brettsam** [comment]
2.1-beta releases are still going out to the feed. It's a little confusing b/c the 3.0 builds show up as newer so you have to manually select the latest 2.1.0-beta1 release.

For example, here's one from a couple days ago: https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs/2.1.0-beta1-11007
