### ISSUE TITLE
Remove RetryAsync from DocumentDBUtility

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-extensions#280]
Since DocDB 1.8, the client has handled retries internally. There's no need for this utility anymore and we should remove it and the related tests. We should sync with the DocDB team to find out if the defaults will work best for us.

**Comment by christopheranderson** [comment]
@brettsam - should we put this in triaged or are you fixing this?

**Comment by brettsam** [comment]
I want to remove this. It's not really a bug but there's a bunch of code that we don't need anymore and probably never gets hit. I'll assign it to the next Sprint and follow up with DocDB to make sure the defaults will work for us. It'd be nice to not have this code following us around if it's not being used.
