### ISSUE TITLE
DocumentDB Binding Error Message Not Specific

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-webjobs-sdk-extensions#286]
Please provide a succinct description of the issue.

Code Example where the database and collection is switched
```csharp
[FunctionName("ProcessQueue")]
        public static async Task RunQueue(
            [QueueTrigger("myqueue", Connection = "AzureWebJobsStorage")]object message, 
            [DocumentDB("collection", "database", ConnectionStringSetting = "conn_documentdb", Id = "{Id}", CreateIfNotExists = true)] dynamic inDoc, 
            [DocumentDB("collection", "database", ConnectionStringSetting = "conn_documentdb")] IAsyncCollector<dynamic> outDocs ,
            TraceWriter log)
        {

            if (message != null && inDoc != null)
            {
                await outDocs.AddAsync(message);
                await SendToTeams(message);
            }
        }
```

**Error Message** (On *outDocs.AddAsync*)

```bash
Message: {"Errors":["Resource Not Found"]} ActivityId: 7fc42ced-228a-42c7-9ca7-c5b798abde04, Request URI: /apps/7dc938ac-8c47-4af3-9760-5e80284624b0/services/c192b434-6ef5-4d86-88c8-268b19914201/partitions/42fe70a5-b0ac-4068-8b29-4b7fb97b06b1/replicas/131483475389333585s
```

Messaging should state that the database and/or collection does not exist.

cc:// @lindydonna @mattchenderson

**Comment by lindydonna** [comment]
CC @brettsam 

I'm guessing we're just returning the error that the Document DB SDK gave us, which is not great. Ideally we'd work with them to improve the error messages for everyone.

**Comment by brettsam** [comment]
Yeah, that's their message and it doesn't have anything useful that we can pull to show that would be more helpful. Instead, I've changed this to throw a new exception with the relevant collection and database names. PR is out now.
