### ISSUE TITLE
Not documented how NotificationHubAttribute can send broadcast push

### ISSUE THREAD

**Issue by RocketPop** [Azure/azure-webjobs-sdk-extensions#291]
Please provide a succinct description of the issue.

There is unclear documentation for the tag behavior of NotificationHubAttribute. The only worthwhile search hits lead to: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.NotificationHubs/NotificationHubAttribute.cs which doesn't fully specify how the TagExpression field works. In my Azure Function to construct messages, I set my variable holding the tag expression to "" which in the end sent messages to no clients. It turns out TagExpression needs to be null. Examples throughout the rest of the SDK show their example tags to be "" - this is inconsistent.

#### Repro steps

Provide the steps required to reproduce the problem

1. Write an azure function to send push messages to a tag (any sample will do)
2. Set the TagExpression to ""
3. Send and 

#### Expected behavior

All registered clients should receive a push. I'm not sure of the "correct" behavior - but most azure notification hubs samples and articles (not webjob versions) will show their tags to be "" to send broadcast messages - this is inconsistent.

#### Actual behavior

None of the registered clients will receive a push. You must instead set the TagExpression to null to send broadcast to all hub subscribers.

#### Related information 

I started with this sample here: http://blog.repsaj.nl/index.php/2016/08/azure-custom-function-bindings-notification-tags-in-cordova-apps/ that met my use case of dynamic tag/hub combo

**Comment by paulbatum** [comment]
@pragnagopa can you help out here to figure out if this is a bug or a documentation issue?

**Comment by pragnagopa** [comment]
If you are not using tags, you do not need to specify "TagExpression". Here is a sample function.json for NotificationHub output:
```
{
      "type": "notificationHub",
      "name": "notification",
      "hubName": "<hubname>",
      "connection": "<NH connection string app setting>",
      "direction": "out"
 }
```
Here is a sample to [send to tags](https://stackoverflow.com/questions/40165148/azure-notification-hub-registration-from-android/40224435#40224435)

Few more [samples ](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/v2.x/src/ExtensionsSample/Samples/NotificationHubSamples.cs) showing how to use NotificationHub attribute.

Documentation [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-notification-hubs#functionjson-file-example) needs to be updated to remove tagExpression. Opened [issue ](https://github.com/Azure/Azure-Functions/issues/712)to track this.

**Comment by pragnagopa** [comment]
Closing this for now.  Please reactivate if you still run into errors.
