### ISSUE TITLE
Add more information to TimerInfo

### ISSUE THREAD

**Issue by kamranayub** [Azure/azure-webjobs-sdk-extensions#30]
Add information about missed occurrences so we can take action based on missed schedule

Azure/azure-webjobs-sdk#622

**Comment by tbertenshaw** [comment]
Also interested in this. I'm currently trying to stop duplication of TimerEvents. I am finding if we publish an update to the webjob(webpublish) it will fire the timer event even if it has already run that day. for a schedule defined as.

``` csharp
public class DailyRequestReportSchedule : WeeklySchedule
	{
		public DailyRequestReportSchedule()
		{
			String cronExpression = ConfigurationManager.AppSettings["RequestReportCronExpression"];
			cronExpression = String.IsNullOrEmpty(cronExpression) ? "00:30:00" : cronExpression;


			int[] cron = Array.ConvertAll(cronExpression.Split(':'), s => int.Parse(s));
			var ts = new TimeSpan(cron[0], cron[1], cron[2]);

			Add(DayOfWeek.Monday, ts);
			Add(DayOfWeek.Tuesday, ts);
			Add(DayOfWeek.Wednesday, ts);
			Add(DayOfWeek.Thursday, ts);
			Add(DayOfWeek.Friday, ts);
			Add(DayOfWeek.Saturday, ts);
			Add(DayOfWeek.Sunday, ts);
		}
	}
```

I'm finding the TimerInfo.Schedule property doesn't have a date/day constituent so I couldn't parse and check which day it is firing for. My intention was to determine if the event fired and it was greater than an hour past the defined firing time; then return without running the logic, to prevent the duplication we are seeing.

**Comment by mathewc** [comment]
What version of the package are you using - recommend trying with the latest released version (1.0.1).

Also, might consider using a single cron expression for your schedule if all you're trying to do is run at the same time each day. For example, if you're trying to run at 12:30 AM each day you could use `[TimerTrigger("0 30 0 * * *")]`. That might simplify things for you.

I think if you had the next/last schedule information available on TimerInfo, that would help you?

**Comment by kamranayub** [comment]
For me, `CurrentOccurrence` (what time am I being called *for* now?),
`LastOccurrence` (when was I last called?) and `LastMissedOccurrences`
(what did I miss?) would be fantastic.

**Comment by tbertenshaw** [comment]
I'm using the latest released version extensions 1.0.1 and webjobs and core 1.1.1. Yeah if i could establish what timer should have fire last and next i can prevent duplicate firing.

**Comment by slippyr4** [comment]
I'm also seeing duplicate triggers about 50% of the time, when I deploy (by publishing a web app and swapping slots - the staging slot has webjobs stopped). My TimerTrigger attribute is as follows: [TimerTrigger("0 0 8 * * *", RunOnStartup = false)]

**Comment by mathewc** [comment]
@tbertenshaw Is your scenario also involving slots?

**Comment by tbertenshaw** [comment]
@mathewc  yes we are also using slots, however we are not swapping them, they are just storing our 3 environments, Prod,UAT,InternalTest, we redeploy to each environment from VisualStudio when needed. At some point we will configure C.I. but not yet. They are all using the same storage account, but (all queues and other application settings are separated and Sticky Slot Settings). as per https://github.com/Azure/azure-webjobs-sdk-extensions/issues/31 we have used seperate lockfile Guids.

**Comment by mathewc** [comment]
@kamranayub I've added a new `ScheduleStatus` class in the work I did for https://github.com/Azure/azure-webjobs-sdk-extensions/issues/35. If that were made available on `TimerInfo` would that meet your needs? It would provide access to both the last execution time as well as the one you are currently being invoked for. `TimerInfo.Schedule` is already there, so you can use that to compute missed occurrences from a start date.

**Comment by kamranayub** [comment]
Yes that would work great! Thanks a lot.

**Comment by mathewc** [comment]
Added `TimerInfo.ScheduleStatus` in commit https://github.com/Azure/azure-webjobs-sdk-extensions/commit/7daa1d945ff86f8866bf314f386dcc0e2774ec1d. Prerelease available now on myget feed (**1.0.2-alpha-10231**).

**Comment by tbertenshaw** [comment]
So I Published my webjob with the alpha libraries, and logging reveals

```
[02/08/2016 06:59:55 > 4bd219: INFO] Executing: 'TimerFunctions.DailyRequestReport' - Reason: 'Timer fired at 2016-02-08T06:59:54.9769809+00:00'
[02/08/2016 06:59:56 > 4bd219: INFO] DailyRequestReport Timer job fired!
[02/08/2016 06:59:56 > 4bd219: INFO] Status: Last='2/7/2016 7:00:00 AM', Next='2/8/2016 7:00:00 AM', IsPastDue=False
[02/08/2016 06:59:57 > 4bd219: INFO] Executed: 'TimerFunctions.DailyRequestReport' (Succeeded)
[02/08/2016 07:00:00 > 4bd219: INFO] Executing: 'TimerFunctions.DailyRequestReport' - Reason: 'Timer fired at 2016-02-08T07:00:00.0129195+00:00'
[02/08/2016 07:00:00 > 4bd219: INFO] DailyRequestReport Timer job fired!
[02/08/2016 07:00:00 > 4bd219: INFO] Status: Last='2/8/2016 6:59:54 AM', Next='2/8/2016 7:00:00 AM', IsPastDue=False
[02/08/2016 07:00:01 > 4bd219: INFO] Executed: 'TimerFunctions.DailyRequestReport' (Succeeded)
```
the 2nd and 3rd and 6th and 7th, lines are my console.logs and the others are autogenerated by the libraries I believe.  You can see that the timer fires just before and just after the hour.  Incidentally my timer is running using a WeeklySchedule as I couldn't find another way of customising the time the timer fired based on a applicationsettings.
this is the method declaration incidentally.

```csharp
public async void DailyRequestReport([TimerTrigger(typeof(DailyRequestReportSchedule))] TimerInfo timerInfo, TextWriter log, ExecutionContext context)
{
}
```

**Comment by mathewc** [comment]
I created a [new issue](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/38) for that, thanks. We'll fix.

**Comment by mathewc** [comment]
@tbertenshaw First, I've added `INameResolver` support for TimerTrigger in the latest pre-release drop. So for your daily schedule, you can now use `[TimerTrigger("%RequestReportCronExpression%")]`.

Secondly, I'm unable to repro your above issue with the double timer firings. Can you try with this latest version, using the INameResolver/Cron method rather than the custom TimerSchedule type and tell me if you still see an issue. If so, please log a bug for that with repro steps. Thanks :)
