### ISSUE TITLE
ExternalFileTrigger fails with nullref exception with files over trigger limit

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-webjobs-sdk-extensions#307]
While attempting to use the External File Trigger on an FTP drop, the trigger errored out with a null reference exception due to an undocumented file size limitation.

#### Repro steps
1. Create an Azure Function which uses the [External File Trigger](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-external-file#external-file-trigger-binding)
2. Drop a file over the trigger limit in size (was 100mb, now I think is 300mb, may increase in future) in to the place being watched by the function

#### Expected behavior
I'd expect this to work. However due to a (as yet undocumented) file size limitation, it doesn't.
Since it doesn't work, an error message akin to "File contents exceeds xxxxx" or the like would have been more helpful.

#### Actual behavior
Function errors out with
```
2017-10-03T18:15:28.266 Exception while executing function: Functions.TimerTriggerCSharp1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'inputFile'. Microsoft.Azure.WebJobs.Extensions.ApiHub: Object reference not set to an instance of an object.
```
#### Known workarounds
None.

#### Related information 
Function developed wholly within Azure Functions Portal IDE

**Comment by brandonh-msft** [comment]
ping.

**Comment by paulbatum** [comment]
@safihamid Is there a known workaround for this?

**Comment by brandonh-msft** [comment]
I believe this limit has been increased to 300mb and is on its way to 1GB however should somebody drop a file in that is over the limit, w/o a fix this behavior is likely to still happen.

**Comment by safihamid** [comment]
ExternalFileTriggers were an experimental feature and we are not not actively working on it anymore an no plans to GA. our recommendation is to use LogicApps + Functions.
