### ISSUE TITLE
ability to customise the singleton lock filename

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/azure-webjobs-sdk-extensions#31]
We have a couple of environments which share resources in the same blob storage account. We then encounter problems with `TimerTrigger`-ed  Queues as they use the same lockfile.

Would it be possible to allow the supply of the container lockfile GUID. And if possible could this be something which is acquired from Environmental Settings on startup. i.e. something like
```csharp
			if(String.IsNullOrEmpty(Environment.GetEnvironmentVariable("LockFileGuid")))
			{
				Environment.SetEnvironmentVariable("LockFileGuid",Guid.NewGuid().ToString());
			}
			var jobHostConfiguration = new JobHostConfiguration
			{
				LockFileGuid = Environment.GetEnvironmentVariable("LockFileGuid")
			}
```

**Comment by mathewc** [comment]
I'm not sure I understand exactly. Are you talking about the singleton lease blobs (as described [here](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger))? If so, the ID in the path comes from the JobHostConfiguration.HostId. Normally a HostId isn't set explicitly - if you haven't set one, we generate one for you. In this [recent issue](https://github.com/Azure/azure-webjobs-sdk/issues/614), we discussed a pattern of conditionally setting the HostID to an explicit value for enabling multi-developer scenarios. Something like that would also work for running in different environments.

**Comment by tbertenshaw** [comment]
Hi @mathewc yes your suggestions above seem to work. I noticed the timer trigger used a singleton lock and i noticed that production/UAT and local dev environments (since we need to use the same blobstorage) were having intermittant firing issues. Setting the webjob tracing level to verbose showed me it was due to them all trying to get a lock on the same blob container.  Thus being able to set the HostId will and does appear to resolve this issue.  

Incidentally if i use ``` jobHostConfiguration.HostId = Guid.NewGuid().ToString("N");```
it will generate a new guid each time the webjob is restarted,and thus a new storage container for the lock. Are the storage containers cleaned up or will they remain there?

**Comment by mathewc** [comment]
I wasn't suggesting you regen one each time on startup - I mentioned Guid.ToString("N") to show a way for you to generate a static one. You can also use characters + descriptive names in your ID if that helps, but the ID should be static for the lifetime of the WebHob host.

**Comment by tbertenshaw** [comment]
thanks @mathewc,  How do I generate but persist a Guid, in this scenario (without generating it and hardcoding it with a compiler pre-processor variable). The only thing I can think of is to store the Guid/identifier in the Azure WebSite.ApplicationSettings (or webjob app.config).

**Comment by mathewc** [comment]
Yes, it would be a hard coded app setting.
