### ISSUE TITLE
Timer Trigger: Is the time(s) GMT or local to the Azure VM region?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk-extensions#32]
If i have a Timer Trigger webjob and say: _run this at 2am, 6am and 3pm_ .. what times will this _really_ run at?

~~~eg. is that 2am @ GMT? or the system time of the azure VM the web job exists on (which I'm assuming is the local time of the region ...) ?~~~

AH! the commit [Use Local time (not UTC) in TimerTrigger scheduling](https://github.com/Azure/azure-webjobs-sdk-extensions/commit/f6c31de78492a8663f88d0873931bb48412148c7) says exactly that .. it's now **local time** :smile: (and all the `UtcNow`'s are replaced with `Now`) 

... so what is _local time_ (just to confirm). I know that, that code uses the machine's system time - but what time is this set to -- the time of the region or something?

**Comment by mathewc** [comment]
I believe the local time in all Azure stamps is set to be the same as UTC, but don't quote me on that.

Regardless, the good thing about using Local time is that you can now control the actual timezone by changing the timezone of your WebApp ([details here](http://blogs.msdn.com/b/tomholl/archive/2015/04/07/changing-the-server-time-zone-on-azure-web-apps.aspx)).

**Comment by PureKrome** [comment]
Hi @mathewc - sorry to cast 'ressurect dead' on this thread, but I've been watching my webjob with more scrutiny over the last few days / week (as my bugs are ironed out) and noticed that changing the timezone of the webjob is not working for me.

Or (more accurately) the CRON JOB is not working as expected .

These are my two methods I have in `functions.cs` :

- `public static async Task Method2Async([TimerTrigger("0 0 2 * * *", UseMonitor = false)] TimerInfo timer)`
- `public static async Task Method2Async([TimerTrigger("0 30 2 * * *", UseMonitor = false)] TimerInfo timer)

First one is for 2am, 2nd is 2:30am -> and by that, I'm hoping for 2am/2:30am Australia Eastern Standard Time (i.e. AESTD).

Looking at my logging, they are getting fired off at 1pm and 1:30pm AESTD. Which is 2am UTC time.

Following the instructions from your previous post, i did the following:

- Added a setting to `appsettings`
- Added an entry to the website appsettings

![image](https://cloud.githubusercontent.com/assets/899878/12837814/4cf6125a-cc1a-11e5-97f6-a94c67999be5.png)

![image](https://cloud.githubusercontent.com/assets/899878/12837956/d674a55e-cc1b-11e5-90db-e994a449f88e.png)


I know i can just put the UTC in there .. and then change it over when daylight savings switches ... but I'd like to know if there's a cleaner solution and I'm not doing it right :/

**Comment by mathewc** [comment]
@davidebbo David - WEBSITE_TIME_ZONE is supposed to work, right? I do see others complaining of issues on SO in regards to this setting not working (e.g. [here](http://stackoverflow.com/questions/30939990/changing-timezone-on-azure-web-apps-doesnt-work-for-datetimeoffset-now)).

**Comment by davidebbo** [comment]
It does work. e.g. set it to `Eastern Standard Time` and type `time` in Kudu Console to see the change reflected. But per that SO question, there appears to be some issue when using `DateTimeOffset.Now`, and I don't know what the deal is.

**Comment by PureKrome** [comment]
Confirmed that it's working @mathewc. I just checked my Kudu Console for the website which my webjob runs within ... and the time is correct  - it's exactly the same as my localhost computer.

So, should I file a new issue about this? 

I'm really looks like the cron job -specific- times are not respecting the timezone of the website.

**Comment by mathewc** [comment]
Yes please create another bug if you think this isn't working. TimerTrigger uses local time everywhere, and I also verified that the NCronTab library we use is also returning Local times, so I'm not sure what could be causing a problem.

**Comment by davidebbo** [comment]
It probably comes down to the `DateTimeOffset` bug. Would be nice to get that fixed, but it's a .general Web App sandbox thing not related to WebJobs.
