### ISSUE TITLE
SendGrid extension not working, Could not load file or assembly SendGrid, Version=9.8.0.0

### ISSUE THREAD

**Issue by sebastianroesch** [Azure/azure-webjobs-sdk-extensions#325]
I tried using the SendGrid extensions in .NET Core, but did not manage to get it to work. When running the func host, it fails with this error:

[07/11/2017 07:58:53] Job host started
[07/11/2017 07:58:53] The following 1 functions are in error:
[07/11/2017 07:58:53] ResponseCodeCheckTrigger: Could not load file or assembly 'SendGrid, Version=9.8.0.0, Culture=neutral, PublicKeyToken=4f047e93159395ca'. The system cannot find the file specified.

#### Repro steps

Provide the steps required to reproduce the problem

1. I checked out the .NET Core Function example from https://github.com/lindydonna/CSharpHttpCore.git

2. I added the SendGrid extensions: 

```
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta3"/>
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SendGrid" Version="3.0.0-beta3"/>
```

3. I added an output binding:
```
    {
      "name": "message",
      "type": "sendGrid",
      "direction": "out",
      "apiKey": "XXXX",
      "to": "{ToEmail}",
      "from": "{FromEmail}",
      "subject": "Subject"
    }
```

4. I added an Import for SendGrid and the out parameter:

```
using System;
using SendGrid.Helpers.Mail;

namespace HttpTriggerCore
{
    public class ResponseCodeCheckTrigger
    {
        public static void Run(TimerInfo myTimer, TraceWriter log, out SendGridMessage message)
        {
        }
    }
}
```

#### Expected behavior

The function should run and not throw an error.

#### Actual behavior

The function host throws this error:

[07/11/2017 07:58:53] Job host started
[07/11/2017 07:58:53] The following 1 functions are in error:
[07/11/2017 07:58:53] ResponseCodeCheckTrigger: Could not load file or assembly 'SendGrid, Version=9.8.0.0, Culture=neutral, PublicKeyToken=4f047e93159395ca'. The system cannot find the file specified.

#### Related information 

I also tried including SendGrid directly. I noticed from the sources that the SendGrid extension depends on SendGrid 9.9, so  I tried including `<PackageReference Include="Sendgrid" Version="9.9.0"/>`, but without success. I also tried the same with SendGrid version 9.8, but no change. 

Where does the dependency on 9.8 come from? And how can I resolve it? Any configuration I missed?

**Comment by paulbatum** [comment]
@sebastianroesch Does this still repro if you create a new v2 function app in Visual Studio? Please make sure you are using the latest version of Visual Studio and the webjobs/functions tools and then update your NuGet for Microsoft.NET.Functions.Sdk to version 1.0.8.

**Comment by sebastianroesch** [comment]
@paulbatum sorry can't reproduce it anymore, we switched to a different SMTP client and got it working with that.

**Comment by paulbatum** [comment]
Understood!
