### ISSUE TITLE
TimerTrigger - support to INameResolver.

### ISSUE THREAD

**Issue by ThomasVercoutre** [Azure/azure-webjobs-sdk-extensions#33]
Is it possible to add support to INameResolver for TimerTrigger  ?

**Comment by mathewc** [comment]
Thanks for logging the bug. Yes it makes sense for us to add this.

**Comment by ThomasVercoutre** [comment]
Thanks. Let me know when you'll have a pre-release so that I can test it.

**Comment by mathewc** [comment]
This feature has been added. Please give it a try and let me know if it works for you. It's available on the nightlies myget feed (version 1.0.2-alpha-10232).

**Comment by ThomasVercoutre** [comment]
I've just tested, It seems to work for me. The INameResolver.Resolve function has been hit and my jobs are triggered according to the value in my config file.
Thanks.

**Comment by pjganesh** [comment]
I'm trying to test this feature, but couldn't locate the version 1.0.2-alpha-10232 mentioned by mathewc. The latest version found in MyGet feed is 2.0.0-alpha-10343. Tried installing this version and tested it - its not working. Can anyone please help in this ?

**Comment by mathewc** [comment]
I just tried the latest version, and the INameResolver works fine. E.g. below is my code which works. What exactly is not working for you? Can you point me to a public repo that contains a repro or something?

```csharp
public class Functions
{
    public static void TestTimer([TimerTrigger("%TestSchedule%")] TimerInfo timer)
    {
        Console.WriteLine("TestTimer fired!");
    }
}

class Program
{
    static void Main(string[] args)
    {
        JobHostConfiguration config = new JobHostConfiguration();
        config.NameResolver = new MyResolver();
        config.UseTimers();

        JobHost host = new JobHost(config);
        host.RunAndBlock();
    }

    private class MyResolver : INameResolver
    {
        public string Resolve(string name)
        {
            if (name == "TestSchedule")
            {
                return "*/10 * * * * *";
            }

            return null;
        }
    }
}
```

**Comment by pjganesh** [comment]
Hi @mathewc,
I forgot to check with CRON expressions earlier. Is there any chance to use TimeSpan instead of Cron ?

**Comment by mathewc** [comment]
Yes, TimerTriggerAttriubte supports a TimeSpan string as well. Please see the xml doc for the attribute.

**Comment by pjganesh** [comment]
I tried it earlier in **MyGet feed version 2.0.0-alpha-10343** with TimeSpan string and it didn't triggered it.

This was the issue I reported on 6/13.

**Comment by mathewc** [comment]
I just tried - the above example works with the cron expression `*/10 * * * * *` replaced with `00:00:10`.

**Comment by abatishchev** [comment]
I think the problem here is that cron expressions are being evaluated against INameResolver. And timespans are not.

**Comment by mathewc** [comment]
Please provide a repro - it works for me. I can put the timespan in the name resolver.

**Comment by venkatvangal** [comment]
Can we get this package from Nugget? instead of MyGet? now the nugget version for webjobs extension is v.1.0.1
