### ISSUE TITLE
Forcing VS2017 to update tooling

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-extensions#336]
VS2017 (15.4.4) was modified and I needed to re-install Azure Functions tools.
Unfortunately, the extension (Azure Functions and Web Jobs Tools) is not updating nor can I force it to do so to get the latest version (15.0.31114.0).

![image](https://user-images.githubusercontent.com/1309622/33225035-b0185d6a-d12d-11e7-8492-914f0daf4490.png)

Any ideas how to address it? Thanks.

**Comment by paulbatum** [comment]
This issue was moved to Azure/Azure-Functions#611
