### ISSUE TITLE
FileSystemScheduleMonitor is inadequate when using deployment slots in app service

### ISSUE THREAD

**Issue by slippyr4** [Azure/azure-webjobs-sdk-extensions#35]
This is further to issue 30 (https://github.com/Azure/azure-webjobs-sdk-extensions/issues/30) where tbertenshaw finds that when he deploys, some timer jobs are refiring.

I'm also seeing duplicate triggers most of the time, when I deploy (by publishing a web app and swapping slots - the staging slot has webjobs stopped). My TimerTrigger attribute is as follows: [TimerTrigger("0 0 8 * * *", RunOnStartup = false)]

----  EDIT -----

I believe the duplicate firing is because internally WebJobs.Extensions is using a class FileSystemScheduleMonitor to record the firing of events. This writes lastrun/nextrun json data in .status files in the webjob data directory. Therefore, when you swap slots, this is swapped out and the webjob has no idea it's already ran. This is a bit of a showstopper for some use cases. 

There really needs to be an option to store this data in blob storage instead.

**Comment by mathewc** [comment]
Correct, the schedule status is stored in the D:\HOME\Data location of the WebApp by default, and files do not swap. The schedule monitor was designed as a strategy pattern to allow just what you suggest - a strategy that stores to blob. I do think we should add blob storage, perhaps making that the default.

**Comment by slippyr4** [comment]
I agree. Blob storage is the sensible default because then you will get the behaviour you might expect, when using slots. IMO the status data should be stored with either AzureWebJobsStorage or AzureWebJobsDashboard connections; then everything works as expect when you are using different connections in slots (which I am not, at the moment - I have WEBJOBS_STOPPED in staging).

As an aside, whilst I see that you can replace the schedule monitor in the public property on TimersConfiguration, it'd be nice to have a constructor overload on TimersConfiguration that takes a ScheduleMonitor.

**Comment by rustd** [comment]
Adding BlobStorage and making it default is a good idea. We should try to get this in for the next release. :)

**Comment by slippyr4** [comment]
If you do, I'll buy everyone cakes. :)

**Comment by mathewc** [comment]
This has been addressed in prerelease package version **1.0.2-alpha-10228** ([instructions here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)). There is now a new `StorageScheduleMonitor` which is the default. It stores its schedule information in the **azure-webjobs-hosts** container, under paths of the format `timers/{hostId}/{timerName}/status`.

Please kick the tires on this and let me know if it works for you. Commit: https://github.com/Azure/azure-webjobs-sdk-extensions/commit/5473e72c032d4eb5a49bd7bd250f27e1cdc7b91e

**Comment by slippyr4** [comment]
Thanks guys. I'm going to test this in production today and do some swaps etc, and see how it goes. I'll feed back soon.

**Comment by slippyr4** [comment]
I'm happy that this is working nicely. Thanks for the speedy turnaround. Is there an ETA on 1.0.2?

**Comment by mathewc** [comment]
Perhaps in a month. I just set the due date on the 1.0.2 milestone to a month out. We'll keep that updated. Thanks.
