### ISSUE TITLE
Webhooks - Am I really giving out my publisher user/pass in my webhook URL??

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-webjobs-sdk-extensions#36]
Per the docs, the webhook callback URLs must be in the following format: `https://{uid}:{pwd}@{site}/api/continuouswebjobs/{job}/passthrough/{*path}`

I tried performing the callback without the user/pass info on there and sure enough I'm getting 401'd. 

Surely I'm not the only one who considers putting my Azure Web App's publisher username and password in the URL that I'm handing out to third party systems as a pretty big security hole? Most web hooks integration is handled by client secrets already (as is pointed out in the GitHub documentation). So typically one doesn't need any additional security beyond that and I for one especially wouldn't want that tied to my publishing identity.

**Comment by christopheranderson** [comment]
We're working on cleaning up that experience, but for now, you can easily just expose an API on your site root which forwards the webhook call to the WebHook. I've also used something like [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) deployed on my main site to just passthrough calls to my WebHooks to my scm site - but this requires taking over the whole main site.

Beyond those work arounds, what would be preferable - 
a) Just opening those scm endpoints (no basic auth) 
b) Are you ok with the notion of having a dedicated "App" for your non-scm protected WebHooks, and an app setting to expose them on the main site?

Thanks for the feedback

**Comment by mathewc** [comment]
I'll add that yes, we are totally aware that people don't want to use basic auth for their WebHooks. We know we don't have the right model yet here for WebJobs WebHooks running behind the Kudu SCM endpoint (which requires the basic auth). That's why the WebHooks portion of this library remain in beta. For some trusted scenarios where you completely trust (or perhaps own) the sender you're registering the hook with, it might be acceptable (but not ideal).

**Comment by drub0y** [comment]
@christopheranderson  Yeah, I mean, I was _hoping_ to use this, but given this limitation right now I think we're just going to expose an ASP.NET WebHooks based API ourselves right now. I just wanted to make sure you guys are thinking about making this a better experience because it's a great idea!

As far as options going forward, I'm ok with either A or B to be honest, but, as mentioned, most webhooks stuff is already secured in some way with client secrets so I'd probably just opt to use A.

**Comment by mathewc** [comment]
Closing this because this is a known issue. We won't ship this way.
