### ISSUE TITLE
How to define a cron expression that will trigger the job run at last day of every month?

### ISSUE THREAD

**Issue by rukai-kooboo** [Azure/azure-webjobs-sdk-extensions#361]
Hi There,
I recently want to build a new job that needs to run at the last day of month, search google, see:
https://stackoverflow.com/questions/45861275/cron-expression-which-run-on-the-last-day-of-the-every-month

It seems we don't support: 0 0 11 L * *
![image](https://user-images.githubusercontent.com/4899310/34868093-a4c96312-f7bd-11e7-8f65-1deeb0e6b35a.png)

Do you have any idea to help me out?
Thanks!

**Comment by brettsam** [comment]
We don't currently support 'L'. We use ncrontab to parse the cron expression and the author has noted that this is not supported: https://github.com/atifaziz/NCrontab/issues/9

One alternative I've seen: Set a cron expression for the 28-31 or each month and have the function itself check to see if it's actually the last day of the month. If not, exit; if so, continue.
