### ISSUE TITLE
CosmosDB DocumentClient Output Bindings

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-extensions#362]
_From @TPoise on November 29, 2017 23:18_

Hi,

Love Azure Functions as well as CosmosDB.  In order to do more advanced things with Cosmos, we create our own instance of DocumentClient.  However, this doesn't scale very well can will cause socket exhaustion very quickly for us ("An attempt was made to access a socket in a way forbidden by its access permissions").  As told in other issues here on Github, using the DocumentClient input binding will help solve this issue for input scenarios.  However from the docs, and experimentation, there's no way to get a DocumentClient instance for output scenarios.

#### Expected behavior

Should be able to create an output binding that can I can cast into a DocumentClient and use this as a pre-warmed singleton instance of the connection to CosmosDB

Example method signature would be something like:
```csharp
public static Task Run(MyPoco poco,  DocumentClient cosmosClient)
{
       
       cosmosClient.Upsert(poco);

}
```
#### Actual behavior

No way to perform the scenario now.

#### Known workarounds

Create your own instance, which can lead to port exhaustion.

_Copied from original issue: Azure/azure-webjobs-sdk-script#2175_

**Comment by brettsam** [comment]
It may be a bit of a misnomer -- but if you use an input binding and request a DocumentClient, you can use that DocumentClient to do anything you want. We call it 'input' b/c we are giving you something to use. Feel free to create documents with that client; there's nothing special about it that restricts this.

As an aside, if you must create your own DocumentClient, you can do that as long as you make it static (so only one is created per function app). I've written some docs up about that here: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Managing-Connections
