### ISSUE TITLE
"The next 5 occurrences of the schedule will be:" <- can this logging state be for 'Info' instead of 'Verbose'?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk-extensions#37]
When I run my webjeb with `Verbose` logging, I can see this :

```
The next 5 occurrences of the schedule will be:
[02/03/2016 23:39:55 > 44c742: INFO] 2/5/2016 2:00:00 AM
[02/03/2016 23:39:55 > 44c742: INFO] 2/6/2016 2:00:00 AM
[02/03/2016 23:39:55 > 44c742: INFO] 2/7/2016 2:00:00 AM
[02/03/2016 23:39:55 > 44c742: INFO] 2/8/2016 2:00:00 AM
[02/03/2016 23:39:55 > 44c742: INFO] 2/9/2016 2:00:00 AM
```

which is awesome. But i don't see it when logging is set to `Info` (ie. for our production webjob).

Could this information please be promoted to `Info` level, if my guess is accurate?

**Comment by PureKrome** [comment]
Side topic: 

`[02/03/2016 23:39:55 > 44c742: INFO] 2/9/2016 2:00:00 AM`

see the word `INFO` in there? I've never seen that really change to something different (like VERBOSE) .. which was why I was confused for a while.

(Unless i've totally made incorrect guesses about all of this).

**Comment by mathewc** [comment]
I don't have a problem with this being Info rather than Verbose.

Regarding the INFO output - that is due to the fact that there are actually 2 logging systems / levels going on here. Anything written to console out by the SDK JobHost is treated as INFO in the Kudu Continuous WebJobs runner.

**Comment by PureKrome** [comment]
>I don't have a problem with this being Info rather than Verbose.

:tada: :balloon: :cake: :sunglasses:

**Comment by brettsam** [comment]
So I thought this was going to be dead-simple. But turns out we actually prevent 'Info' logging by default: https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/ConsoleTraceWriter.cs#L59

I can get around this by specifying "WebJobs.Execution" as my source for the log. @mathewc, is that what you'd expect an extension to have to do in order to log to the console?

**Comment by mathewc** [comment]
Addressed via @brettsam's commit
