### ISSUE TITLE
Should be able to write multiple document using CosmosDB output binding using Node.js 

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-webjobs-sdk-extensions#376]
There should be a way to write multiple documents For Node.js functions and the CosmosDB output bindings and documentation for it.

[Documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb#output) on the CosmosDB output binding has a small note on "To create multiple documents, you can bind to ICollector<T> or IAsyncCollector<T> where T is one of the supported types" for .NET but nothing for Node.

**Comment by fabiocav** [comment]
@brettsam may have some information on how this can be done today.

/cc @pragnagopa

**Comment by brettsam** [comment]
You can return an array from a javascript function and we'll insert all of the documents. Here's an example: https://github.com/Azure/azure-functions-host/blob/v1.x/test/WebJobs.Script.Tests.Integration/TestScripts/Node/DocumentDBOut/index.js 

```
context.bindings.relatedItems = [
    { related: input },
    { related: input },
    { related: input }
];
```
If that covers what you're trying to do, we'll need to add this to the docs (we can use this issue to track that).

**Comment by nzthiago** [comment]
I see, thank you - that is what I was after, good to see it's possible. Would it be easy to add to the docs here?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb#output 

If you know the steps to get an example added there then please do, otherwise I can give it a try

**Comment by nzthiago** [comment]
Have passed this as documentation feedback

**Comment by captainmike** [comment]
Two years later, still not yet in the docs, and that's how I stumbled upon this post. How do we make this happen?

**Comment by nzthiago** [comment]
Created this feedback on the Output Binding page to get reviewed https://github.com/MicrosoftDocs/azure-docs/issues/52575

**Comment by pragnagopa** [comment]
cc @mhoeger as FYI.
