### ISSUE TITLE
Attempting to register an extension throws an error

### ISSUE THREAD

**Issue by wartmanrp** [Azure/azure-webjobs-sdk-extensions#383]
Please provide a succinct description of the issue.

When attempting to register extensions using the cli commands, I am receiving the error "Value cannot be null. Parameter: Stream.

#### Repro steps
1. Step A

Attempts to use either of the following commands results in the aforementioned error (in powershell running as admin)

`func extensions install --package Microsoft.Azure.WebJobs.Extensions.Dura
bleTask --version 1.2.0-beta3`
`func extensions install --package Microsoft.Extensions.Configuration.AzureKeyVa
ult -v 2.1.0-preview1-final`

#### Expected behavior
 Commands will register extensions allowing launching of my Azure functions project.

#### Actual behavior

Receive the error:
`Value cannot be null.
Parameter name: stream`

#### Known workarounds

None.

#### Related information 

Provide any related information 

* Package version
`Azure Functions Core Tools (2.0.1-beta.23)
Function Runtime Version: 2.0.11587.0`

**Comment by fabiocav** [comment]
@ahmelsayed , this issue was addressed in the tooling, correct?

BTW, `Microsoft.Extensions.Configuration.AzureKeyVault` is not a WebJobs/Functions extension, so that wouldn't register anything.

**Comment by ahmelsayed** [comment]
yes it is. @wartmanrp please upgrade to `2.0.1-beta.24` for that command to work

**Comment by fabiocav** [comment]
Thanks for the confirmation!

@wartmanrp closing this as it is fixed on the latest release, but please let us know if you run into any problems.

**Comment by wartmanrp** [comment]
Thanks, I was able to circumvent the issue for now, I'll be sure to reach out if I have more trouble.
