### ISSUE TITLE
Cosmos DB Connection Mode configuration setting

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-webjobs-sdk-extensions#387]
Creating this issue so we can track the requirement of configuring the Cosmos DB client creation `ConnectionMode`. 

Right now it uses the default, but the user might need to change it for performance or connectivity reasons.

Possible values are in an enum: `ConnectionMode.Gateway` and  `ConnectionMode.Direct`.

**Comment by davetheunissen** [comment]
+1, we've had to do this to get round our internal corporate proxy.

**Comment by mathewc** [comment]
Can this issue be closed now? Looks like the change has been merged.
