### ISSUE TITLE
TimerTrigger cannot acquire a lock

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk-extensions#4]
I have the following function.
```c#
        public static void TimerJob([TimerTrigger("00:00:10")] TimerInfo timerInfo)
        {
            Console.WriteLine("Scheduled job fired at ="+timerInfo.Schedule.GetNextOccurrence(DateTime.Now));
        }
```

 Here is the repro
- Run one instance of WebJob. This can acquire the lock and TimerTrigger fires
- Run another instance of the same WebJob
- Kill the first one.
- The second instance cannot acquire the lock. I get the following on the console.
Found the following functions:
WebJob3.Functions.TimerJob
WebJob3.Functions.ProcessQueueMessage
Waiting for Singleton lock (WebJob3.Functions.TimerJob.Listener)
Unable to acquire Singleton lock (WebJob3.Functions.TimerJob.Listener).
Job host started

**Comment by mathewc** [comment]
This was a bug that has already been fixed. See [this commit](https://github.com/Azure/azure-webjobs-sdk/commit/79383d51157760b89a12bf17c32c6c586febec68). Please update using the myget feed to pull the SDK with the fix and give it a try again. If it cannot acquire the lock it should now correctly cause a failure (meaning the host will start again and retry in WebApps/WorkerRole). Also, you can adjust the lock acquisition timeout to get the behavior you desire.

**Comment by rustd** [comment]
if a function fails to acquire a lock, should it cause the host to fail? What if I have other functions which are being Triggered on Queue messages in the same host. In this case I would not want the host to restart.

**Comment by mathewc** [comment]
I misspoke a bit above - in the Singleton listener case (your case) if a listener lock cannot be acquired on startup by the trigger listener, the host will still start normally - in this case, it means another host has the lock (things are working as expected).

In your case, it's likely that the acquisition timeout (which defaults to 15 seconds) was about to expire before you killed the first host. When you killed the first host, the lease was left open, and it will naturally expire in 15 seconds. So the second instance was unable to acquire the lock in time. However, the first host (or some host) will eventually restart and acquire the lock and start the listener.

**Comment by rustd** [comment]
I grabbed the Nightly and the Timer is no longer SingleTon. if I run 2 instances of the host then the timer is triggered on both.

**Comment by mathewc** [comment]
Probably I didn't update the Extensions nightly - I only update the SDK (where the bug fix was made). I'll go update them all now.

**Comment by mathewc** [comment]
I've updated the Extensions package on myget.
