### ISSUE TITLE
Sign the Extension assemblies

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-extensions#41]
With the same key that other WebJobs SDK packages are signed with. Currently we're not signing.

**Comment by mathewc** [comment]
However, we're blocked by the fact that NCronTab is not signed, and we have a dependency on it. http://www.nuget.org/packages/ncrontab/

**Comment by davidebbo** [comment]
You're going to start a religious war here. Note that if we strong name it, we need to keep the version fixed. See what I went through a few years ago for WebActivator: https://github.com/davidebbo/WebActivator/wiki/Signing-WebActivator

**Comment by mathewc** [comment]
@davidebbo All the WebJobs SDK core assemblies are signed as per long standing policy, and people have no problems using those packages. The WebJobs SDK Extensions are part of that grand tradition. so it seems they should also be signed. Why is this a problem?

**Comment by mathewc** [comment]
@davidebbo All the WebJobs SDK core assemblies are signed as per long standing policy, and people have no problems using those packages. The WebJobs SDK Extensions are part of that grand tradition. so it seems they should also be signed. Why is this a problem?

**Comment by davidebbo** [comment]
It's ok to sign them. But when doing this, the important thing is to freeze the assembly version and never change it. That's the scheme Json.NET and some other top packages switched to in order to save users from too much pain.

**Comment by mathewc** [comment]
Update: The author of NCronTab has graciously uploaded a signed version of his package as NCronTab.Signed, so we're unblocked here.

**Comment by nimishrocksster** [comment]
We are also experiencing this issue and our service deployment is blocked on this.

**Comment by mathewc** [comment]
Since this issue was created, we've onboarded a lot of additional packages in the Extensions project (e.g. ApiHubs, NotificationHubs, etc.). We want our signing story to be consistent across all these packages I believe, so we should see if the requisite assemblies for these other packages are also signed. Otherwise we'll be in a world where some Extension packages are signed, and some are not, which is messy.

**Comment by joymon** [comment]
Any update on signing? I checked 2.1.0 nuget pack and still not signed. 
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions/2.1.0

**Comment by cdhawan** [comment]
Kindly strong named and Authenticode sign these assemblies.

**Comment by paulbatum** [comment]
All published NuGet assemblies relating to WebJobs 3.x / Functions 2.x are now strong name signed, including the extension assemblies. We will not be able to make any changes to signing for earlier versions of the extension assemblies as this would be a [breaking change](https://haacked.com/archive/2012/02/16/changing-a-strong-name-is-a-major-breaking-change.aspx/).

Closing this as resolved.
