### ISSUE TITLE
CosmosDBBindings ConnectionPolicy Settings

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-webjobs-sdk-extensions#415]
I'd like to add the Connection Policy Setting for the CosmosDB Bindings. 

In our app, frequently configure these policies. 

```
ConnectionPolicy: PreferredLocations
ConnectionPolicy: ConnectionMode
ConnectionPolicy: ConnectionProtocol
```

These parameter is included in the best practices of CosmosDB. I guess a lot of people might want to configure that. 
 
I suggest to make it  configureble the Connection Policy via `host.json`.

If no one try to do it, I'd happy to contribute it.

**Comment by k-miyake** [comment]
CosmosDB Connection Policy Setting is recommended in [Performance tips for Azure Cosmos DB and .NET](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips#networking), so I also want it.

**Comment by paulbatum** [comment]
@brettsam Did we recently add connection mode?

**Comment by brettsam** [comment]
Yes, `ConnectionMode` is now added (but not yet released). https://github.com/Azure/azure-webjobs-sdk-extensions/commit/b2c30326ab6b84c005d9f18a774dce5133132ea7, but the other values are not exposed.

cc: @ealsur

**Comment by ealsur** [comment]
There is an issue tracking PreferredLocations: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/363 

The difference is that ConnectionMode & Protocol can be set at host.json level, but PreferredLocations should be set at the Binding / Trigger level. This is because a Trigger or Binding might be pointing to a different ConnectionString / Account and each Account could have different regions.

The problem is that if a user configures a Binding with a PreferredLocation in Function A and another Binding (same ConnectionString) on Function B but without (or different PreferredLocation) we would need to have 2 Clients. This might imply changing the cache of Clients from one per ConnectionString to one per ConnectionString/PreferredLocations.

**Comment by TsuyoshiUshio** [comment]
Thank you, @ealsur 

IMO, we can compromise that. For example, we could have to have different configuration for Function A and Function B. 
However, generally speaking, people might want to configure Preferred Location for Function App, right?  The location is depend on the Region which CosmosDB and FunctionApp deployed. 
Then just add to host.json (or AppSettings) might be good option. 

What do you think @k-miyake ? 

Also, how about ConnectionProtocol? It might be good for `host.json`

**Comment by ealsur** [comment]
ConnectionProtocol makes sense to set it at `host.json` level but for PreferredLocations, if you are working with different Cosmos DB account, for example Function A points to Account A and Function B to Account B, Account A could be in a different region list as Account B and you might want to define a different PreferredRegions order for each.

**Comment by k-miyake** [comment]
I could understand the problem of multiple functions that @ealsur 's mention. Then, how about  set it with function.json?

**Comment by TsuyoshiUshio** [comment]
@ealsur @brettsam Can we contribute two things by the two pull requests? Or would you guys want to do it by product team?

1.  Enable Connection Protocol by host.json
2.  Enable Prefered Location using Attribute (Trigger/Bindings level)

**Comment by ealsur** [comment]
I can take a shot at 1, but 2, I'd wait until we define if the Client cache using the locations is the way to go.

**Comment by TsuyoshiUshio** [comment]
@ealsur Thanks! and understand. It helps a lot of uses!  If you finish these, please let us know via this issue. Also, if you have any help, please let us know.

**Comment by ealsur** [comment]
@TsuyoshiUshio Sent a PR for the Protocol request.

**Comment by TsuyoshiUshio** [comment]
@ealsur Thanks! Very quick! :)

**Comment by TsuyoshiUshio** [comment]
Awesome! @ealsur ! :)
