### ISSUE TITLE
SendGrid FlushAsync() does not clear the buffer after each call

### ISSUE THREAD

**Issue by watashiSHUN** [Azure/azure-webjobs-sdk-extensions#416]
https://github.com/Azure/azure-webjobs-sdk-extensions/blob/568861139ecf2996849908d99b277a732b886b44/src/WebJobs.Extensions.SendGrid/Bindings/SendGridMessageAsyncCollector.cs#L51-L57

**Comment by mathewc** [comment]
@fabiocav pointed out that the Twilio binding has the same issue
