### ISSUE TITLE
Custom-triggered functions are not discovered by the JobHost

### ISSUE THREAD

**Issue by nathandavidson** [Azure/azure-webjobs-sdk-extensions#42]
I created a new console app that copied [these](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/Sample.Extension/SampleTriggerAttribute.cs) [three](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/Sample.Extension/SampleTriggerAttributeBindingProvider.cs) [files](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/Sample.Extension/SampleJobHostConfigurationExtensions.cs) to start writing a custom trigger.

The Main method and triggered method are below:
```
namespace ConsoleApplication1
{
    using Microsoft.Azure.WebJobs;
    using System;

    public static class Program
    {
        public static void Main()
        {
            var config = new JobHostConfiguration();
            config.UseSample();

            using (var host = new JobHost(config))
            {
                host.RunAndBlock();
            }
        }
        
        public static void SampleTriggeredMethod(
            [SampleTrigger(@"sample\path")]SampleTriggerValue value)
        {
            Console.WriteLine("SampleTrigger execution provided value: " + value);
        }
    }
}
```

I'd expect the JobHost to discover this method and start triggering it based on the internal timer. But the output I get when running this app:

> No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
> Job host started

However, adding something like a TimeoutAttribute to SampleTriggeredMethod, or adding another method that uses a built-in trigger type, allows the JobHost to discover this method.

Here's a [repro solution](https://github.com/Azure/azure-webjobs-sdk-extensions/files/147318/ConsoleApplication1.zip) with connection strings removed from App.config.

**Comment by mathewc** [comment]
If you move your sample extension into its own assembly and reference it, it will work (I verified). While we could investigate why extension assembly loading doesn't handle extensions defined within the exe project, that really isn't how people will write extensions, so I don't think it's a scenario. If you disagree you can reopen this issue and we can leave it on the backlog. Thanks for logging the bug and repro.
