### ISSUE TITLE
Allow TimerTrigger run on all instances in case of scale out

### ISSUE THREAD

**Issue by sergei66666** [Azure/azure-webjobs-sdk-extensions#420]
Hello!
It is feature, not bug.

In some cases same method should run periodically on all instances after scale out.
But at now timer is singleton.

Is it possible to change this behavior?
Maybe add host id to a timer name inside TimerTriggerBinding if necessary.
But Singleton attribute on TimerListener is confusing me.

**Comment by brettsam** [comment]
What is the scenario that you need to run the function on all instances?

**Comment by sergei66666** [comment]
I need to perform complex data processing every 10 seconds. This data comes from 100 suppliers, for example. One instance can only handle half, ie data from 50 suppliers. So need scale out.

I could use ServiceBus or a queue, but I know the interval with which I have to perform processing and the timer seems to me much more suitable (aka KISS).
Yes, I need to synchronize instances at the startup, but then use just a timer.

**Comment by sergei66666** [comment]
#428

**Comment by mathewc** [comment]
So you're saying that if you could have the timer running on each instance, you'd somehow have the timer partition the work pulled on each instance, so each invocation only handles a manageable subset?

Seems like a cleaner more robust design would be for you to have a single Timer or other process pulling the batches of work and dropping a queue message for that work into a work queue that all of your scaled out instances are processing. That way you get durability/retries for each batch or work automatically.

**Comment by sergei66666** [comment]
@mathewc I was considering the queue option. But in my case, the queue is an unnecessary complication. Queue benefits are not required in this case.

I believe that the approach described at #428 can help. Thank you.
