### ISSUE TITLE
Twilio Binding does not seem to be working

### ISSUE THREAD

**Issue by sameertotey** [Azure/azure-webjobs-sdk-extensions#421]
When I created a Azure Function with Twilio binding to send multiple output messages, I get the following error:

The following 1 functions are in error:
[6/4/18 6:00:41 PM] Run: Microsoft.Azure.WebJobs.Host: Error indexing method 'FunctionSendDeliveryTwilioSMS.Run'. Microsoft.Azure.WebJobs.Host: Can't convert from type 'Twilio.Rest.Api.V2010.Account.CreateMessageOptions.

Here FunctionSendDeliveryTwilioSMS is the name of my Azure function.

#### Repro steps
```
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.ServiceBus.Messaging;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;

namespace PinnacleWareHouser.FunctionAppHost
{
    public static class FunctionSendDeliveryTwilioSMS
    {

            [FunctionName("FunctionSendDeliveryTwilioSMS")]
            public static void Run([ServiceBusTrigger(
                    "deliverynotifications",
                    "sendtwiliosms",
                    AccessRights.Manage,
                    Connection = "ServiceBusConnection")]string salesOrderDeliveryObject,
                [TwilioSms(AccountSidSetting = "TwilioAccountSid", AuthTokenSetting = "TwilioAuthToken")] IAsyncCollector<CreateMessageOptions> messages,
                TraceWriter log)
            {

                log.Info($"C# ServiceBus topic trigger function - FunctionSendDeliveryTwilioSMS - processed message: {salesOrderDeliveryObject}");

                var sendToCustomer = true;
                var sendToSalesRep = true;

                var toNumber = string.Empty;
                var messageBody = "Sample test SMS message";
                var fromNumber = "+1xxxxxxxxxx";


                if (sendToCustomer)
                {
                    toNumber = "+1xxxxxxxxx";
                    var message = new CreateMessageOptions(new PhoneNumber(toNumber))
                    {
                        Body = messageBody,
                        From = fromNumber
                    };
                    messages.AddAsync(message);
                }

                if (sendToSalesRep)
                {
                    toNumber = "+1xxxxxxxxxx";

                    var message = new CreateMessageOptions(new PhoneNumber(toNumber))
                    {
                        Body = messageBody,
                        From = fromNumber
                    };
                    messages.AddAsync(message);
                }
                return;
            }
    }
}

```

#### Expected behavior

Expect the Azure function to run

#### Actual behavior

get the error:
The following 1 functions are in error:
[6/4/18 6:15:06 PM] Run: Microsoft.Azure.WebJobs.Host: Error indexing method 'FunctionSendDeliveryTwilioSMS.Run'. Microsoft.Azure.WebJobs.Host: Can't convert from type 'Twilio.Rest.Api.V2010.Account.CreateMessageOptions.

#### Known workarounds

Directly send the Twilio SMS without using the Azure function binding.

This function was working fine prior to upgrading the Twilio Nuget package

#### Related information 

Provide any related information 

* Package version

 Twilio: 5.13.2
Microsoft.Azure.Webjobs.Extensions.Twilio: 1.2.0

* Links to source

**Comment by fabiocav** [comment]
The Twilio SDK was completely changed in a recent release. What was supported in 1.x was 4.7.2, which doesn't have the type above. 

In 1.0, the binding supports the `SMSMessage` type, and you can find more information here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-twilio
