### ISSUE TITLE
CosmosDB: "Detected corrupted documents without _id identifier error"

### ISSUE THREAD

**Issue by AndreaVitale** [Azure/azure-webjobs-sdk-extensions#422]
Hi, as per [the docs](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-functions/functions-bindings-cosmosdb-v2.md#output---javascript-examples) I'm trying to send data to CosmosDB in an Azure Functions like this:

*function.json*
```
{
      "name": "user",
      "type": "cosmosDB",
      "databaseName": "andrea",
      "collectionName": "users",
      "createIfNotExists": true,
      "connectionStringSetting": "CosmosDbConnectionString",     
      "direction": "out"
}
```

and using this bindings as follows:
```
        context.bindings.user = JSON.stringify({
            id: id.toHexString(), // A string like this: 5b1eae798de7c007ddf9f095
            name: context.req.body.name,
            surname: context.req.body.surname,
            email: context.req.body.email
        });
```

but when I try to explore data via the azure portal, I got this notification error:
```
Error while fetching page of documents:
 {"code":500,"body":"Detected corrupted documents without _id identifier, verify that you are only storing documents through Mongo protocol and not SQL API or DocumentDB SDK."}
```

I'm doing the same thing you do into the docs.
What am I missing?

I already opened an issue inside the docs project [#10034](https://github.com/MicrosoftDocs/azure-docs/issues/10034) where there are other tests I made like connecting directly with a mongo client library. A docs team member said that I have to open an issue there.

Thanks.

**Comment by paulbatum** [comment]
When you created the db it was put into Mongo mode. Azure Functions does not support the Mongo API at the moment. If you create the collection using the "SQL / document" API you should find this works.
