### ISSUE TITLE
Missing CosmosDB properties/V1->V2 gap

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-extensions#423]
The CosmosDB updates made in the PR #337 have not been ported over to `dev`. We need to move those changes over to close that gap.

**Comment by ealsur** [comment]
@fabiocav @brettsam By the way, here is another PR that would be good to get in that adds some recent things to V2 😄 https://github.com/Azure/azure-webjobs-sdk-extensions/pull/409
