### ISSUE TITLE
TimerListener

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-webjobs-sdk-extensions#454]
Please provide a succinct description of the issue.
The output from the timer listener is difficult to read when the azure functions has multiple timer triggers.

#### Repro steps

Provide the steps required to reproduce the problem

1. create a solution with multiple timer triggered functions
2. execute and view the output of the timer listener

#### Expected behavior
output should be easy to read an detail which timer is schedule to execute when, instead of just listing the times of the timer.

#### Actual behavior
the output displays a list of times with no indication to which function they relate.

#### Known workarounds
none

**Comment by brettsam** [comment]
This went in with #318.
