### ISSUE TITLE
[CosmosDBTrigger] Race in start/stop

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-extensions#455]
PR #433 introduced some graceful start/stop functionality. But running the tests in the functions-host branch show that we've got a race now between this start/stop where it's possible to leave a ChangeFeedProcessor running after the host has stopped.

It looks like `RegisterObserverFactoryAsync()` can take a little while to run. If we call `Stop()` while it's still running, we'll never call `UnregisterObserversAsync()`, and that processor will steal away change notifications from tests later in the run.

Is calling `Unregister()` before `Register()` is complete okay? It looks like that may be what we used to do. This may just need another check for "Registering" so it knows if its safe to call `Unregister()`. Either that or we need a lock/semaphoreslim that waits for any outstanding register calls to complete before exiting the Stop (which may take a little while).

**Comment by ealsur** [comment]
We could add a lock mechanism, I wonder though, what should be the Stop behavior if the lock is still taken (ie it's Registering)? Should it wait?

**Comment by brettsam** [comment]
It seems like it could be a potentially long lock period, which isn't great. But looking at the previous code it looks like we were okay to call StartAsync() and then StopAsync() pretty quickly and it didn't throw an exception. 

Do you know the behavior of Unregister() being called while there's a currently-running Register()? We weren't having any problems with that pattern before. Maybe we don't need to check for `listenerStarted`?

https://github.com/Azure/azure-webjobs-sdk-extensions/blob/4e792e72faa9c94783cd828c4a1e8fe0d9e3b193/src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerListener.cs#L55-L72

**Comment by ealsur** [comment]
Maybe we can change it to:

    try
    {
        if (this.host != null)
        {
            await this.host.UnregisterObserversAsync();
            this.listenerStarted = false;
        }
    }
    catch (Exception ex)
    {
        this.trace.Warning($"Stopping the observer failed, potentially it was never started. Exception: {ex.Message}.");
    }

**Comment by brettsam** [comment]
That call to set `listenerStarted` worries me. What if you call 

`StartAsync()` -> takes 5 seconds
`StopAsync()` -> takes 1 second

You'd end up with `listenerStarted = true`, I think. Yet I believe it would be stopped. Is there any way to get the true state of the host directly without tracking it ourselves?

**Comment by ealsur** [comment]
Does this mean that:
a. The listener can be accessed from multiple threads
b. The thread that calls `StartAsync` does not await it

Or how could StopAsync be called before Start finishes?

**Comment by ealsur** [comment]
@brettsam waiting on this to understand what's the best course of action

**Comment by brettsam** [comment]
I just ran through this. What's happening is that we're calling `listener.StartAsync()`, and then calling `listener.Cancel()` before that is done. In this listener, `Cancel()` calls `StopAsync()`. This is happening b/c the host is shutting down before it's fully running, which is a valid scenario. In this case, it leaves the ChangeFeedProcessor running in the background. 

It feels like we really need a `CancellationToken` on that call to `RegisterObserverFactoryAsync()` so we can short-circuit it if it's in-flight. There aren't any newer versions of this package that have this, are there?

Short of that -- if it's safe to call `Register()` on one thread and then immediately call `Unregister()`, we could have some `_isRegistering` bool that we check as well as the `_listenerStarted`. Or maybe we just need one of those, but need to move it before the call to `Register()`, so we know to unregister the in-flight operation?

**Comment by brettsam** [comment]
Yes, preventing multiple calls to `Start()` is good. Also, this pattern still needs to work (which it does):
1. `Start()` -> throws
2. Host retries and calls `Start()` again.

But calling `Start()` -> success, and then calling `Start()` again should be prevented.

My main concern with calling `Unregister()` while `Register()` is still running is that we're not confident of the internal state of the `ChangeFeedEventHost` at the end of these calls. I don't know everything that's happening in that call to `Register()` -- is it possible to have some things end up in a weird state if you call `Register()` and then immediately `Unregister()`? For example:

If Register does a bunch of stuff like:
1. Connect to external service A
2. Set up some classes internally.
3. Start listening.
4. Flip some internal variables.

And we call `Unregister` after it has completed step 1 -- will `Register` continue running and leave things in a weird state? We've been doing this for a while and haven't seen any issues (that I know of), but wanted to see if we know whether the `ChangeFeedProcessor` guarantees anything with these calls in this order.

I think our options are:
1. Call `Unregister()` without checking anything -- which is what we've been doing without any obvious issues for a while now.
2. Use a lock to make sure to wait for the call to `Register()` to complete before calling `Unregister()` -- would obviously slow down calls to `Cancel()`, but may not even be needed.

**Comment by brettsam** [comment]
Hey @ealsur -- any preference to either of our options? Do you think we're safe to make this do number 1 above?

**Comment by ealsur** [comment]
@brettsam I sent a second PR for V2 https://github.com/Azure/azure-webjobs-sdk-extensions/pull/468

**Comment by brettsam** [comment]
This went in with #467/#468
