### ISSUE TITLE
Microsoft.Tpl.Dataflow is decommissioned. WebJobs.Extensions still depend on it

### ISSUE THREAD

**Issue by Takaloy** [Azure/azure-webjobs-sdk-extensions#465]
Hi,

more of a question than a bug report. Microsoft.Tpl.Dataflow has been unlisted for a while now and Azure.WebJobs.Extensions still uses it. I am wondering if there's any plans to move to System.Threading.Task.Dataflow packages?

Cheers

**Comment by paulbatum** [comment]
@Takaloy  We've already switched this over in webjobs v3 - see [here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj#L29).

We have no plans to update earlier versions of webjobs. Hope that makes sense, closing as answered.
