### ISSUE TITLE
3.0.0-beta8 QueueTrigger attribute binding Json Exception

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-webjobs-sdk-extensions#480]
using the binding CloudQueueMessage to a queue throws a Json exception when a message string is received; to reproduce 

Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: s. Path '', line 0, position 0.'

see code.

```
        [FunctionName("SendEmailMessageTimer")]
        public static async Task SendEmailMessageTimer(
            [TimerTrigger("0 */1 * * * *")]
            TimerInfo timerInfo,
            [Queue("send-email-request",Connection ="ApplicationStorageAccount")]
            IAsyncCollector<CloudQueueMessage> messages,
            ILogger logger)
        {
            await messages.AddAsync(new CloudQueueMessage("some text"));
            logger.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }
        
        [FunctionName("SendEmailMessage")]
        public static async Task SendEmailMessageRun(
            [QueueTrigger("send-email-request", Connection = "ApplicationStorageAccount")]
            CloudQueueMessage queueItem,
            ILogger logger)
        {
            logger.LogInformation($"C# Queue trigger function processed: {queueItem.AsString}");
            await Task.CompletedTask;
        }
```

**Comment by paulbatum** [comment]
@grahamehorner can you include the stacktrace of the exception please

**Comment by grahamehorner** [comment]
@paulbatum  I've just tried to reproduce the exception without success? this may be due to some changes in packages; happy for this to be close; I'll re-open if this occurs again.

**Comment by paulbatum** [comment]
@grahamehorner good to hear. There is one possible explanation which I think is likely is that this exception occurs, but is caught and swallowed. If you had "break on all exceptions" enabled, then you would have seen it.

**Comment by grahamehorner** [comment]
@paulbatum the issue has re-surfaced using rc here is a stacktrace

   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.Azure.WebJobs.Host.Protocols.JsonSerialization.ParseJObject(String json) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Protocols\JsonSerialization.cs:line 102
   at Microsoft.Azure.WebJobs.Host.Queues.QueueCausalityManager.GetOwner(CloudQueueMessage msg) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\QueueCausalityManager.cs:line 55

**Comment by paulbatum** [comment]
Again I think it must be due to your debugging settings. To illustrate, take a look at the code for that GetOwner method:
```
            try
            {
                json = JsonSerialization.ParseJObject(text);
            }
            catch (Exception)
            {
                return null;
            }
```
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/QueueCausalityManager.cs#L53-L60

This exception should be caught and swallowed. If you have first chance exceptions enabled then your debugger will break on it. But you should not be seeing it impact the actual operation of your function, nor should this error actually make it into your error logs (say in App Insights) when you are running in Azure.

**Comment by paulbatum** [comment]
My statements above stand (this exception should be caught and swallowed and not be impacting the execution of your function), but I will add that we have made a change that will be in next release of the storage extension that should reduce these first chance exceptions:
https://github.com/Azure/azure-webjobs-sdk/pull/1930

**Comment by grahamehorner** [comment]
Not longer occurs with updated extensions
