### ISSUE TITLE
Guidance on long running listener on Consumption plan

### ISSUE THREAD

**Issue by keesschollaart81** [Azure/azure-webjobs-sdk-extensions#484]
I'm building [an v2 extension to connect Azure Functions with an MQTT Broker](https://github.com/keesschollaart81/CaseOnline.Azure.WebJobs.Extensions.Mqtt). The extension creates an open connection to the MQTT broker and enables developers to trigger Functions and/or to publish messages. The tricky part is the open connection.

When I run this in consumption plan, I lose my connection because the thread/proces is aborted after 10 minutes of inactivity (right?). My questions are:
- Will this (a long running listener) never be a supported scenario on consumption plan?
- If not, is it possible to warn the user somehow (maybe detect the hosting type and log a warning during startup?)
- The documentation on how to deal with consumption-plan is either hard to find or non-existing? ([this](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/Binding-Extensions-Overview) is the only thing I could find). 
- As an extension developer I don't find this a very big issue (just switch plans). The point is, as a user you have to be aware of this behaviour (in the context of custom extensions) so someone have to tell you. I can image that other extension developers also run in this issue?

**Comment by swettstein** [comment]
bump. i'm running into the same issue with a custom FTP Trigger. for now, i'm using an extra TimerTrigger that fires on a schedule to keep the function warm.

**Comment by fabiocav** [comment]
This is not a scenario that is currently planned for consumption. Persistent connections from triggers (or custom triggers in general) are not supported in consumption.

You can detect the different hosting models based on environment setting (e.g. this is how the runtime performs those checks here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Environment/EnvironmentExtensions.cs#L131)

**Comment by fabiocav** [comment]
Closing this for now as this won't be worked on in the near future.
