### ISSUE TITLE
Trigger Binding; leases collection feature request

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-webjobs-sdk-extensions#487]
Using a boilerplate Functions v2 Function App in .Net with:
* VS2017.15.8.4 
* Extension v15.9.02009 
* Core Tools 2.5.2
* nupkg v3.0.1-beta2

#### Repro steps
Provide the steps required to reproduce the problem

1. Add a CosmosDB Trigger binding to an Azure Function pointing at a bare CosmosDB with one user-created collection (eg: `ratings`) in it.
```csharp
        [FunctionName("GetRatings")]
        public static void Run([CosmosDBTrigger(
            databaseName: "brandonhcosmos",
            collectionName: "ratings",
            ConnectionStringSetting = "DBconnections")]IReadOnlyList<Document> input, ILogger log)
```
2. Run the Azure Function

#### Expected behavior
A trigger should be created, listening to the specified collection on my Cosmos DB.

#### Actual behavior

The trigger complains it can't find a leases collection and advises the user to set the `CreateLeaseCollectionIfNotExists` property to `true`

#### Request
**This should be 'true' by default to minimize the amount of work required to get started**

**Comment by ealsur** [comment]
@brandonh-msft The creation of the collection has a cost impact in the user/customer (unless they are running in the Emulator). Defaulting to increase the user cost is not something I'm keen to.

@brettsam What do you think?

**Comment by brettsam** [comment]
The problem is dollars, not effort. A collection is a billable entity in Azure, and we don't want to auto-create those. That's why we've made all of these "auto-create" settings false by default in Cosmos.

We had the same discussion around output bindings and we require you to set "AutoCreate" to true there as well.
