### ISSUE TITLE
Feature Request: TimerInfo can give "last run datetime"

### ISSUE THREAD

**Issue by mjgpy3** [Azure/azure-webjobs-sdk-extensions#506]
Hello all,

Thank you for all your hard work on this great portion of Azure!

Is there a way to retrieve the last `DateTime` or `DateTimeOffset` at which a timer scheduled azure function has run? Perhaps on the `TimerInfo` object or some other way? My use-case is that I'm trying to write a function that sweeps over data that has changed since the function last ran without hardcoding the schedule.

Thanks again.

**Comment by JohnReeson** [comment]
See [TimerInfo.ScheduleStatus.Last](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/a3a5a49a64f3592c1eb7c1296086dc83c2011e96/src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleStatus.cs#L16).

**Comment by mjgpy3** [comment]
Thanks @JohnReeson!
