### ISSUE TITLE
Function 2.0: Table storage binding is not working if there are any reference to class library that references Windows.Azure.Storage 9.3.2

### ISSUE THREAD

**Issue by Anufriev** [Azure/azure-webjobs-sdk-extensions#515]
#### Repro steps

1. Create a solution and create a new simple function app 2.0  project (FunctionApp) with a timer trigger function
2. Add Microsoft.Azure.WebJobs.Extensions.Storage 3.0.0 nuget package
3. Add '[Table("testTable")] CloudTable table' argument to the function
4. Run function - ok
5. Add a new standard 2.0 library (ClassLibrary) to the solution
6. Add Windows.Azure.Storage 9.3.2 nuget to the class library project. This version is the same as version that is used by Microsoft.Azure.WebJobs.Extensions.Storage.
7. Add reference to the class library project to the function app project
8. Run the app

#### Expected behavior

No exceptions

#### Actual behavior

System.InvalidOperationException: 'Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.'

#### Known workarounds

Do not use any library that references Microsoft.Azure.WebJobs.Extensions.Storage nuget.

#### Related information 

* [repository](https://github.com/Anufriev/functionAppTableStorageBindingBug)
* ![image](https://user-images.githubusercontent.com/1809671/46569653-9940bc00-c960-11e8-86b3-ce288742d5b6.png)

**Comment by paulbatum** [comment]
Actually, Microsoft.Azure.WebJobs.Extensions.Storage depends on storage 9.3.1. So whats happening here is you're using a newer version than what the extension depends on. And you're hitting a bug that is tracked here:

https://github.com/Azure/azure-webjobs-sdk/issues/1942

**Comment by twentytwokhz** [comment]
Still reproducing today. This is frustrating :(

**Comment by paulbatum** [comment]
@twentytwokhz I assume the issue you're running into is https://github.com/Azure/azure-webjobs-sdk/issues/1942 - I'll follow up regarding its status

**Comment by AlphaCreative** [comment]
We are having this same issue with Microsoft.Azure.WebJobs.Extensions.Storage 3.0.5 and WindowsAzure.Storage 9.3.3.

**Comment by thebajanguy** [comment]
Got error today August 9th 2019 and I downgraded to Microsoft.Azure.WebJobs.Extensions.Storage 3.0.3 and used WindowsAzure.Storage 9.3.3 and it worked fine.

**Comment by gitakhil** [comment]
Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTrigger1'. Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'Submission#0

I'm working Azure Table and Azure Function binding.  and getting the above error. 

I am doing this--> https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#input---c-script-example---one-entity
