### ISSUE TITLE
Allow users to encrypt app settings values in azure portal

### ISSUE THREAD

**Issue by yosuftan** [Azure/azure-webjobs-sdk-extensions#517]
For security purposes, I would not like to expose secrets in plain text in the azure portal's app settings. For example, every time triggered function has a AzureWebJobsStorage key and an associated connection string. I would like that connection string to be encrypted. 

I know that for local.settings.json, there is a value to specify isEncrypted: true. Could there be a similar feature provided for azure portal?

**Comment by mhoeger** [comment]
This issue was moved to Azure/azure-functions-ux#3278
