### ISSUE TITLE
[CosmosDB] Better error message when using a partitioned Lease database

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-webjobs-sdk-extensions#518]
[Per this UserVoice](https://feedback.azure.com/admin/v3/suggestions/35542243/)

Partitioned lease databases aren’t supported in the Functions CosmosDB change feed binding. The error message for this doesn’t tell the user this so time is wasted trying to fix the configuration of the database. The binding should check if the Lease DB is paritioned and if so it should fail right there and throw a useful error.

**Comment by ealsur** [comment]
@jeffhollan We are adding support for partitioned lease collections in the next update 😄

**Comment by Mike-Ubezzi-MSFT** [comment]
@ealsur When will this be rolled out? Thanks for your support in the SO forums...

**Comment by ealsur** [comment]
@Mike-Ubezzi-MSFT even if the code is merged this depends on other Azure components deployment timeline, so we are basically waiting on that. It should be around new year from what I've heard.
