### ISSUE TITLE
Error to run a function after installing SendGrid nuget package

### ISSUE THREAD

**Issue by carloscamposcoelho** [Azure/azure-webjobs-sdk-extensions#531]
I'm working on a C# Azure function project (v2) and everything works fine until I install the package Microsoft.Azure.WebJobs.Extensions.SendGrid thru nuget package manager.

After that, when I run the project I get an error:

![2018-11-07 00_21_40-c__users_rabbit_appdata_local_azurefunctionstools_releases_2 5 2_cli_func exe](https://user-images.githubusercontent.com/4945030/48107357-7ab33680-e226-11e8-9bfd-fd88581d9a06.png)

Detailed stack: [log.txt](https://github.com/Azure/azure-webjobs-sdk-extensions/files/2555859/log.txt)

#### Repro steps

Provide the steps required to reproduce the problem

1. Right click on the csproject file => Manage NuGet Packages

2. Search for "Microsoft.Azure.WebJobs.Extensions.SendGrid" and install it

3. Run the project after installation is finished

![2018-11-07 00_44_41-sendit - microsoft visual studio](https://user-images.githubusercontent.com/4945030/48107358-7ab33680-e226-11e8-8d6c-89fd6d022ef7.png)

**Comment by carloscamposcoelho** [comment]
I've downgraded the SendGrid extention from version 3.0.0 to 3.0.0-rc1 and it's running locally again.

**Comment by v-anvari** [comment]
Closing this issue, Please feel free to reach out to us in case of any queries regarding this issue
