### ISSUE TITLE
Database context is reused on several timers when RunOnStartUp = true

### ISSUE THREAD

**Issue by pekspro** [Azure/azure-webjobs-sdk-extensions#538]
I have created a web job with the latest SDK (3.0.3) with two timers that both triggers on start-up. Both these timers read from a database. On the second read the application crashes with the error message:

    System.InvalidOperationException: An attempt was made to use the context while it is being configured. A DbContext instance cannot be used inside OnConfiguring since it is still being configured at this point. This can happen if a second operation is started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.

When timers are triggered by time this error doesn’t occur.

My code looks like this:

    class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = new HostBuilder()
                .ConfigureAppConfiguration(b =>
                {
                })
                .ConfigureWebJobs(b =>
                {
                    b.AddAzureStorageCoreServices()
                    .AddAzureStorage()
                    .AddTimers();
                })
                .ConfigureLogging((context, b) =>
                {
                    b.AddConsole();
                })
                .ConfigureServices((build, services) =>
                {
                    services.AddDbContext<MyDatabaseContext>(options =>
                        options.UseSqlServer(build.Configuration.GetConnectionString("MyDatabaseContext")));
                })
                .UseConsoleLifetime();

            var host = builder.Build();
            using (host)
            {
                await host.RunAsync();
            }
        }
    }

    public class MultiTimerTestFunctions
    {
        public Guid ID { get; set; }

        public MultiTimerTestFunctions(MyDatabaseContext MyDatabaseContext)
        {
            MyDatabaseContext = MyDatabaseContext;
            ID = Guid.NewGuid();
        }

        public MyDatabaseContext MyDatabaseContext { get; }

        public async Task Read1TestAsync([TimerTrigger("0,30 * * * * *", RunOnStartup = true)] TimerInfo timer, ILogger logger)
        {
            try
            {
                logger.LogInformation("Read1a - " + ID.ToString());
                var read1a = MyDatabaseContext.JobLogs.ToListAsync();

                await Task.Delay(5000);

                logger.LogInformation("Read1b - " + ID.ToString());
                var read1b = MyDatabaseContext.JobLogs.ToListAsync();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error read1: " + ex.Message);
            }
        }

        public async Task Read2TestAsync([TimerTrigger("0,30 * * * * *", RunOnStartup = true)] TimerInfo timer, ILogger logger)
        {
            try
            {
                logger.LogInformation("Read2a - " + ID.ToString());
                var read2a = MyDatabaseContext.JobLogs.ToListAsync();

                await Task.Delay(5000);

                logger.LogInformation("Read2b - " + ID.ToString());
                var read2b = MyDatabaseContext.JobLogs.ToListAsync();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error read2: " + ex.Message);
            }
        }
    }

Is this by design?

**Comment by dallancarr** [comment]
If you enable just one trigger does the issue still appear?

**Comment by dallancarr** [comment]
https://stackoverflow.com/questions/34189334/azure-webjobs-with-entity-framework-job-parallelism

But for a quick fix inject the service provider and resolve an instance from the method.

**Comment by pekspro** [comment]
If I have just one trigger everything is fine. It also works if I remove **RunOnStartup = true**. And I think that is strange. I would expect the same behaviour both when the code is triggered by start-up event or a timer.

**Comment by dallancarr** [comment]
Maybe its pure luck 👍 Anyway just scope the DbContext to `ServiceLifetime.Transient` it should at least get you going.
