### ISSUE TITLE
httpTrigger binding to query parameters

### ISSUE THREAD

**Issue by FlippieCoetser** [Azure/azure-webjobs-sdk-extensions#546]
Azure Function contains bindings: httpTrigger and blob.

a filename is passed in via an HTTP GET request: 
`http://<yourapp>.azurewebsites.net/api/<funcname>?filename=filename.txt`

The blob is supposed to be configured to use this query parameter (filename), but I can't find a way to achieve this in the `junction.json` file

 ```
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get"
      ]
    },{
      "name": "blob",
      "type": "blob",
      "direction": "in",
      "path": "container/filname",
      "connection": "AzureWebJobsStorage"
    }
```

Looking at **Customize the HTTP endpoint**
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#customize-the-http-endpoint

I can see how to configure a route but do not see any syntax for ready the query parameters.
Is this support functionality? If not, please consider such use case.

**Comment by JohnReeson** [comment]
Try `"path": "container/{query.filename}"`

**Comment by FlippieCoetser** [comment]
@JohnReeson thanks! That works!
