### ISSUE TITLE
Any reason as to why the CosmosDBAttribute is sealed?

### ISSUE THREAD

**Issue by JoasE** [Azure/azure-webjobs-sdk-extensions#549]
Using the `CosmosDBAttribute` can be a little bit of a hassle having to specify the same configuration over and over again.

Just look in the [Microsoft docs on function bindings with CosmosDB](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#output).

In an application, properties like: `databaseName` and `ConnectionStringSetting` will often be an application wide configuration.

An easy solution to the configuration duplication would be to create your own preconfigured attribute like such:

```
public class DatabaseAttribute : CosmosDBAttribute
{
    public DatabaseAttribute(string collectionName) : base("databaseName", collectionName)
    {
        this.CreateIfNotExists = true;
    }
}
```

Or maybe even go as far as creating one attribute per collection.

Same goes for the `HttpTrigger`, where I would want to create prefigured attributes like `HttpPost`:

```
public class HttpPost : HttpTriggerAttribute
{
    public HttpPost() : base(AuthorizationLevel.Anonymous, "post")
    {
    }
}
```

Why are these attributes sealed?
Is it possible for these classed to not be sealed to prevent duplicate configuration and make working with them a bit easier?

**Comment by Postlagerkarte** [comment]
@JoasE : Having the same question. I wonder what approach you took to solve it?

**Comment by JoasE** [comment]
@Postlagerkarte This was a while ago, but pretty sure I just specified the string values in every function. You could try defining a static class with public const string fields in order to prevent you from having to go everywhere to change the name of the database etc.
