### ISSUE TITLE
Improve timer trigger logging

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-extensions#550]
If the timer trigger fails to fire for whatever reason, more logs would help us diagnose the issues. Most of these can be verbose so that they're only logged to our system logs and won't clog up users with normal verbosity:
- What CRON expression did we actually get? Right now we log the next schedule, but not what the CRON was before we parsed it.
- Log when we start a timer, and exactly what length that timer was for. If a timer fails to fire, we know to look at thread starvation/ CPU/ etc. But at least we know we started the timer as we expected.
- Include the actual function name when writing logs (i.e. the name from metadata rather than `Function 'FunctionApp3.Function1.Run' is past due on startup. Executing now.`). Ideally, include these logs in the FunctionName column in system logs.
- If a timer is running because it's past due, put it into the `Reason` for the function execution. Right now you have to search up for a message (without a FunctionName or FunctionInvocationId) to figure out why a timer fired at an odd time. Same thing for `RunOnStartup`.
- Include the timezone offset (or maybe include UTC in parens) in the `The next 5 occurrences...` message. We log the time zone higher up, but it'd be good to include this all in one message.

**Comment by mhoeger** [comment]
Really like the list! Thoughts on the following?
 - Warning log if you have `RunOnStartup` to true (like the `async void` warning)
 - Don't know if this is possible, but any information on when the delayed execution was supposed to run if it is late
