### ISSUE TITLE
Cosmos DB binding support for DatabaseName and CollectionName from configuration

### ISSUE THREAD

**Issue by Scythen** [Azure/azure-webjobs-sdk-extensions#558]
Support for retrieving database and collection names from configuration using the CosmosDBAttribute binding.

This would work in the same was as the connection string attribute. Rather than providing the actual value, provide the name of the setting containing the value.

Generally, having fixed database and collection names is expected.
However, because Cosmos DB allows scaling at the DB level as well as the collection level having the ability to run a function app against a single Cosmos DB containing all collections as well as separate databases and collections can provide significant cost benefits, particularly in development and test environments.

In development, I would like to have a single database containing all collections provisioned to share RUs.
In production, I would like to have different databases with different access rights and reserved RUs (at db and collection level).

**Comment by liamwhan** [comment]
@Scythen unless Im misunderstanding your requirement, this is already possible

`CosmosDBAttribute` retrieves collection and db names using template variable substitution. A modified example from one of our Azure Functions looks like:
```csharp
 public static async Task<IActionResult> Run(
     [CosmosDB("%CosmosDBName%", "%CosmosDBCollection%", ConnectionStringSetting = "CosmosDBConnection")] IDocumentClient documentClient) { }
```

Which retrieves the values from either our Azure configured application settings in production or our `local.settings.json` in development:

```json
{
    "CosmosDBName": "MyDatabase",
    "CosmosDBCollection": "MyCollection",
    "CosmosDBConnection": "{{CosmosDB ConnectionString}}"
}
```

**Comment by Scythen** [comment]
@liamwhan yes, that is exactly what I want!
Where is that documented? I must have missed it.
