### ISSUE TITLE
Cosmos DB Binding collectionName/databaseName from configuration fails (JavaScript)

### ISSUE THREAD

**Issue by antempus** [Azure/azure-webjobs-sdk-extensions#564]
Setting the `databaseName` and `collectionName` to environment variables in the `function.json` of an azure function with a `cosmosDB` output binding causes the azure function to fail to execute as the reference names are used as literals rather than the referenced value.

#### Repro steps

1. Create Azure Function 2.x with a Cosmos DB output binding
2. In the output binding parameter of `databaseName` specify a reference to a value in `local.settings.json`
3. In the output bindign parameter of `collectionName` specify a reference to a value in `local.settings.json`
4. Run function/deploy function

#### Expected behavior

Azure function is able to pull in the reference value from local settings as it does for triggers and the `connectionStringSetting` for the CosmosDB binding.
#### Actual behavior

Azure Function complains:
```
System.Private.CoreLib: Exception while executing function: Functions.FunctionName
Microsoft.Azure.WebJobs.Extensions.CosmosDB: The collection 'COSMOS_COLLECTION' (in database 'COSMOS_DATABASE') does not exist. To automatically create the collection, set 'CreateIfNotExists' to 'true'. Microsoft.Azure.DocumentDB.Core: Message: {"Errors":["Owner resource does not exist"]}
```

Cosmos Binding/Azure Function cannot pull the reference from environment variables like other fields are able to.

#### Known workarounds

Statically define collection and database in `function.json` for each function. 

#### Related information 

Using the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#output---configuration), there is no specification about why this doesn't work or why it should be used as a static string and not configurable via environment variable. 

Seems to be supported using `C#` as discussed in issue #558 

Version Information:
`NodeJS -v (v.8.11.2)`
`az -v (2.0.41)`'

Config example:
```
function.json {
    {
      "type": "cosmosDB",
      "name": "document",
      "direction": "out",
      "databaseName": "COSMOS_DATABASE",
      "collectionName": "COSMOS_COLLECTION",
      "connectionStringSetting": "COSMOS_CONNECTION_STRING"
    }
}

...
local.settings.json {
   "Values": {
    ...
   "COSMOS_DATABASE": "dbName",
    "COSMOS_COLLECTION": "collectionName",
    }
}
```

**Comment by ealsur** [comment]
Values that need to be read from the Configuration environment, need to be wrapped with % in Azure Functions:

    function.json {
        {
          "type": "cosmosDB",
          "name": "document",
          "direction": "out",
          "databaseName": "%COSMOS_DATABASE%",
          "collectionName": "%COSMOS_COLLECTION%",
          "connectionStringSetting": "COSMOS_CONNECTION_STRING"
        }
    }

**Comment by antempus** [comment]
@ealsur 

Can confirm your suggestion works, where should this be forwarded to for documentation adjustments for future reference?

**Comment by ealsur** [comment]
This is a documented behavior in Azure Functions regarding replacing values from configuration environment https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings

**Comment by antempus** [comment]
Awesome, looks like I made a mistake here and didn't dig in far enough. 

Thanks @ealsur
