### ISSUE TITLE
CosmosDB extension incompatible with BulkExecutor NuGet Package

### ISSUE THREAD

**Issue by ryanspletzer** [Azure/azure-webjobs-sdk-extensions#572]
If you've been using `Microsoft.Azure.WebJobs.Extensions.CosmosDB` which relies on the 2.2.0 version of `Microsoft.Azure.DocumentDB.Core` package then you can't use `Microsoft.Azure.CosmosDB.BulkExecutor` which relies on 2.4.0 version of DocumentDB package (or 2.1.3 for the preview version of the package). However relying on specific versions instead of a range of versions in either project may break this again.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a blank functions app.

2. Add a Cosmos DB trigger function.

3. Add the `Microsoft.Azure.CosmosDB.BulkExecutor` package and try to instantiate a BulkExecutor with the following sample code (it doesn't need to execute to repo, as it won't compile):

```
ConnectionPolicy connectionPolicy = new ConnectionPolicy
{
    ConnectionMode = ConnectionMode.Direct,
    ConnectionProtocol = Protocol.Tcp
};
DocumentClient client = new DocumentClient(new Uri("https://localhost:8081"), "key", connectionPolicy);

DocumentCollection collection = client.ReadDocumentCollectionAsync(
    "https://localhost:8081").Result;

// Set retry options high during initialization (default values).
client.ConnectionPolicy.RetryOptions.MaxRetryWaitTimeInSeconds = 30;
client.ConnectionPolicy.RetryOptions.MaxRetryAttemptsOnThrottledRequests = 9;

IBulkExecutor bulkExecutor = new BulkExecutor(client, collection);
bulkExecutor.InitializeAsync().Wait();

// Set retries to 0 to pass complete control to bulk executor.
client.ConnectionPolicy.RetryOptions.MaxRetryWaitTimeInSeconds = 0;
client.ConnectionPolicy.RetryOptions.MaxRetryAttemptsOnThrottledRequests = 0;
```

#### Expected behavior

BulkExecutor should be able to be instantiated in a project that's using the CosmosDB trigger and the BulkExecutor package.

#### Actual behavior

The project won't compile.

#### Known workarounds

None at this time -- preview versions of BulkExecutor package still rely on DocumentDB 2.1.3 and there appears to be no version of BulkExecutor package that rely on 2.2.0. It's also not clear why BulkExecutor doesn't use DocumentDB.Core package instead. (Source code is not present in this repo which the BulkExecutor NuGet package points to: https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started)

#### Related information 

Provide any related information 

* Package version: 3.0.3
* Links to source: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj#L21

**Comment by v-anvari** [comment]
@**ealsur** / @mhoeger , can you suggest if this is a feasible request to include in the package, or is it a known issue like [#247](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/247)

**Comment by v-anvari** [comment]
Hi @ealsur , Please suggest if this can be added to a feature request

**Comment by ealsur** [comment]
Higher versions of the BulkExecutor package have no equal restrictions on SDK versions, please update the BulkExecutor package to a higher version
