### ISSUE TITLE
Doc links to the Singleton feature no longer work

### ISSUE THREAD

**Issue by StingyJack** [Azure/azure-webjobs-sdk-extensions#580]
Pages like https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger

Have a link to  https://github.com/Azure/azure-webjobs-sdk/wiki/Singleton

But that just redirects to https://github.com/Azure/azure-webjobs-sdk/wiki

(That isnt the only page I've come across that has that link, its on a few SO posts, and elsewhere)

And as a result I cant find the actual usage docs for `[Singleton]`, to see if it is expected to work like a proper synchronization barrier and only permit a single instance of the function to be executed at a time.

**Comment by v-anvari** [comment]
Hi @StingyJack , thankyou for bringing this to us.

@FinVamp1, can you kindly update the link?

**Comment by v-anvari** [comment]
The document has been updated

**Comment by FinVamp1** [comment]
This link has been updated to point to https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to#singleton-attribute as a lot of the Web Jobs SDK content resides there instead of the wiki.
