### ISSUE TITLE
Readme broken link to ErrorTrigger sample

### ISSUE THREAD

**Issue by OzBob** [Azure/azure-webjobs-sdk-extensions#589]
In the Readme (https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/README.md) there is a link to:

Error Monitoring Sample http://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Samples/ErrorMonitoringSamples.cs

but that code file does not exist, in dev or master branches.

**Comment by v-anvari** [comment]
Hi @OzBob , Thankyou for bringing this to notice, we will update the docs shortly.

**Comment by v-anvari** [comment]
The changes have been committed here - [https://github.com/Azure/azure-webjobs-sdk-extensions/pull/669](https://github.com/Azure/azure-webjobs-sdk-extensions/pull/669). Closing this issue
