### ISSUE TITLE
Want to pass sqlQuery in from Function Python code.

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-webjobs-sdk-extensions#596]
I have a Python function with an HttpTrigger which is supposed to pull either a single document or a list of documents using the following routes:

    /questions/001
    /questions

I would like to be able to perform this in a single function. Here is my functions.json:

        {
          "type": "cosmosDB",
          "name": "questions",
          "databaseName": "questions",
          "collectionName": "questions",
          "connectionStringSetting": "CosmosDBConnection",
          "direction": "in",
          "partitionKey": "{Id}",
         "sqlQuery": "select * from c where c.id = {id}"
        }

Here is my Python code:

    def main(req: func.HttpRequest, questions: func.DocumentList) -> func.HttpResponse:
        if not questions:
            res = "ok"
        else:
            res = questions[0].to_json()

        return func.HttpResponse(res)

I would like to be able to build my sqlQuery in Python and pass that into my function.json file so that I can use the same binding to retrieve a single document or multiple documents. I don't know how to do that; I don't know if it's possible. I can't find any good documentation that says if this is or is not possible. Ideally, I'd like the `sqlQuery` part of my CosmosDB binding look something like this:

    "sqlQuery": "{sqlQuery}"

**Comment by v-anvari** [comment]
Hi @aarsan , Apologies for the delayed response. We were tracking all the old issues while we found this request. Can you let us know if you were able to find any solution to this.
