### ISSUE TITLE
Documentation is out of date with the latest Azure Web Job SDK version

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-webjobs-sdk-extensions#603]
#### Repro steps
1. Read the [documentation](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/master) 
 and note that I should configure the `JobHostConfiguration` class.

#### Expected behavior
The documentation should provide guidance on how to configure the `HostBuilder` because the `JobHostConfiguration` class is [deprecated](https://github.com/Azure/azure-webjobs-sdk/issues/1870#issuecomment-417888043).

#### Actual behavior
The documentation does not match the code [sample](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Program.cs)

#### Known workarounds
I can use the code sample and [supporting documentation ](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started) to get started.

**Comment by v-anvari** [comment]
Hi @KSchlobohm , Thank you for bringing this up, Further checking with the team on updating the documentation.

**Comment by v-anvari** [comment]
#https://github.com/Azure/azure-webjobs-sdk-extensions/pull/665

**Comment by v-anvari** [comment]
Closing this issue, as the commits have been made
