### ISSUE TITLE
Dependencies warning on Microsoft.Azure.WebJobs.Extensions

### ISSUE THREAD

**Issue by Laurianti** [Azure/azure-webjobs-sdk-extensions#607]
Microsoft.Azure.WebJobs.Extensions 3.0.5 uses Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11)
But Microsoft.Azure.WebJobs.Host.Storage 3.0.11 doesn't exist.
The following warning is raised:

> warning NU1603: Microsoft.Azure.WebJobs.Extensions 3.0.5 depends on Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11) but Microsoft.Azure.WebJobs.Host.Storage 3.0.11 was not found. An approximate best match of Microsoft.Azure.WebJobs.Host.Storage 3.0.13 was resolved.

Related:
Azure/azure-webjobs-sdk#2297

**Comment by sbest-gcm** [comment]
+1 - had to install the dependency directly

**Comment by reisenberger** [comment]
Linking an underlying issue which should fix this: https://github.com/Azure/azure-webjobs-sdk/issues/2386

**Comment by v-anvari** [comment]
Hi @Laurianti , Thankyou for bringing this out to notice. Closing the issue, as the fix is followed up in [2386](https://github.com/Azure/azure-webjobs-sdk/issues/2386)
