### ISSUE TITLE
Update CosmosDB SDK

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-webjobs-sdk-extensions#610]
Hello folks!

Is there any plans to update the CosmosDB bindings and changefeed host on Azure Functions to use the new [CosmosDB library](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/)?

Would that be an acceptable PR?

Thanks!

**Comment by galvesribeiro** [comment]
Ping

**Comment by galvesribeiro** [comment]
ping

**Comment by scholtes** [comment]
This also solves #629 as CosmosDB SDK v3 support System.Text.Json.

**Comment by Dave76** [comment]
Any update on this one? The fact that the bindings/triggers are still using the old Document SDK seems like a step backwards and can lead to serialization issues when trying to share documents between functions and asp.net core 3.1 projects.

**Comment by v-anvari** [comment]
@ealsur, Does the latest updates use [Cosmos Library](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/), Kindly suggest.

**Comment by ealsur** [comment]
It's in our plans, and work is being done, no ETA currently. It's not just a client-side extension upgrade, but it requires upgrades on other Function components as well (Consumption Plan dynamic scaling)

**Comment by MikeNicholls** [comment]
The new [data plane RBAC in preview](https://devblogs.microsoft.com/cosmosdb/role-based-access-control-preview/) supported by the v3 SDK specifically has [a permission](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#permission-model) for reading from a container's change feed.

It would be perfect if we could set up change feed triggers using an Azure Functions managed identity, currently with the v2 SDK a trigger requires a master key for the entire database.
