### ISSUE TITLE
CosmosDB bindings do not support OFFSET LIMIT on cross-partition queries

### ISSUE THREAD

**Issue by trbenning** [Azure/azure-webjobs-sdk-extensions#621]
Please provide a succinct description of the issue.

#### Repro steps

1. Have partitioned collection
2. Create a function with a CosmosDB input binding that contains a SELECT statement with OFFSET / LIMIT `[CosmosDB(DatabaseName, CollectionName, SqlQuery = "SELECT * FROM c where c.input = {Input} OFFSET 10 LIMIT 10")] IEnumerable<Document> documents`
3. Invoke function

#### Expected behavior

The query returns results that honor the OFFSET / LIMIT clauses

#### Actual behavior

A runtime error is reported: `System.Private.CoreLib: Exception while executing function: {FunctionName}. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'documents'. Microsoft.Azure.DocumentDB.Core: Cross Partition OFFSET / LIMIT is not supported.`

#### Known workarounds

None

#### Related information 

Provide any related information 

* Package version - 3.0.5

**Comment by probablyup** [comment]
@brettsam can anyone on the team comment on when this might be available? We're trying to use azure functions + cosmos with a relatively large document set and not being able to limit queries is a big issue.

**Comment by probablyup** [comment]
Update: extension support for this was merged and released last week https://github.com/Azure/azure-webjobs-sdk-extensions/pull/620

If you are seeing this error as a result of running a sqlQuery in a cosmos azure function trigger/input binding, you're waiting on this PR: https://github.com/Azure/azure-functions-extension-bundles/pull/20
