### ISSUE TITLE
The given key was not present in the dictionary (CosmosDB SQL)

### ISSUE THREAD

**Issue by theav8or** [Azure/azure-webjobs-sdk-extensions#624]
Possible bug in Java CosmosDB (SQL) client, when using **NULL** values in Java function.
Troubleshooting:
Tried to reset the DB
LVL (keeps track of the level in the subtree ) – fails
UDF  (User def’ Query)- works but will use up the AU on DB.

Error can be Reproduce using HTTP trigger -  https://<will-share-later->.azurewebsites.net/api/IsDocSeenBefore
Querying CosmosDB for the same table with NULL onJS completed with-out error
Currently AzF Java version is 1.3.0 (see POM.XML), would  switching to 1.3.1 include code updated to the ComsosDB client?
#### Investigative information

Please provide the following:

- Timestamp: 1/16/2020 9:44:29 AM
- Function App name: Will-share-later
- Function name(s) (as appropriate): IsDeviceSeenBefore, IsPersonSeenBefore, IsDocSeenBefore,
- Invocation ID:
- Region: West Europe 

#### Repro steps

Provide the steps required to reproduce the problem:

**Comment by swau10tix** [comment]
HI there,
The impact of not being able to send null values from fn app to cosmos is :
1. We have to do a work around that includes a lot of conditioning in the SQL
2. It has some performance impact on the query execution

please let us know if/when this can be fixed on the fn app level.

**Comment by v-anvari** [comment]
Hi @ealsur , Can you please look into this request, the bugs must probably be fixed already. Can you please share your inputs

**Comment by ealsur** [comment]
@v-anvari I don't know if this is related to Java or not, but I don't see what is the actual error stack trace? Without that, it's hard to know what is the origin. I get that the customer is using CosmosDB bindings, but I don't see if the error is actually related to any code path in the particular extension or it is part of the .NET > Java translation layer.

**Comment by v-anvari** [comment]
Thank you Mathias, 

@theav8or are you still facing this error, is yes can you provide the latest error details, that is the latest invocation id of the error and the region.
