### ISSUE TITLE
Add support for Non-Scale Startup & restarts to "Warmup" trigger

### ISSUE THREAD

**Issue by elksson** [Azure/azure-webjobs-sdk-extensions#632]
Our API uses a very large DbContext which takes time to compile the models and views. Since we are using EF Core 3.x there is not the capability to cache the model to speed up the first start so we get very slow response times when our function app is not properly warmed. 

The Warmup trigger currently only supports being triggered when the function is scaling up. However we need to execute this same function also when the instance or application is restarted. So that every time our API is called even the first time EF Core is already initialized and can return the data fast. 

#### Repro steps

Provide the steps required to reproduce the problem

Create a large EF Core Code first migration project. 
Create an HTTP Function which queries the API for an entity and returns the result
Observe the first time you call the API the response is very slow. however subsequent calls are much faster. 

#### Expected behavior

EF Core is initialized by the warmup trigger on both scale out, and restart and non scale out operations. This allows the application to compile the EF Core models, and views. resulting in high speed results even on the first call to the HTTP Trigger

**Comment by v-anvari** [comment]
Hi @elksson , Apologies for the delayed response. We were tracking all the old issues while we found this request. Can you let us know if you were able to find any solution to this.
If you are still facing the delay, then let us know the invocation id of the error and the region that its running.
