### ISSUE TITLE
Listener for function was unable to start

### ISSUE THREAD

**Issue by atsapura** [Azure/azure-webjobs-sdk-extensions#633]
I'm trying to use `CosmosDBTrigger` with a collection of `Document`s, but on the start I get this error:
```
The listener for function 'index-product' was unable to start.
The listener for function 'index-product' was unable to start. Microsoft.Azure.DocumentDB.Core: Gateway Failed to Retrieve Query Plan: Unknown QueryFeatures:  NonValueAggregate
ActivityId: 3fba08b2-f061-4bac-be4b-178ba6da68e3, Microsoft.Azure.Documents.Common/2.5.1, Windows/10.0.17763 documentdb-netcore-sdk/2.9.3.
```

The code looks like this:
```fsharp

    [<FunctionName("index-product")>]
    let indexProduct
        (
            [<CosmosDBTrigger("dbName",
                             "collectionName",
                             ConnectionStringSetting = "cnn",
                             LeaseCollectionName = "leases",
                             CreateLeaseCollectionIfNotExists = true)>]
            documents : IReadOnlyCollection<Document>,
            [<CosmosDB("dbName", "anotherCollection", ConnectionStringSetting = "cnn")>]
            client: DocumentClient,
            logger : ILogger
        ) = 
       ...

```

If this cosmos trigger is removed, no error occurs. I use Cosmos Emulator and Storage Emulator locally, both are running and responsive.
Also, this problem is tied to environment, since the exact same code works on other machine.

**Comment by petro2050** [comment]
I keep getting this issue every once in a while along with `The lease was lost`. Since triggers cannot start, a lot of back-end processing I need to do fails. I'm having this issue with remote deployment.

**Comment by v-anvari** [comment]
Hi @atsapura, Thankyou for the update. Let us know if you are facing any issues with the latest versions.
