### ISSUE TITLE
Ability to provide the start time for the CosmosDb change feed

### ISSUE THREAD

**Issue by ianrkent** [Azure/azure-webjobs-sdk-extensions#637]
The `ChangeFeedProcessorOptions.StartTime` provided by the underlying CosmosDb Change Feed Processor allows the user to specify a point in time for which they would like to start receiving the feed - as specified [here](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed)

The current wrapper around this provided by the `CosmosDBTriggerAttribute` does not support setting this start time, 

Having access to setting the start time would allow more fine grain control of the CosmosDb change feed, specifically when you know you don't want to process historical data.

**Comment by ankku** [comment]
Is there any fedback from Microsoft on this??

**Comment by v-anvari** [comment]
@ealsur , Kindly look into this request, is it possible to give the access?

**Comment by ealsur** [comment]
@v-anvari Please see https://github.com/Azure/azure-webjobs-sdk-extensions/pull/691

**Comment by v-anvari** [comment]
Thankyou Mathias 

Closing this issue as the update is provided in [https://github.com/Azure/azure-webjobs-sdk-extensions/pull/691](https://github.com/Azure/azure-webjobs-sdk-extensions/pull/691)
