### ISSUE TITLE
databaseName parameter in cosmos trigger requires constant parameter

### ISSUE THREAD

**Issue by Kitwradr** [Azure/azure-webjobs-sdk-extensions#645]
![image](https://user-images.githubusercontent.com/26614919/80955509-0e19f780-8e1d-11ea-92be-c6ea86064813.png)

How to get the variables from local.settings.json and use it?

**Comment by Badabum** [comment]
First, as the error says, in c# attribute argument should be a constant expression. That's a language constraint. `Environment.GetEnvironmentVariable` is not constant. To use `local.settings.json` value here you should wrap setting name in `%` like this: `databaseName: "%CosmosDBDatabaseName%"`

**Comment by v-anvari** [comment]
Hi @Kitwradr, Apologies for the delayed response. Let us know if you were able to resolve this issue.
