### ISSUE TITLE
SendGrid Dynamic template data method missing in sendgrid function template

### ISSUE THREAD

**Issue by stephenstroud** [Azure/azure-webjobs-sdk-extensions#646]
Missing method for adding dynamic template data when using dynamic template id

Example
```
           var dynamicTemplateData = new 
            {
                link = "www.example.com"
            };

            var message = new SendGridMessage()
            {
                TemplateId = Environment.GetEnvironmentVariable("SendGridTemplateId"),
                TemplateData = dynamicTemplateData //Missing
            };
```

#### Related information 

https://github.com/sendgrid/sendgrid-csharp/issues/858

**Comment by DjolePetrovic** [comment]
Because they are not using the latest Sendgrid Nuget package as their dependency.

**Comment by v-anvari** [comment]
Hi @stephenstroud , Let us know if you are still facing this issue with the latest NuGet packages.

**Comment by stephenstroud** [comment]
@v-anvari I'm not seeing any update for the package Microsoft.Azure.WebJobs.Extensions.SendGrid v3.0.0 where this issue exists. I got around this issue by installing the Twilio Sendgrid package in addition to this library.

**Comment by v-anvari** [comment]
Hi @stephenstroud ,Could you please elaborate your error and kindly provide the repro steps.

I was able to get a successful build, using visual studio and following this [template](https://github.com/sendgrid/sendgrid-csharp/blob/main/USE_CASES.md#transactional-templates) 

I have added Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0 and SendGrid C# client lib

**Example code:**

using System;
using System.Threading.Tasks;
using SendGrid.Helpers.Mail;

namespace FunctionApp1
{
    public static class Function1
    {
        private static void Main()
        {
            Execute().Wait();
        }
        static async Task Execute()
        {
            var dynamicTemplateData = new ExampleTemplateData
            {
                Subject = "Hi!",

            };
            var msg = new SendGridMessage();
            msg.SetTemplateData(dynamicTemplateData);

            var message = new SendGridMessage()
            {
                TemplateId = Environment.GetEnvironmentVariable("SendGridTemplateId"),

            };
        }
    }
