### ISSUE TITLE
Are TimerTriggered Azure Functions called in parallel if the execution takes longer than the interval between two triggers

### ISSUE THREAD

**Issue by wischi-chr** [Azure/azure-webjobs-sdk-extensions#656]
I'm currently writing a TimerTrigger triggered Azure Function that triggers every minute.
`[TimerTrigger("0 * * * * *")]`

_(I use a CRON expression because I'm on a consumption plan)_

The function is pretty quick in most of the time (1-5s) and runs every minute. But if there is a lot of work for the function it can take longer than 60s.

According to a wiki entry in this repositoy:
https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger

> If your function execution takes longer than the timer interval, another execution won't be triggered until after the current invocation completes. The next execution is scheduled after the current execution completes.

But in the microsoft azure function documentation it states the exact opposite:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#parallel-execution

>When multiple triggering events occur faster than a single-threaded function runtime can process them, the runtime may invoke the function multiple times in parallel. If a function app is using the Consumption hosting plan, the function app could scale out automatically.

Is this true for all triggers (even the TimerTrigger), or is the TimerTrigger an exception?

I also found this exact question on stackoverflow:
https://stackoverflow.com/questions/49282060/azure-functions-timer-trigger-thread-safety
with two exact opposite answers. One of them has more upvotes but no comment or argument about the parallel-execution documentation from microsoft.

And even stranger than that is the fact that the trigger doesn't even work most of the time.
For example take a look at the function invocations between 12:15 and 13:00.

![image](https://user-images.githubusercontent.com/2495113/88184777-69e16900-cc33-11ea-96b2-127a72f9c45e.png)

But according to the successful execution count diagram the function was running just fine
![image](https://user-images.githubusercontent.com/2495113/88185189-eecc8280-cc33-11ea-8b87-69834ce65416.png)

**Questions:**
- Can TimeTrigger Functions be called in parallel?
- How can I diagnose the issue with a time triggered function that isn't executed according to schedule.

Thanks in advance.

**Comment by v-anvari** [comment]
Hi @wischi-chr , [Parallel execution](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#parallel-execution) is referring to different triggers in a single function app, in that case different triggers can run as multiple threads. But, considering a single trigger, it will run after a job has finished. In this case, a timer triggered job runs every min.

You will be able to analyze the data logs of each invocation in detail in [Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview) and diagnose exceptions for failed logs in the [exceptions blade](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions#diagnosing-failures-using-the-azure-portal).

If you are still finding an error in execution, let us know the latest failed invocation id and function app name
