### ISSUE TITLE
Can't create lease collection for graph account when using change feed trigger

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-webjobs-sdk-extensions#657]
Please provide a succinct description of the issue.

#### Repro steps

1. Create a cosmos db account with Gremlin API
2. Create a database
2. Create a graph in the database with shared throughput(or provisioned throughput, it doesn't matter)
3. Create a V3 function app
4. Define a function with CosmosDBTrigger:

```csharp
  public Task CaptureChange([CosmosDBTrigger(
                "<database-name>",
                "<collection-name>",
                ConnectionStringSetting = "<connection-string>",
                LeaseCollectionName = "<lease-collection-name>",
                CreateLeaseCollectionIfNotExists = true)]
```

#### Expected behavior

Lease collection with name `<lease-collection-name>` is created. And function receives new changes

#### Actual behavior

Exception with the message: `Shared throughput collection should have a partition key,` is thrown.

#### Known workarounds

No known workarounds. I tried to create a lease collection using portal and cli but it fails because you can't create a collection with partition key `/id`(which is required by the changefeed) in the graph account. This used to work previously, at least we have 2 envs with change feed on graph collections, but they have been created pretty long ago.

#### Related information 

Provide any related information 

* `"Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.7" `

**Comment by Badabum** [comment]
Seems like cosmos apis has been updated and do not allow to create collection with `/id` partition key - which is the requirement for leases collection - in graph database. I've discovered that possible workaround is to use separate SQL cosmos account and database for leases collection. Also researching this problem in one of cosmos sdk repositories I've read that `/id` partition key is not a requirement anymore, so maybe the dependency in mentioned extension just needs to be updated.

**Comment by phillsteele** [comment]
Any update on this?  It would seem at the very least documentation should direct you to create your lease container in a separate SQL API database if a lease container can't be created in Gremlin API database.

**Comment by v-anvari** [comment]
@ealsur, Can you help us here with the information asked? 

Followed [Docs](https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-dotnet) to reproduce this issue, but the function app works as expected with no errors.

Repro steps:

1. Create a Azure Cosmos DB account
2. Create an Azure Function app
3. Create Azure Cosmos DB trigger
4. Connect to your Azure Cosmos DB account and create the Items container in the Tasks database
5. Update new vertex to test the function
6. Function logs shows the updated logs with every new update in vertex

Function app name : 657
Cosmos Account: 657
Region: EAST US
Time stamp: 2020-10-08 13:15:54.333

**Comment by ealsur** [comment]
Change Feed Processor (which is used on the Cosmos DB Trigger) is not compatible with Gremlin accounts, it's a library meant to be used on SQL API accounts that uses the SQL API SDK.

The only workaround possible is to store the lease collection in another Cosmos account that is SQL API.

This is called out on the Functions documentation: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#supported-apis

![image](https://user-images.githubusercontent.com/1633401/95492747-6adf8800-0950-11eb-8fd1-fec04fd24a55.png)

**Comment by v-anvari** [comment]
Hi @Badabum, As Matias has confirmed that the only workaround possible is to store the lease collection in another Cosmos account, please find more details on the above comment. 

In case of any further queries related to this feature, please feel free to reopen the issue.

**Comment by Badabum** [comment]
@v-anvari thx, the docs are clear and I've switched to the workaround with sql account quite a while ago
