### ISSUE TITLE
Does SendGrid use port 80?

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-webjobs-sdk-extensions#660]
I'm in CSS and we have a customer inquiry as to whether the SendGrid trigger from WebJobs SDK uses HTTP port 80 communication.
They received an email from SendGrid that support for port 80 is ending and want to confirm the impact for WebJobs SDK.

**Comment by Niladri24dutta** [comment]
@dcbrown16 Sendgrid uses port 443 (https) for all the V3 REST API calls in the behind. So as per my understanding you can still use it.

**Comment by Niladri24dutta** [comment]
@dcbrown16  you can still create an issue for that here https://github.com/sendgrid/sendgrid-csharp/issues

**Comment by v-anvari** [comment]
Hi @dcbrown16 , As suggested, if you still have any queries please raise an issue in [Sendgrip Csharp issues]( https://github.com/sendgrid/sendgrid-csharp/issues). Hence, closing this issue in this repository.
