### ISSUE TITLE
AddTimer Issue

### ISSUE THREAD

**Issue by ahmedzeyada** [Azure/azure-webjobs-sdk-extensions#662]
I have just updated to Microsoft.Azure.WebJobs.Extensions to Version=3.0.6.
I am using AddTimer method in azure WebJob and this causing a problem =>
Could not load assembly  Microsoft.WindowsAzure.Storage.dll.

**Comment by v-bbalaiagar** [comment]
Hi @ahmedzeyada , Apologies for the delay in response. This issue was somehow missed, we are eager to know if you are still facing the same issue, so that we can look into it.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
