### ISSUE TITLE
StorageScheduleMonitor does not support using Visual Studio service dependencies to link to an Azure Storage Account

### ISSUE THREAD

**Issue by thesuavehog** [Azure/azure-webjobs-sdk-extensions#692]
**Problem**: StorageScheduleMonitor used a fixed value for the configuration key name for the Storage Service Connection String:
https://github.com/Azure/azure-webjobs-sdk-extensions/blob/afb81d66749eb7bc93ef71c7304abfee8dbed875/src/WebJobs.Extensions/Extensions/Timers/Scheduling/StorageScheduleMonitor.cs#L77

While this is referenced in the WebJobs SDK How-To (https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to - `Because version 3.x uses the default .NET Core configuration APIs, there is no API to change connection string names.`) it breaks the ability to use the Visual Studio service dependencies as the setup for the Azure Storage in the Connected Services puts a key in the `secrets.json` files named `ConnectionStrings:<LABEL>` (where `<LABEL>` is the name you give the service when setting it up). 

When you inspect the setup of the various Connected Service json files, it seems like it will be "smart" and use the right connection string... except that the WebJobs SDK won't use it.

The proper solution is probably for `AddAzureStorageCoreServices` to take a configuration parameter as is the norm for many of the Add___ or Configure___ pattern methods.

However it would be nice for the SDK to play nice with the Visual Studio connected service dependencies and fall back to that if the `AzureWebJobsStorage` is not set without additional config.

**Comment by v-anvari** [comment]
Hi @ealsur / @brettsam , Is it possible to access the connection string from a key in a .json file without any additional configuration.

**Comment by ealsur** [comment]
@v-anvari I have no involvement in any of these other extensions, I only worked on the Cosmos DB extension.

**Comment by v-anvari** [comment]
Thankyou @ealsur 

cc @fabiocav

**Comment by fabiocav** [comment]
@thesuavehog would you mind sharing a the repro steps for the issue? This might be something we've made some progress on and some of the details might be missing

Thank you!

cc @stefanushinardi @vijayrkn
