### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.Http updates missing from Nuget

### ISSUE THREAD

**Issue by b-twis** [Azure/azure-webjobs-sdk-extensions#695]
Hello,

It looks like Extensions.Http package has not been published to nuget since v 3.0.2 in Jan 2019.
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Http/

Is there a reason that there are no later stable versions published? 

I am looking to include the fixes from the following commit related to **request.EnableBuffering();**
https://github.com/Azure/azure-webjobs-sdk-extensions/commit/ff2440ac1f657ba76f5ab5a3cefafa3c55a50fdb#diff-4ba2e016cd5f274903d211369de77dec50b4248e2c38fb772d8fa9c59332d262

Later releases including 3.0.7 seem to be tagged in this repo, but are nowhere to be found in public stable nuget land

https://myget.org/gallery/azure-appservice seems to contain multiple later versions
https://myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.Extensions.Http

Are any of these stable? and if so where can I find them?

Thanks,

Basil

**Comment by v-anvari** [comment]
Hi @brettsam, Can you confirm if this is in plan to update the latest versions in the NuGet gallery, or do we have any blocker

**Comment by b-twis** [comment]
Any news on this?

**Comment by hugopacheco** [comment]
Hello, any updates on this? 

The most recent version available on nuget.org is 3.0.12 and it references a vulnerable version of System.Text.Encodings.Web (https://github.com/Azure/azure-webjobs-sdk-extensions/issues/760). 

The most recent version of Microsoft.Azure.WebJobs.Extensions.Http (3.2.0) [no longer references System.Text.Encodings.Web](https://github.com/Azure/azure-webjobs-sdk-extensions/commit/e26b47977c5a88d41655237e0d9463904887e9ef), however it's not available on nuget.org :(

Thanks in advance!

**Comment by hugopacheco** [comment]
Happy to report 3.2.0 was published to nuget.org 2 days ago (yyyy-MM-dd: 2022-08-09). 

@b-twis I think this issue can be closed

**Comment by JonasJes** [comment]
Is this update related to https://github.com/Azure/azure-functions-vs-build-sdk/issues/589 ?
