### ISSUE TITLE
Managing the HttpClient for Cosmos

### ISSUE THREAD

**Issue by martinjt** [Azure/azure-webjobs-sdk-extensions#724]
I'm attempting to get CosmosDbTriggers working against the cosmos emulator.  Specifically, this is a problem when the emulator runs with a different hostname (i.e. part of a docker-compose).

This details how to do disable SSL validation, however, this isn't an access level we have in the CosmosDbTrigger attribute.
https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=cli%2Cssl-netstd20#disable-ssl-validation

I can see 4 distinct ways that this could be fixed, and I'm happy to do the work if you're happy to accept the changes.

*Option 1:* Parameter on the Attribute for Disabling SSL Validation
Provide a bool on the attribute properties that will generate a DocumentClient with SSL validation disabled (overriding the handlers).  

*Option 2:* Unseal/make public the `ICosmosDbService` interfaces
If these were opened up, we could inject our own at startup.

*Option 3:* Make the trigger support 
This would be then specifically optimised to use against the emulator.  This is potentially more work to maintain, but encapulat

Option 4: Make the DocumentClient get it's HttpClient from the services HttpClientFactory
If this uses a named httpclient from the HttpClientFactory, then we can override this in the Client factory to return one that bypasses the SSL validation.  This is potentially dangerous as "Global" HttpClient changes could inadvertently affect the Trigger client without intending to.

My preference is Option 2 as it's obscure enough that it wouldn't be used by everyone as a simple property change, but powerful enough to give us an extension point for testing.  It doesn't tie anything to the emulator scenario and introduces other interesting scenarios I think.

What I need to know is, would that be accepted by the maintainers?  I have noticed that there's an upgrade to the V3 SDK in there, so maybe it's a fast follower after that?

**Comment by v-anvari** [comment]
cc @ealsur , Do you have any insights here, is this supported.

**Comment by ealsur** [comment]
No, this is not possible, the internal HttpClient or configuration is not accessible.

**Comment by v-anvari** [comment]
Thank you @ealsur 

Hi @martinjt , Let us know if you have any further queries

**Comment by martinjt** [comment]
Thanks both,. The question isn't whether it's possible though, it's whether you'd accept a PR that makes it possible.

There are some options in the ticket that would make it accessible using the HttpClientFactory approach that the underlying Cosmos SDK providers (which the webjobs ask is hiding right now)

**Comment by ealsur** [comment]
@martinjt DocumentClient does not allow you to inject the HttpClient instance. For that, it would require https://github.com/Azure/azure-webjobs-sdk-extensions/pull/717 to be merged and the new extension to be released/integrated in Azure.
