### ISSUE TITLE
Reference to Microsoft.Azure.WebJobs.Extensions.Http 3.* is pulling in unlisted package version 3.1.1

### ISSUE THREAD

**Issue by jmullen974** [Azure/azure-webjobs-sdk-extensions#726]
My PackageReference to Microsoft.Azure.WebJobs.Extensions.Http 3.* is pulling in unlisted package version 3.1.1

#### Repro steps

1. Include the following in a .csproj file:
`<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.*" />`

2. Check the package version that was pulled in by Nuget.

#### Expected behavior

Nuget should pull in the latest stable 3.* version which is 3.0.12

#### Actual behavior

Nuget pulls in Microsoft.Azure.WebJobs.Extensions.Http 3.1.1, which is an unlisted version.

#### Known workarounds

Pin the package to version 3.0.12:
`<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.12" />`

#### Related information 

* [Nuget page for unlisted version](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Http/3.1.1)
* I am using Visual Studio 2019 version 16.9.6

**Comment by liliankasem** [comment]
@fabiocav @brettsam do we need to publish the 3.1.1 package or is it unlisted for a reason?

**Comment by fabiocav** [comment]
@liliankasem the package is published and unlisted, otherwise, there would be a failure here.

@jmullen974 this is purely NuGet behavior. Are you experiencing this in multiple environments? Can you share a sample project where you have that issue?

**Comment by jmullen974** [comment]
@fabiocav I am seeing this on my local machine, and in Azure DevOps on a windows-2019 agent. Azure support was able to reproduce the issue as well. Here is a sample project: 
[ConsoleApp1.zip](https://github.com/Azure/azure-webjobs-sdk-extensions/files/7571193/ConsoleApp1.zip)
.

**Comment by jmullen974** [comment]
This is no longer a problem now that Microsoft.Azure.WebJobs.Extensions.Http 3.2.0 is out
