### ISSUE TITLE
How to pass parameter using Cosmosclient object and update the property LimitToEndpoint

### ISSUE THREAD

**Issue by bandarum** [Azure/azure-webjobs-sdk-extensions#727]
var client = new CosmosClient(endpoint, masterKey, new CosmosClientOptions()
{
LimitToEndpoint = true,
ConnectionMode = Microsoft.Azure.Cosmos.ConnectionMode.Gateway
});
LimitToEndpoint = true,

**Comment by ealsur** [comment]
Duplicate of https://github.com/Azure/azure-webjobs-sdk-extensions/issues/728

**Comment by v-anvari** [comment]
Closing the issue as duplicate
