### ISSUE TITLE
Ability to specify UserAgentSuffix for CosmosDbTriggerAttribute and CosmosDBAttribute 

### ISSUE THREAD

**Issue by bernarden** [Azure/azure-webjobs-sdk-extensions#729]
After a brief investigation I found that UserAgentSuffix is always hardcoded to the same value [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/a0fb2011acfa88126d9eecc285d7a7f8283ccbe5/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs#L22). It would be good to be able to specify the UserAgentSuffix on CosmosDBTriggerAttribute and CosmosDBAttribute or perhaps be able to set it globally. This would allow us to query Cosmos DB logs per function/unique name instead of always seeing `CosmosDBTriggerFunctions` in the logs.

**Comment by ealsur** [comment]
Could you describe the scenario? Would you want it to be set to the Function name or some custom value?

**Comment by bernarden** [comment]
We are currently trying to optimise our Cosmos DB usage i.e. we want to identify number of requests and their costs for each of the Azure Function Apps we have (~35). As part of this process we updated all our code to specify user agent to be the same as the name of the Azure Functions App it's hosted on. The only functions where we couldn't do this are the functions that still use CosmosDbTriggerAttribute and CosmosDBAttribute. Ideally we want to be able to set the user agent to any custom value we want.

**Comment by ealsur** [comment]
@bernarden Would the user agent modification be at the Function level (each Function inside the same project with different user agent)? Or all the Functions inside the same Function App would have the custom user agent?

The problem with the first one is that you cannot reuse the same client instance across Functions. If 2 Functions bind to the same Cosmos DB account, we can reuse the client and reduce connections, but if both need to have different user agents, then that would void that approach if each Function has different user agent.

The question also defines where the setting should be. It could be a setting defined at the `host.json` level (like the connection mode, for all client instances in the Function App) or at the attribute level.

**Comment by bernarden** [comment]
It would be best for our use case to be able to specify a custom user agent for each Function using the CosmosDBTriggerAttribute and CosmosDBAttribute attributes. Although I do think that the default user agent value should be overwritable using the host.json file.
