### ISSUE TITLE
Notification upon Aborted Triggered WebJob

### ISSUE THREAD

**Issue by p202-rross** [Azure/azure-webjobs-sdk-extensions#734]
More of a question...

I have a triggered (scheduled) WebJob in which I'd like to send an email if the job is aborted or stops running. I'm finding some older, deprecated solutions for this, but nothing for .NET Core 3+. 

What are some approaches other have taken for this?

**Comment by Sergey-Nosov-GH** [comment]
If you have Application Insights hooked up and you can infer the abnormal condition from logs, you could add an Alert Rule.

**Comment by v-bbalaiagar** [comment]
Hi @rachael-ross,  Let us know if the above information resolves your query, or if you have any further queries.
