### ISSUE TITLE
Is it possile to use Application settings in order to specify the values of CosmosDb trigger properties like MaxItemsPerInvocation?

### ISSUE THREAD

**Issue by tunoi** [Azure/azure-webjobs-sdk-extensions#735]
This seems to be working for string type properties only (by enclosing the property value with %). For integer or boolean property types this solution cannot be used. Is there any alternative to this that also supports integer/boolean property types?

**Comment by ealsur** [comment]
That is limited by the binding expressions, I don't believe that is possible for int types.

**Comment by v-bbalaiagar** [comment]
FYI @AnatoliB

**Comment by alrod** [comment]
Answered.
