### ISSUE TITLE
Serializer customization using `ICosmosDBSerializerFactory` does not work

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-webjobs-sdk-extensions#743]
I created a class that implements `ICosmosDBSerializerFactory` and tried to customize the default serializer, but it did not work correctly because `CreateSerializer` was not called.

It seems that after adding the customized `ICosmosDBSerializerFactory` to the DI, the Cosmos DB Extension overrides it with the default SerializerFactory.

The initialization by Startup seems to be done in the order of `Function App` => `Extensions`, so if the Extension provides an extensible interface, it need to use `TryAddSingleton`. (In Function Extensions, it could be a convention to use `TryAddSingleton`)

- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/src/StorageBlobsWebJobsBuilderExtensions.cs
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/src/StorageQueuesWebJobsBuilderExtensions.cs

#### Repro steps

```csharp
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        builder.Services.AddSingleton<ICosmosDBSerializerFactory, MyCosmosDBSerializerFactory>();
    }
}

public class MyCosmosDBSerializerFactory : ICosmosDBSerializerFactory
{
    public CosmosSerializer CreateSerializer()
    {
        var options = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

        // From https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs
        return new CosmosSystemTextJsonSerializer(options);
    }
}
```

#### Expected behavior

The customized SerializerFactory will be used.

#### Actual behavior

The default implementation of SerializerFactory is always used.

#### Known workarounds

Not available.

#### Related information 

* `Microsoft.Azure.WebJobs.Extensions.CosmosDB` : `4.0.0-preview1`
* https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Config/CosmosDBWebJobsBuilderExtensions.cs#L36

**Comment by shibayan** [comment]
@ealsur I believe `ICosmosDBSerializerFactory` is designed to be user customizable, is this understanding correct?

**Comment by ealsur** [comment]
@shibayan that is correct, there is a test here covering the expected behavior: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBHostBuilderExtensionsTests.cs#L74-L104

What kind of operations are you performing after? The Create is not called until you do an operation that requires the creation of a client instance

**Comment by ealsur** [comment]
I think the reason the test did not catch this is because the test registers the custom serializer factory after calling AddCosmosDB on the host configuration, while maybe in your code, the injection of the custom serializer is happening before.

**Comment by ealsur** [comment]
Yes, that's the problem. I found it when inverting the test order. I added it to the current PR that is fixing AAD so we fix both issues with the same next release

**Comment by shibayan** [comment]
Thank you for the quick response.

The order of `Startup` class was fixed by Function SDK as follows, although it is not clearly stated in the documentation. I'm sure the added commit will fix this!
```json
{
  "extensions":[
    { "name": "Startup", "typeName":"FunctionApp24.Startup, FunctionApp24, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"},
    { "name": "CosmosDB", "typeName":"Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.CosmosDB, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
  ]
}
```

Thanks again.

**Comment by ealsur** [comment]
Yeah, I added a test with the inverted order (injection first then AddCosmosDB) and that initially failed (that's how I came to the conclusion about the order), with the TryAddSingleton change, then both tests passed. Thanks for the pointer to the other examples, that was very useful.

**Comment by ealsur** [comment]
Should be fixed in preview2 release
