### ISSUE TITLE
RBAC support for Cosmos DB Trigger with functions system assigned Identity

### ISSUE THREAD

**Issue by iulianmarius** [Azure/azure-webjobs-sdk-extensions#746]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 
Hello is there a way to use the cosmosDB Input/output bindings in a function with a **system assigned** function identity and CosmosDB RBAC ? this is working for SignalR triggers for example with this connection string :"Endpoint=https://hostname;AuthType=aad;Version=1.0;"
i tried the same with cosmosdb but i get this error 

Microsoft.Azure.WebJobs.Extensions.CosmosDB: Cannot create Collection Information for tasks in database portalResources with lease leases in database portalResources : Value cannot be null. (Parameter 'authKeyOrResourceToken | secureAuthKey'). Microsoft.Azure.DocumentDB.Core: Value cannot be null. (Parameter 'authKeyOrResourceToken | secureAuthKey').

Provide any related information 

* Function Runtime Version: 3.2.0.0
* Links to source

**Comment by ealsur** [comment]
The extension version 3.X.X uses the Cosmos DB V2 SDK which does not support AAD authentication. 

The extension version 4.X.X uses the Cosmos DB V3 SDK which does support AAD authentication: https://azure.microsoft.com/en-us/updates/public-preview-of-v4-cosmos-db-extensions-for-azure-functions/
