### ISSUE TITLE
Unresolved dependency for version 4.0.0-preview3 

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-webjobs-sdk-extensions#756]
Version 4.0.0-preview3 has a dependency on Microsoft.Azure.WebJobs version 3.0.31, but that version is not publiched on nuget

**Comment by v-bbalaiagar** [comment]
Hi @fabiocav, Could you please look into this issue.

**Comment by ealsur** [comment]
If this is for the Cosmos DB extension, it seems this PR bumped the WebJobs dependency on all extensions: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/745

**Comment by mlankamp** [comment]
@ealsur The PR updates the dependency in all extensions, but only Microsoft.Azure.WebJobs.Extensions.CosmosDB seems to have the problem (probably because others are not pushed to nuget after the PR)

**Comment by ealsur** [comment]
Exactly, it is the only released Extension after the bump.

**Comment by ealsur** [comment]
I'm not sure why the base `Microsoft.Azure.WebJobs` 3.0.31 was not released or when it will be. @fabiocav / @brettsam any ideas?

**Comment by mlankamp** [comment]
The package is available on the [myget feed](https://myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs/3.0.31). So it's probably still being tested

**Comment by mlankamp** [comment]
The version is available now, so issue is solved
