### ISSUE TITLE
CosmosDBTrigger: The value for StartFromTime attribute cannot be specified by using biding expression

### ISSUE THREAD

**Issue by oionut** [Azure/azure-webjobs-sdk-extensions#757]
The value of StartFromTime attribute is used without being resolved thus it cannot be specified through config.
Specifying the value of  StartFromTime using biding expression (eg %StartFromTime%) with the actual value set in FunctionApp Configuration always throws an exception: ```The specified StartFromTime parameter is not in the correct format. Please use the ISO 8601 format with the UTC designator. For example: '2021-02-16T14:19:29Z'.``` (https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs#L151)

**Comment by v-bbalaiagar** [comment]
Hi @ealsur , Could you please look into this issue.

**Comment by ealsur** [comment]
@oionut What version of the extension are you using?

**Comment by ealsur** [comment]
Added support for the new extension on the linked PR

**Comment by oionut** [comment]
> @oionut What version of the extension are you using?

@ealsur 4.0.0-preview2

**Comment by ealsur** [comment]
@oionut I sent a PR to add support for that

**Comment by oionut** [comment]
> @oionut I sent a PR to add support for that
Thank you @ealsur
