### ISSUE TITLE
[BUG] CosmosDB trigger function seems to hang and stops processing events when authenticating via MSI

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-webjobs-sdk-extensions#779]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#29104](https://github.com/Azure/azure-sdk-for-net/issues/29104).

### Library name and version

Microsoft.Azure.WebJobs.Extensions.CosmosDB

### Describe the bug

This issue was reported by a customer. The problem started after the customer updated their app to authenticate with CosmosDB using an MSI instead of a connection string. According to the customer, the function seems to hang and stop processing events. To mitigate this issue, the customer had to manually restart the app, and after this, the app would go back to working as expected until the issue manifest it again. 

I reviewed the function executions for the function with the issue and it looks like the invocations were successful. I also reviewed the CPU usage and SNAT port exhaustion for the times when the customer had to manually restart the app from 5/30/22 18:45 to 6/2/22 18:29, and everything seems to be working as expected. For more information, please see [CRI ](https://portal.microsofticm.com/imp/v3/incidents/details/308705579/home) notes for the analysis. 

Given that MSI authentication is a preview feature, I will recommend the customer to move back to using the connection string to authenticate with CosmosDB. 

When getting ready to GA the MSI feature offering, please make sure that we do exhaustive testing for this scenario for all hosting offerings: Consumption and Dedicated (App Service Plan and Premium).

**Comment by Ved2806** [comment]
Hi @ealsur Do you have any inputs on this?

**Comment by ealsur** [comment]
Assuming @Francisco-Gamino you are using the `4.0.0-preview` package and that the change from connection string to MSI was done with the same package version (not going from 3.X and connection string to 4.X and MSI): Make sure the `Microsoft.Azure.Cosmos` dependency is updated on the Function App project to the latest available version. There were versions of the SDK (`Microsoft.Azure.Cosmos`) that had reported issues with MSI authentication.

**Comment by Francisco-Gamino** [comment]
Hello @ealsur , this issue was opened for the [CRI](https://portal.microsofticm.com/imp/v3/incidents/details/308705579/home) you helped me looked into. After investigating, we determined that the function slowed down processing events due to unhandled exceptions in the customer code. Closing issue.
