### ISSUE TITLE
Dependency on ASP.NET 2.2

### ISSUE THREAD

**Issue by czb182** [Azure/azure-webjobs-sdk-extensions#799]
This package depends on asp.net core 2.2, which as far as i know is out of support. Seems like for build targets. 3.1 and above, it should have a framework reference dependency instead of package reference.  I'm using .net6 and its pulling in all .net 2.2 nuget libraries.

This library is reference by Microsoft.NET.Sdk.Functions (4.1.3) so its widely consumed.

**Comment by ramya894** [comment]
@czb182 We will check this issue with our next level team and update you.

**Comment by czb182** [comment]
any update?

**Comment by jviau** [comment]
While we do reference these older functions, this is a compile time reference only. At runtime, the host will be loading up to date versions of these DLLs, so there is no actual security vulnerability. We have a few reasons for this (but not limited to):

1. As a hosted service, we want to provide security patches without requiring customers to update and redeploy their app.
2. AspNetCore team changed how they distribute their dlls. Previously they were individual nuget packages, but they now distribute a 'meta' package, `Microsoft.AspNetCore.App.Ref` which aggregates all these dlls together. Unfortunately, this package is **not** mean to be referenced by anyone, rather only `Microsoft.NET.Sdk.Web` references it.

**Comment by czb182** [comment]
Why not just add a framework reference and remove old Nuget packages

**Comment by lAnubisl** [comment]
> While we do reference these older functions, this is a compile time reference only. At runtime, the host will be loading up to date versions of these DLLs, so there is no actual security vulnerability. We have a few reasons for this (but not limited to):
> 
> 1. As a hosted service, we want to provide security patches without requiring customers to update and redeploy their app.
> 2. AspNetCore team changed how they distribute their dlls. Previously they were individual nuget packages, but they now distribute a 'meta' package, `Microsoft.AspNetCore.App.Ref` which aggregates all these dlls together. Unfortunately, this package is **not** mean to be referenced by anyone, rather only `Microsoft.NET.Sdk.Web` references it.

Does this also work this way for Azure Functions Emulator?

**Comment by czb182** [comment]
I think I see part of issue is that these are netstandard2.0 libraries.  Is .NET Framework still supported for webjobs?  It seems like with .net core 3.1 falling out of support in month or two, everything can be targeted to net6.0 and framework reference can be leveraged.

**Comment by jviau** [comment]
> Why not just add a framework reference and remove old Nuget packages

We do not want to bring in the entire AspNetCore framework as that will adversely impact function load performance. We have addressed this in functions v4 as these references are no longer present.

> I think I see part of issue is that these are netstandard2.0 libraries. Is .NET Framework still supported for webjobs? It seems like with .net core 3.1 falling out of support in month or two, everything can be targeted to net6.0 and framework reference can be leveraged.

netstandard2.0 is the correct route here as these are class libraries (and not an application themselves), this means it can be used in almost any other chosen TFM: netfx, netcoreapp, net5/6/7. See https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

As for functions supported runtimes (including netfx support), please see https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cwindows%2Cin-process%2Cv4&pivots=programming-language-csharp#languages

**Comment by czb182** [comment]
Still seems weird to reference deprecated libraries for any scenario.  Are we sure doing a framework reference would impact load?  Maybe system knows to load only desired libraries and not the entire framework?  Or maybe since its part of framework already there is no impact?

**Comment by jviau** [comment]
Bringing in the full framework reference definitely could adversely impact cold start. We are also no longer bringing in the most minimal dependencies - which as a framework ourselves is important as we do not want to mislead customers on what we truly support. This is a known gap as AspNetCore does not lend itself to be nicely redistributed in a piece meal fashion. I don't expect us to address this in the near future, especially since these dependencies are all removed in Functions v4 (so in a way it is already addressed). I am not sure if this will work, but if you must address this in your projects, you can try directly referencing AspNetCore framework: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio. No promises that will work though - I have not tried it myself.

/cc @fabiocav, @brettsam as you two have dealt with similar security issues.

**Comment by nvmkpk** [comment]
> these dependencies are all removed in Functions v4

I still see transitive references to Asp.net Core 2.2 nuget packages via `Microsoft.Azure.WebJobs.Extensions.Http` version 3.2. This is preventing us from using azure functions.
