### ISSUE TITLE
Receive multiple messages from Service Bus in one webjob

### ISSUE THREAD

**Issue by iremmats** [Azure/azure-webjobs-sdk-extensions#8]
For reference, read this: http://geekswithblogs.net/asmith/archive/2012/04/10/149275.aspx

Implementing most integration patterns with webjobs and ServiceBus is pretty straight forward. For example, splitting is very easy with ICollector<BrokeredMessage> as output. 
But Aggregating is kind of impossible. What I would like is to have a ServiceBusTrigger support some kind of combination of SessionId/Correlation id and a counter.
Imaging sending 10 messages with same SessionId and property NumberOfMsgInSession = 10. My webjob with ServiceBusTriggerWithSessionId(queue) would not start until all 10 messages can be read from the queue/subscription.

**Comment by rustd** [comment]
Let's use this bug https://github.com/Azure/azure-webjobs-sdk/issues/570 to track this issue.
