### ISSUE TITLE
[FeatureRequest] Configuration for consistency level in CosmosDB binding 

### ISSUE THREAD

**Issue by inirudebwoy** [Azure/azure-webjobs-sdk-extensions#808]
Hello 👋 

 In some cases we need to be sure that data has been saved, while in other we don't really care about it. The docs does not say what is the consistency level for this type of binding though. I'd like to propose an option to set consistency level for CosmosDB binding.

**Comment by ealsur** [comment]
The binding uses the SDK, the SDK uses the account consistency.

So if your account is Strong, the binding will honor that. If the account is Eventual, the binding will honor that. It's not a binding level configuration, but an account level configuration.

**Comment by inirudebwoy** [comment]
Thanks for reply. Yes it is but in some cases I’d like to lower the consistency level. It is possible when using SDK. Best regardsMichał KlichOn 18 Nov 2022, at 7:37 PM, Matias Quaranta ***@***.***> wrote:﻿
The binding uses the SDK, the SDK uses the account consistency.

**Comment by ealsur** [comment]
Consistency cannot be decreased in all cases, adding a generic attributed called ConsistencyLevel would set the wrong expectations.

Because Consistency level can be relaxed only in a subset of operations, the alternative is that you can use the client directly through the binding if you want: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=in-process%2Cfunctionsv2&pivots=programming-language-csharp#http-trigger-get-multiple-docs-using-documentclient-c

**Comment by inirudebwoy** [comment]
Thank you. Unfortunately we are using python and that seems to not be possible with python.  Best regardsMichał KlichOn 21 Nov 2022, at 3:47 PM, Matias Quaranta ***@***.***> wrote:﻿
Consistency cannot be decreased in all cases, adding a generic attributed called ConsistencyLevel would set the wrong expectations.
Because Consistency level can be relaxed only in a subset of operations, the alternative is that you can use the client directly through the binding if you want: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=in-process%2Cfunctionsv2&pivots=programming-language-csharp#http-trigger-get-multiple-docs-using-documentclient-c

**Comment by ealsur** [comment]
I see. I am not aware of how Python works but if it does not have the access to the client, then it would not be possible to reduce the consistency through the bindings. Binding properties are generic for Input/Output, and reducing the consistency is only possible on a subset of these operations, adding the property there would make the user think it can be reduced in all.

**Comment by inirudebwoy** [comment]
Makes sense. It would be great if python had same features as .net has. Best regardsMichał KlichOn 25 Nov 2022, at 4:30 PM, Matias Quaranta ***@***.***> wrote:﻿
I see. I am not aware of how Python works but if it does not have the access to the client, then it would not be possible to reduce the consistency through the bindings. Binding properties are generic for Input/Output, and reducing the consistency is only possible on a subset of these operations, adding the property there would make the user think it can be reduced in all.
