### ISSUE TITLE
Specifying StartFromTime property doesn't work

### ISSUE THREAD

**Issue by deniz-newday** [Azure/azure-webjobs-sdk-extensions#809]
I think this is a problem with the `Microsoft.Azure.Cosmos` library and I have already raised this issue on their github. 
If I provide `StartFromTime` it doesn't pick up any messages from the container even there are items which are newer than the specified date. But on the `CosmosDBTriggerListener` if I convert the parsed DateTime to UniversalTime, the messages are being picked up by the change feed.

#### Repro steps
local.settings.json

``` json
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "InputChangeFeed__ContainerName": "event-stream",
    "InputChangeFeed__DatabaseName": "ToDoList",
    "InputChangeFeed__LeaseContainerName": "leases",
    "InputChangeFeed__LeaseContainerPrefix": "eventpublisher15",
    "InputChangeFeed__StartFromTime": "2022-11-08T14:28:33.000Z",
    "InputChangeFeedConnection__accountEndpoint": "https://someaccount.documents.azure.com:443/"
  }
}
```

Function Code
``` c#
[FunctionName(nameof(WorkingChangeFeedMessagePublisher))]
    public async Task Run(
        [CosmosDBTrigger("%InputChangeFeed:DatabaseName%", 
            "%InputChangeFeed:ContainerName%",
            
            Connection = "InputChangeFeedConnection",
            LeaseContainerName = "%InputChangeFeed:LeaseContainerName%",
            LeaseContainerPrefix = "%InputChangeFeed:LeaseContainerPrefix%",
            StartFromTime = "%InputChangeFeed:StartFromTime%",
            FeedPollDelay = 500)]
        IReadOnlyList<Document> documents, ILogger logger)
    {
        foreach (var document in documents)
        {
            logger.LogInformation("received item.");
        }
    }
```

#### Expected behavior

If there are items in the database which are added to the container after `2022-11-08T14:28:33.000Z`, they should be picked up by the change feed

#### Actual behavior

The lease is created in the database but no items are picked up from the database by the changefeed.

#### Known workarounds

at [CosmosDbTriggerListener](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs#L185), instead of setting
`this._hostBuilder.WithStartTime(startFromTime);`, if we provide `this._hostBuilder.WithStartTime(startFromTime.ToUniversalTime());`, the changefeed starts working.

#### Related information 

Provide any related information 

* Package version 4.0.0-rc
* Links to source

**Comment by ramya894** [comment]
@deniz-newday would it be possible for you share us the function app name so that we can for the logs from our end.

**Comment by deniz-newday** [comment]
I don't think I can share the name since it's for work but it can be reproducable easily with the code above ^

**Comment by deniz-newday** [comment]
I've also raise this issue with https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3559

**Comment by ramya894** [comment]
@deniz-newday please follow the solution provided in the above repo, i,e the dedicated repo

**Comment by deniz-newday** [comment]
@ramya894 sorry but could you please provide a link? I couldn't see the solution in the repo.

**Comment by ealsur** [comment]
This will get solved once the fix in the SDK is done, there is no specific change that is required in this extension.

**Comment by ramya894** [comment]
closing it as answered.
