### ISSUE TITLE
GA status for Cosmos DB trigger Identity connection

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-webjobs-sdk-extensions#810]
We are on our way to replacing the connection string with Managed Identity for Function trigger. And I see the package Webjobs.Extensions.CosmosDB already has the stable version [4.0.0](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.CosmosDB/4.0.0) which contains the support for Identity connection way.

But from Microsoft Docs, the status for the Cosmos DB trigger identity connection support is still in preview.
1. https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#configure-an-identity-based-connection
2. https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=in-process%2Cextensionv4&pivots=programming-language-csharp#tabpanel_2_extensionv4_in-process

 So, I wonder is this document not updated? Or this feature is not fully supportted yet and we still need to wait some time?

Thanks!

**Comment by ealsur** [comment]
Docs were updated to reflect the GA status
