### ISSUE TITLE
Receiving NU1603 warning when using Microsoft.Azure.Functions.Worker.Extensions.SendGrid 3.0.2

### ISSUE THREAD

**Issue by KenBrannigan** [Azure/azure-webjobs-sdk-extensions#815]
I have an azure function project using NET 7 in isolated mode. The output is a send grid message using Microsoft.Azure.Functions.Worker.Extensions.SendGrid 3.0.2. When I compile the project I get the following warning:

C:\Users\XXX\AppData\Local\Temp\lpedynlh.tn2\WorkerExtensions.csproj : warning NU1603: Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2 depends on Microsoft.Azure.WebJobs (>= 3.0.17) but Microsoft.Azure.WebJobs 3.0.17 was not found. An approximate best match of Microsoft.Azure.WebJobs 3.0.18 was resolved.

**Comment by fabiocav** [comment]
This would also need to flow to the worker extension once fixed.

**Comment by fabiocav** [comment]
@KenBrannigan new versions of the package are now deployed.

Closing as completed.
