### ISSUE TITLE
Two input bindings inside one Azure Http trigger function

### ISSUE THREAD

**Issue by shashimahawaththa** [Azure/azure-webjobs-sdk-extensions#828]
Hi,

Really appriciate your help here, I am new to azure development and I need to get result from 2 cosmoDB collections and combine the result to send the response. Here my issue is, I need to have 2 cosmoDB input bindings inside one http trigger aure function and I need to use one input binding response attribute to input to other input binding. below is my coding example,

![image](https://user-images.githubusercontent.com/39517229/220144098-b363040c-ada4-40ed-8544-945f8207c530.png)

 is it possible?

**Comment by bhagyshricompany** [comment]
@shashimahawaththa  yes you caan perform multiple input binding over azure function.
If you can provide the code zip file what you doing or repro all steps So i can give you more help on that.
I created sample and thats working.
<img width="785" alt="image" src="https://user-images.githubusercontent.com/116645353/226558327-a16ae5e2-c593-42af-9320-03f59beab14c.png">

**Comment by shashimahawaththa** [comment]
Hi bhagyshricompany,
Thanks for attending this. Yeah I know we can use multiple input binding over azure function. but here my concern is how to refer one input binding response value to another input binding input within same function app, as I mentioned in the screen shot

Thanks!

**Comment by bhagyshricompany** [comment]
you can refer the function chaining doc:
https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-sequence?tabs=csharp
