### ISSUE TITLE
Confusion about CosmosDB binding and retries

### ISSUE THREAD

**Issue by Ceglowa** [Azure/azure-webjobs-sdk-extensions#830]
I am currently trying to use the retry policy in the CosmosDB binding in the Function. However, I think that the docs are bit misleading as of now and I am unsure whether the retry policy will work or not.

#### Repro steps

Provide the steps required to reproduce the problem

1. I have a python Function that uses the CosmosDB binding. I wanted also to add retry policy as stated here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-python#retries The definition of the function.json looks like this:
```
{
  "scriptFile": "../src/handler.py",
  "entryPoint": "handle",
  "bindings": [
    {
      "type": "cosmosDBTrigger",
      "name": "documents",
      "direction": "in",
      "connectionStringSetting": "CosmosDB_Endpoint",
      "databaseName": "database",
      "collectionName": "collection",
      "CreateLeaseCollectionIfNotExists": true
    }],
    "retry": {
      "strategy": "exponentialBackoff",
      "maxRetryCount": 3,
      "minimumInterval": "00:01:00",
      "maximumInterval": "00:15:00"
    }
}
```

2. When the host is initializing is is showing the following log: 
![image](https://user-images.githubusercontent.com/27965443/221596158-a6f46874-b4bf-4319-996c-c5aa1da62fc8.png)

#### Expected behavior

Based on the information found on the https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-python#retries it seems that the retry policy is supported for the CosmosDB binding. I was expecting that this kind of log won't be shown.

#### Actual behavior

The log regarding the support of the retry policy is showing which is somewhat confusing in relation to the documents. 

#### Related information 

Provide any related information 

* Version of the azure functions python runner = 4.15.1.1
* Host.json
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
  
```

**Comment by ealsur** [comment]
The Retry Policies are supported on bundles that include the Cosmos DB Extension 4.0 and higher

**Comment by Ceglowa** [comment]
Is the CosmosDB Extension included in `Microsoft.Azure.Functions.ExtensionBundle`? If yes, then to what version shoud I increase it to - "version": "[4.*, 5.0.0)"?

**Comment by ealsur** [comment]
I don't know, this repo is not for the Bundles, this repo is for the `Microsoft.Azure.WebJobs.Extensions.CosmosDB` extension package.

https://github.com/Azure/azure-functions-extension-bundles sounds like the right repository for your question.

**Comment by Ceglowa** [comment]
Okay, but I still think that the documentation here https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-python#retries is very misleading. On one hand there is `Important` section on the top which is not mentioning CosmosDB binding (which implies that the support for retry policies for CosmosDB binding will be removed). And there is no notion of which version you need to use to support retry policies for CosmosDB binding.

**Comment by ealsur** [comment]
@Ceglowa The documentation page has a Feedback section at the bottom, please use that to report documentation related issues. I understand what you are describing, but there is nothing that can be changed on this repo to either update the documentation or to handle Bundle related questions.

**Comment by Ceglowa** [comment]
Okay, I posted a issue on the azure-docs github repository so that the documentation is clearer about this (https://github.com/MicrosoftDocs/azure-docs/issues/106040). Closing this ticket
