### ISSUE TITLE
TimerTrigger wait until previous trigger has finished

### ISSUE THREAD

**Issue by sharpcoder28** [Azure/azure-webjobs-sdk-extensions#84]
I'd like a way to have a TimerTrigger not trigger again if it's still running. I tried to look at the code to see if I could extend it, and maybe I still can if someone can point me in the right direction.

The issue is right now we have a Timer running every one minute. It checks a bunch of e-mails and FTP servers for files, does some processing and then adds those to a queue. The problem is if it takes longer than a minute, then it's going to fire again and we haven't deleted the e-mails yet so we get duplicates.

I know a better solution would be a web hook to Office 365 if someone can point me in the right direction there that would be great. As far as FTP I'm not sure, maybe a file system watcher, but that's going to be a windows service which we are trying to get away from.

Right now I'm refactoring to just read the e-mail and stick it in blob, then use blobtrigger, which "should" get us there. That's if that can still process all the e-mails and FTPs in time, and they don't have a timeout, etc, etc.

**Comment by mathewc** [comment]
TimerTrigger already works the way you suggest - it won't trigger again if there is an outstanding invocation still running. You can see in the code [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs#L227) that the internal Timer used has `AutoReset=false`, and when we invoke your function we only start the timer again AFTER your function completes (code [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs#L180)).

This repo also has a FileTrigger for files, and we've had asks to make this work for FTP, but that hasn't been done. For WebHooks, we're not pointing people to our new [Azure Functions](https://azure.microsoft.com/en-us/services/functions/) service which we just released a preview of.

If you see that TimerTrigger is not working the way I indicate, feel free to reopen this.

**Comment by sharpcoder28** [comment]
I figured out it was because I was using non-static and async methods. Once I removed the async it started working as intended. I'm guessing it would be hard to know if the same method was running off on another thread somewhere.  Up to you if you want to support async or not. I'm also not sure how much using async would buy us anyways. Thank you for the timely response.

**Comment by mathewc** [comment]
We do support async, and in the code I linked above you can see we `await` the invocation of your function. If this isn't working its a bug. Do you have a slim repro of this that you can share with me? If there is a bug we'll fix it :)

**Comment by sharpcoder28** [comment]
Sure thing. In the following code you should see it log a few times and then get an exception after 20 seconds because the writer is closed. Not sure if that is another bug too!

```
public async void AsyncTest([TimerTrigger("00:00:05", RunOnStartup = true)]
            TimerInfo info, TextWriter log)
{
            
            log.WriteLine("Entered method");

            await Task.Delay(20000);

            log.WriteLine("After delay");
}
```

**Comment by mathewc** [comment]
That isn't an asyn function. You need to return a Task. Change void to Task.




On Wed, Apr 27, 2016 at 11:57 AM -0700, "sharpcoder28" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure thing. In the following code you should see it log a few times and then get an exception after 20 seconds because the writer is closed. Not sure if that is another bug too!

public async void AsyncTest([TimerTrigger("00:00:05", RunOnStartup = true)]
            TimerInfo info, TextWriter log)
{

            log.WriteLine("Entered method");

            await Task.Delay(20000);

            log.WriteLine("After delay");
}


-

**Comment by sharpcoder28** [comment]
Ahh. It works perfectly now. Thanks for your help. I guess I need to do more research on async and Tasks ;)

**Comment by vargonian** [comment]
Thank you so much, this was exactly my issue as well. (i.e. async void changed to async Task).  I still trip up with the async/await pattern.
