### ISSUE TITLE
Function's timer trigger is not fired at certain time.

### ISSUE THREAD

**Issue by AndreyDegtyarev** [Azure/azure-webjobs-sdk-extensions#840]
Good morning,

I faced with an issue when timerTrigger  is not fired at particular time, but it can be fired later on the same day at unexpected time.

Function app runs in  Premium Service Plan (pricing plan P1v2)
Function runs every day at 12:00 AM (CRON expression looks like "0 0 0 * * *").
However, as we can see timer cannot be triggered at particular time occasionally (it happens 2-3 times in a moth).

I looked through all recommendations about solving issue nevertheless issue takes place.
AlwaysOn Enabled
Is runOnStartup enabled? | False

There is neither trace entry that says Function was triggered..  nor any log entry regrading error.
However, I could mention some additional information which may help figure out the problem:
timestamp [UTC]
2023-03-17T13:30:35.2557391Z
message
Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2023-03-17T00:00:00.0000000+00:00
itemType
trace

Troubleshooting got the following information:
Function Name	Total Occurrences	Latest Timestamp	Latest FunctionInvocationId

load-data-scheduled	1	3/20/2023 12:00:02 AM	2410c0a1-601b-43ce-aa2d-29f4d7156b4c
Common Cause	
Usually it means the function was in Hang or deadlock status then as its Timeout value could be set as Unlimited in Dedicated App Service Plan.

**Comment by bhagyshricompany** [comment]
Hi @AndreyDegtyarev  thanks for inform Will check as the input you provided and update you on this asap.
pls provide the region name ,Instance Id,function name Properly.

**Comment by AndreyDegtyarev** [comment]
Hi @bhagyshricompany,
Location
West Europe
SubscriptionId: a464f508-ff11-423c-bab6-8eadb42ebcf2
AppId: c8d3cccd-4b36-4747-9f1c-d2fcf2f8b747

**Comment by bhagyshricompany** [comment]
@AndreyDegtyarev pls provide the function app name.StartTimestamp and End Timestamp.

**Comment by AndreyDegtyarev** [comment]
Start timestamp [UTC]
2023-03-17T13:26:42.259784Z
End timestamp [UTC]
2023-03-17T13:44:25.7200761Z

**Comment by bhagyshricompany** [comment]
function name ?

**Comment by AndreyDegtyarev** [comment]
Function app: proton-prod-quarkdataloaderfunc 
Function name: load-data-scheduled

**Comment by bhagyshricompany** [comment]
@AndreyDegtyarev Thanks for input.

**Comment by bhagyshricompany** [comment]
is it coming again pls check and update

**Comment by AndreyDegtyarev** [comment]
I see that function has been executing properly for 2 weeks. 
However I noticed an unexpected behavior.
The function triggers once a day, inside the logic it creates file and stores it in blob.
Occasionally, couple blobs can be created which means function had  been triggered twice. Moreover, it executes secondly at the same time. But I only see one execution in Function Monitor. 
 For example:
31032023-00-00-983a620e.data.zip
31032023-00-23-983a620e.data.zip

00-00 and 00-23 are time of execution

There is only single entry of execution in Monitor log
2023-03-31 00:23:25.859 Success
3bf5c587c1e9b6b2cb00faca854f7756

**Comment by bhagyshricompany** [comment]
@fabiocav  pls comment

**Comment by AndreyDegtyarev** [comment]
Hey guys,
Are there any updates?
We came across the same issue again. Function hadn't been triggered for 3 days. 
load-data-scheduled function launches every day at 00:00. however it failed to run in last 3 days.
According to function monitor last success ran:
2023-05-19 00:28:20.539   (-- in fact, it should have launched at 00:00)
 Success
0
794184
c00749ebd86a1deca27283c21dbf7f46

I couldn't find any related failure entry in  AppInsights however I found the issue in traces transaction search
<html>
<body>
<div class="event-property-panel-section" role="region" aria-label="Trace Properties" style="box-sizing: inherit; margin-bottom: 15px; color: rgb(255, 255, 255); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(17, 17, 17); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;"><span role="presentation" style="box-sizing: inherit;">Trace Properties</span><div class="float-right" role="button" aria-controls="aria-81" tabindex="0" focusable="true" style="box-sizing: inherit; margin-left: auto;"><span class="text-button" style="box-sizing: inherit; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; color: rgb(72, 148, 254); cursor: pointer; font-size: 14px;">Show less</span></div></div>

Event time | 5/21/2023, 2:12:25.6771191 PM (Local time) |  
-- | -- | --
Device type | PC |  
Message | The listener for function 'Functions.load-data-scheduled' was unable to start. |  
Severity level | Error |  
Telemetry type | trace |  
Client IP address | 0.0.0.0 |  
Role name | proton-prod-quarkdataloaderfunc |  
Role instance | 30bfc2956d5dd9eb65769c8a096471c221c8d23f3a89d03d50cb58c36b0eefcd |  
SDK version | azurefunctions: 4.19.0.20414 |  
Sample rate | 1 |  

</div>
</body>
</html>

**Comment by bhagyshricompany** [comment]
investigating on this update you  on this

**Comment by fabiocav** [comment]
@AndreyDegtyarev due to the nature of the issue, the investigation here would be more efficient if done through support. Would you have the ability to create a support request for this issue so we can take a closer look? Thanks!
