### ISSUE TITLE
CosmosDBTrigger attribute "CreateLeaseContainerIfNotExists" will create a container which TTL is not enabled and lead to dead lock and startup failed during initialization

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-webjobs-sdk-extensions#858]
The CosmosDBTrigger's attribute "CreateLeaseContainerIfNotExists = true" will create a container which TTL is not enabled. But during the function startup, there will be a BootstrapperCore.InitializeAsync() and will acquire a lock if lease is not initialized. this lock has 30s ttl. But this won't take effect if the container's TTL option is not enabled.

#### Repro steps

1. Create a lease container use "CreateLeaseContainerIfNotExists = true"
2. During the startup, in BootstrapperCore.InitializeAsync(), after `bool isLockAcquired = await this.leaseStore.AcquireInitializationLockAsync(this.lockTime).ConfigureAwait(false);`, some unexpected event happen and the lock failed to be released.
3. All the next startup will fail to get this lock and run into dead while loop, which cause the startup timeout.

#### Expected behavior

The lock is deleted by container through ttl even unexpected event happened.

#### Actual behavior

The lock record is kept in the container and block all further requests and block the startup.

#### Known workarounds

Manually delete this lock record.

#### Related information 

Provide any related information 

* Package version: 4.0.0
* Links to source: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c46614b9311365f203d489394cf475e212ca202f/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Bootstrapping/BootstrapperCore.cs#L51

**Comment by blankor1** [comment]
And also, I guess this line for acquiring the lock should be moved into the try block to ensure that any exception happen the lock will be released?
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c46614b9311365f203d489394cf475e212ca202f/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Bootstrapping/BootstrapperCore.cs#L61
<img width="807" alt="image" src="https://github.com/Azure/azure-webjobs-sdk-extensions/assets/36236746/ae62bf8e-7010-4589-abac-b6420eea827a">

**Comment by bhagyshricompany** [comment]
Thanks for  reporting pls share the functin,app name instance id, region timestamp etc

**Comment by blankor1** [comment]
Hi @bhagyshricompany, we have resolved this issue by manually deleted the lock property in the lease container. But to further avoid this case we still have a question: Is disabling TTL for lease container a by design behavior for some reason? Or we should enable TTL for lease container?

For now, seems every CosmosDBTrigger that create lease container through [CreateLeaseContainerIfNotExists = true] will create a TTL not enabled container, and hence the TTL which serves as safeguard will not take effect at all.

It's micorsoft internal service, for the detailed function info we can communicate on Teams (yuxia3).

**Comment by ealsur** [comment]
@blankor1 TTL has not been enabled on Lease Container creation in any extension versions and there is no requirement that it is. The logic you are pointing to regarding the lock is on the SDK client, which is not code in this repository. 

Can you please clarify what was the effect this lock document not being removed caused?

**Comment by blankor1** [comment]
Thank you for your response. I understand that the code is not in this repo, but it will actually be called and executed during the CosmosDBTrigger startup. And without the TTL enabled, the TTL safeguard will not work at all. That is the functionality conflict part. Is there any concern why not enable TTL from the extension method?

And for the effect, in our case, we hit something unexpected during the startup, and the lock is created but not released. If the TTL is enabled, the lock should be deleted after expire. But since TTL is not enabled, the lock stay in the lease collection and the lease document is not created. And then, all following startup processes won't succeed since it will go into this dead while loop forever (line 53) and cause the startup timeout.
<img width="738" alt="image" src="https://github.com/Azure/azure-webjobs-sdk-extensions/assets/36236746/405ea93f-8d9a-4420-82a5-9e110a8629ab">

**Comment by ealsur** [comment]
@blankor1 TTL has not been enabled on any version of the extension, nor it is in the Change Feed Processor documentation as a requirement.

The `ReleaseInitializationLockAsync` call in the `finally` statement deletes the lock if it was acquired.

> we hit something unexpected during the startup

Can you expand on what was that? `AcquireInitializationLockAsync` just creates the document, if the document creation fails the exception bubbles and goes outside of `InitializeAsync`. If it does not throw, then `true` is returned, the `try/finally` block enters and anything that happens there would eventually reach the `finally` which would delete the lock.

We need to understand what the problem was in order to evaluate if the TTL is the best solution. I do wonder why this has not been an issue in the ~6 years this extension had this behavior.

**Comment by blankor1** [comment]
I guess it is an app crash or something similar to it which cause the app to terminate without entering the finally block. Unfortunately, when we know that it is the lock that block the function startup, it has been more than one month since the issue happened, and the applen's data is not available anymore. So we don't know what exactly happened.

What we see is that the corresponding lease lock exist in the lease container and the program runs into the dead while loop which blocks the following startup process.

**Comment by ealsur** [comment]
@blankor1 Are you using the https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.CosmosDB or https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.CosmosDB/

**Comment by MikeNicholls** [comment]
@ealsur I've seen this happen in the past with Microsoft.Azure.WebJobs.Extensions.CosmosDB, we create our lease container manually so I resolved it by enabling TTL (setting it to -1) in our ARM template.

Looking back at the report I received at the time, "Azure Functions runtime is unreachable" was showing in the Azure portal.

![screenshot](https://github.com/Azure/azure-webjobs-sdk-extensions/assets/5996859/d588a16d-cfaa-4ca2-9bc3-e7ceec66610f)

![cosmos](https://github.com/Azure/azure-webjobs-sdk-extensions/assets/5996859/b57acbd0-4611-433b-80fb-02218000f439)

**Comment by ealsur** [comment]
@MikeNicholls Thanks for the extra details, I wonder what could that mean. But I guess adding the TTL is not something that should hurt as none of the leases use the TTL property.
