### ISSUE TITLE
CosmosDBTrigger creates empty collection of changed items

### ISSUE THREAD

**Issue by aleksandrshvets** [Azure/azure-webjobs-sdk-extensions#872]
#### Repro steps

1. Create CosmosDB trigger using dotnet and azure-webjobs-sdk-extensions:

```
[FunctionName(FunctionName)]
	public async Task Run([CosmosDBTrigger(
			databaseName: "%DatabaseName%",
			containerName: "%DeploymentItemContainer%",
			Connection = "ConnectionString",
			LeaseContainerName = "%LeaseContainerName%",
			LeaseContainerPrefix = "%LeasePrefix%",
			CreateLeaseContainerIfNotExists = true)]
		IReadOnlyList<Item> input)
	{
		try
		{
                       foreach (var item in input)
			{
				await DoStuff(item);
			}
		}
		catch (Exception exception)
		{
			_logger.LogError("An error occurred while processing the Cosmos change feed: {0}", exception);
			throw;
		}
	}
```
2. Add record to the container used by function

#### Expected behavior

Change in container is handled by function.

#### Actual behavior

Function is triggered but `input` collection is empty.

#### Known workarounds

No workarounds found.

#### Related information 
Everything works fine on local emulator.
```
azurefunctions: 4.25.2.2
<PackageReference Include="FluentValidation" Version="11.7.1" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="4.4.0" />
<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.35.4" />
<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
<PackageReference Include="System.Net.Http" Version="4.3.4" />
```

**Comment by ealsur** [comment]
Are you testing this on the Emulator or a real Cosmos DB account? We have tests in this repository that are part of the CI that verify the behavior.

There is a known scenario for the Cosmos DB Service to return an empty result and that is if you use `StartFromTime`.

Are you certain the input variable is empty (Count == 0) and not filled with `null` items (which would point to an issue with the `Item` class definition).

**Comment by ealsur** [comment]
To be more precise, this Extension uses the Cosmos DB SDK, the Cosmos DB SDK will not call `ProcessChanges` 

https://github.com/Azure/azure-webjobs-sdk-extensions/blob/a390e4eee0f7bb5d2add08e12db7368b98163ea7/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs#L222

If the Count is 0:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/101b9b1ad59d65f4687cf383afdb9b22b873b0dc/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Observers/ChangeFeedObserverFactoryCore.cs#L90-L111

```
 IReadOnlyCollection<T> changes = this.AsIReadOnlyCollection(stream, context);
            if (changes.Count == 0)
            {
                return Task.CompletedTask;
            }
```

**Comment by aleksandrshvets** [comment]
@ealsur
I use real Cosmos DB account. Exception looks like:
```
Sequence contains no elements
System.InvalidOperationException at Function+<DoStuff>d__5.MoveNext
```

**Comment by ealsur** [comment]
@aleksandrshvets 

Can you provide the full stack trace? At least based on the source code, I don't see a way for the Trigger to be invoked with an empty list

**Comment by ealsur** [comment]
```
Sequence contains no elements
System.InvalidOperationException at Function+<DoStuff>d__5.MoveNext
```

Means the exception is inside DoStuff, not in the main Function code.

DoStuff takes an `item` not the list. So the exception cannot be related to `input`?

**Comment by ealsur** [comment]
Also, what is the signature of `DoStuff`?

**Comment by aleksandrshvets** [comment]
@ealsur thanks for help, trigger works fine. I was confused by error message that was related to exception in  async DoStuff mehod
