### ISSUE TITLE
WebJobs Host in a Windows Service: how to encrypt/obscure AzureWebJobsStorage?

### ISSUE THREAD

**Issue by OzBob** [Azure/azure-webjobs-sdk-extensions#876]
In a Windows Service that hosts the WebJobs SDK (```Assembly Microsoft.Azure.WebJobs.Host, Version=3.0.37.0```) depends on the ```AzureWebJobsStorage``` value being in clear text in the appsettings.json file

How to encrypt the appsettings.json file? or set an environment variable to allow the WebJobs Host access to it.

I have tried and failed setting the value using the following methods:

1. Changing the IConfiguration provider to use a custom ```ConfigurationBuilder().Add(new EncryptedConfigurationSource ...``` that encrypts and reads an ```app.config``` file, and sets IConfiguration in DI for all my code, but NOT the [SDK WebJobsConfigurationExtension](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/a6c80c74de3354bcb573b080d0076296e52b0b5a/src/WebJobs.Extensions.CosmosDB/WebJobsConfigurationExtensions.cs#L12)
2. setting a func value with : ```func settings add AzureWebJobsStorage "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1...```
3. setting an environment variable: ```[Environment]::SetEnvironmentVariable("AZURE_STORAGE_CONNECTION_STRING","DefaultEndpointsProtocol=http;AccountName=devstoreaccount1...```

The only thing that prevents the below error is to delete the appsettings.json file.

Can I inject a custom ```StorageClientProvider``` or override the default ```WebJobsConfigurationExtension```?

#### Expected behavior
```WebJobsConfigurationExtension``` should use the IConfiguration provider set in the ConfigurationBuilder StartUp, not auto open the appsettings.json file and **not** find 'AzureWebJobsStorage' in there.

#### Actual behavior
Exception 
```
   Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'AAA.BBB'
       ---> System.InvalidOperationException: Storage account connection string 'AzureWebJobsStorage' does not exist. Make sure that it is a defined App Setting.
         at Microsoft.Azure.WebJobs.Extensions.Clients.Shared.StorageClientProvider`2.GetWebJobsConnectionStringSection(String name)
```

#### Known workarounds
None. Only clear text values in appsettings.json file. I requre an encrypted value.
I can encrypt my own config file projectname.dll.config, by using net7 ConfigurationManager, and delete appsettings.json, but there should be a recommended solution to encrypting a config file. 

#### Related information 
Packages referenced in my test project:
```
		<PackageReference Include="Microsoft.Azure.WebJobs.Host.Storage" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.1" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.2.1" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Queues" Version="5.1.3" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
```

**Comment by OzBob** [comment]
More info: deleting the appsettings.json results in the SDK using my IConfiguration specified in the ConfigurationBuilder.

**Comment by bhagyshricompany** [comment]
Thanks for reporting will  check and update.Thanks

**Comment by bhagyshricompany** [comment]
Hi @OzBob  3

Just as a short hint, I could recommend storing the values in environment variables. This is a bit more secure than storing them plainly in text files as accessing environment variables requires higher priviledges than reading a file. For many companies this was enough solution if azure key vault or aws secret manager could not be used. Environment variables you can use both if you host your app as docker container or running on VM. 
please ref this doc. https://learn.microsoft.com/en-us/azure/storage/common/storage-service-encryption
https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows.
Try this option if not raised request on portal.Thanks
