### ISSUE TITLE
TimerTrigger issue with Daylight Saving Time change

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-webjobs-sdk-extensions#880]
Daylight saving time change caused the timer trigger not to trigger for 1hour for below repro app.

#### Repro app details -

Function App : prod-mcz-balance-app
Timer trigger: SendImbalanceToFiftyoneAsync
OS: Windows
App setting 'WEBSITE_TIME_ZONE' is set to: 'Romance Standard Time'

When Daylight saving time was set 1 hour back on 29th of October the TimerTrigger did not trigger for 1 hour between 12.00 AM - 01.00 AM UTC. 

#### Related information 

https://github.com/Azure/azure-webjobs-sdk-extensions/pull/492#issuecomment-479862622

**Comment by dffisker** [comment]
Any updates on this?
