### ISSUE TITLE
Azure Function Cosmos Trigger - with strong typed param I cannot filter multiple document types coming from changefeed

### ISSUE THREAD

**Issue by swegele** [Azure/azure-webjobs-sdk-extensions#885]
I have an Azure Function triggered by Cosmos changefeed :-)  Yay very cool!

Two document types are stored in container named "ProjectData":
- `Project` 
- `ProjectInterview`
 
Partition key is "ProjectId".  Property `TypeName` distinguishes which is which.

The latest Azure Function Cosmos extension makes the `Run` method parameter strongly typed `IReadOnlyList<T>`.  
I only care about processing `Project` changes.

PROBLEM:  Changes to both document types are triggering my one function.  
The serializer tries to turn the `ProjectInterview` json into a `Project` which ends up populating very few properties.

My wonky workaround: 

```cs
        public async Task Run(
            ...
            IReadOnlyList<Project> projects)
        {
            //*** IMPORTANT - must filter out projectinterviews stored in the same container
            projects = projects.Where(p => p.TypeName == nameof(Project)).ToList();

            ...

```

Workaround is a hack and it is expensive in two ways:
- My function gets triggered when I don't want it to be
- If I want to eventually add another function handling changes for ProjectInterview, I would end up having 4x functions triggered.

In this instance it almost seems like the older way of accepting `Document` is better because then you can determine which it is first.

If there is no better workaround, then maybe the documentation should say something about how to design your container to not have multiple types if you want to use change feed azure functions.  I didn't find anything mentioned about it anywhere.

**Comment by ealsur** [comment]
Thanks for the report. I'll try to answer the different points:

> My function gets triggered when I don't want it to be

This was still a functional behavior of the previous Extension version and the reason is that it's not tied to the Extension. Change Feed as a source of data/feature does not have filtering capabilities on the service. There is no way on any Extension version to filter to only receive events of a particular type of documents.

> In this instance it almost seems like the older way of accepting Document is better because then you can determine which it is first.

And you can do that with this Extension version too. The difference is that with the older version, you had no alternative. 
`Document` is just a `Dictionary<string, object>` implementation. You can use `JObject`:

```
 public async Task Run(
            ...
            IReadOnlyList<JObject> events)
        {
            foreach (var event in events)
                  if (event["TypeName"] == nameof(Project))
                  .....
            ...
```

You could also use a base class with the `TypeName` property if you want to have it more typified.

I'll update the migration docs at https://learn.microsoft.com/en-us/azure/azure-functions/migrate-cosmos-db-version-3-version-4?tabs=isolated-process&pivots=programming-language-csharp#modify-your-function-code to cover this scenario.

**Comment by swegele** [comment]
I tried the following:

```cs
        [Function(nameof(UpdateUserProjectsFunction))]
        public async Task Run(
            [CosmosDBTrigger(
                databaseName: Constants.CONST_CosmosDBName,
                containerName: Constants.CONST_ContainerName_Projects,
                Connection = "cosmos_uri",
                LeaseContainerName = "leases",
                LeaseContainerPrefix = "UpdateUserProjectsFunction-",
                CreateLeaseContainerIfNotExists = true)]
            IReadOnlyList<JObject> events)
        {
           ...
```

...it gives me this error when the function is triggered from changing a document:

```
Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'UpdateUserProjectsFunction': Cannot convert input parameter 'events' to type 'System.Collections.Generic.IReadOnlyList`1[[Newtonsoft.Json.Linq.JObject, Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Newtonsoft.Json.Linq.JToken. Path: $[0].id | LineNumber: 0 | BytePositionInLine: 45.
```

Any tips appreciated.

**Comment by ealsur** [comment]
Are you in Isolated Worker mode? Then try `JsonNode`.

**Comment by swegele** [comment]
Thank you sir!  That worked.  Running in Isolated extensions v4 and .net 8.

Is there a better or different place (latest version) to post questions?


I thought I saw a video or an article where you mentioned you can get the `CosmosClient` by injecting it in the `Run` method.  I tried that but it didn't work.  So I ended up creating one _(see below)_.  But it would be nice if I could simply inject the one that already exists.

**Program.cs**
```cs
        var uri = configuration.GetSection("cosmos_uri_only").Value;
        var tokenCred = new DefaultAzureCredential();
        var cosmosClient = new CosmosClient(uri, tokenCred);
        services.AddSingleton(cosmosClient);

```

**Function Code**
```cs
    public class UpdateUserProjectsFunction
    {
        private readonly ILogger _logger;
        private readonly CosmosClient _cosmosClient;

        public UpdateUserProjectsFunction(ILoggerFactory loggerFactory,
            CosmosClient cosmosClient)
        {
            _logger = loggerFactory.CreateLogger<UpdateUserProjectsFunction>();
            _cosmosClient = cosmosClient;
        }

        [Function(nameof(UpdateUserProjectsFunction))]
        public async Task Run(
            [CosmosDBTrigger(
                databaseName: Constants.CONST_CosmosDBName,
                containerName: Constants.CONST_ContainerName_Projects,
                Connection = "cosmos_uri",
                LeaseContainerName = "leases",
                LeaseContainerPrefix = "UpdateUserProjectsFunction-",
                CreateLeaseContainerIfNotExists = true)]
            IReadOnlyList<JsonNode> events)
        {

```

**Comment by ealsur** [comment]
Mmm this might work:

```
[Function(nameof(UpdateUserProjectsFunction))]
        public async Task Run(
            [CosmosDBTrigger(
                databaseName: Constants.CONST_CosmosDBName,
                containerName: Constants.CONST_ContainerName_Projects,
                Connection = "cosmos_uri",
                LeaseContainerName = "leases",
                LeaseContainerPrefix = "UpdateUserProjectsFunction-",
                CreateLeaseContainerIfNotExists = true)]
            IReadOnlyList<JsonNode> events,
           [CosmosDB(
                databaseName: Constants.CONST_CosmosDBName,
                containerName: Constants.CONST_ContainerName_Projects,
                Connection = "cosmos_uri")] CosmosClient client)
        {
```

Example where I'm using it:

https://github.com/ealsur/netday-cosmos/blob/a1e8a5b11030bbf9c2b19883915afe9975052367/cosmos.monitor/CosmosMonitor.cs#L28-L32

**Comment by swegele** [comment]
That `CosmosDBAttribute` doesn't like the .NET 8 Isolated mode.
It gives this error and won't compile.

[AZFW0001: Invalid binding attributes](https://dotnet-worker-rules.azurewebsites.net/rules?ruleid=AZFW0001)

So then I tried the newer stuff and tried this:

```cs
    public class UpdateUserProjectsFunction
    {
        [Function(nameof(UpdateUserProjectsFunction))]
        public async Task Run(
            [CosmosDBTrigger(
                databaseName: Constants.CONST_CosmosDBName,
                containerName: Constants.CONST_ContainerName_Projects,
                Connection = "cosmos_uri",
                LeaseContainerName = "leases",
                LeaseContainerPrefix = "UpdateUserProjectsFunction-",
                CreateLeaseContainerIfNotExists = true)]IReadOnlyList<JsonNode> nodes,
            [CosmosDBInput(
                databaseName: Constants.CONST_CosmosDBName,
                Connection = "cosmos_uri")]CosmosClient cosmosClient,
            ILogger _logger)
        {

```


It compiles but gives a runtime error when the function is called on a change:

`
Function 'UpdateUserProjectsFunction', Invocation id 'ad20b513-5959-4a3d-8a37-dc542c3b04df': An exception was thrown by the invocation.
Result: Function 'UpdateUserProjectsFunction', Invocation id 'ad20b513-5959-4a3d-8a37-dc542c3b04df': An exception was thrown by the invocation.
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'UpdateUserProjectsFunction': Cannot convert input parameter 'cosmosClient' to type 'Microsoft.Azure.Cosmos.CosmosClient' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.InvalidOperationException: Cosmos DB connection configuration 'cosmos_uri' does not exist. Make sure that it is a defined App Setting.
`

I feel like I'm close.  The 'cosmos_uri' is most certainly defined and present because the trigger uses it.

**Comment by swegele** [comment]
I played around with trying to get the Cosmos Input Binding working for a few more hours.  Honestly it seems a little lean on documentation for my comfort.  Changes are happening fast and I'm a little lost here.

I'm going to go back to simply configuring and injecting an explicit CosmosClient created by me explicitly in Program.cs.  That worked great, and it felt similar to how I would code it that in a normal app.

Thanks for the help and keep up the great changes.

**Comment by ealsur** [comment]
Yes, I think Isolated Worker mode has certain limitations that I at least am not personally knowledgeable of, sorry for sharing a non-working example. When I tested it I guess it was in In-Process Functions.
