### ISSUE TITLE
Continuous TimerTrigger vs. triggered settings.job file with schedule

### ISSUE THREAD

**Issue by jon-mey** [Azure/azure-webjobs-sdk-extensions#904]
I've discovered there are 2 ways of creating jobs on a schedule:

1. Create a triggered WebJob with a settings.job file with a schedule, e.g.
`{
    "schedule": "0 */15 * * * *"
}`
2. Create a continuous WebJob and use the TimerTriggerAttribute

When is each approach appropriate? Is 1) more suitable for jobs that runs more seldom, e.g. once a month? And, in the case of 1), who is responsible for starting the job host? Is it scheduled directly by the OS?

**Comment by bhagyshricompany** [comment]
You're correct that there are two main approaches to creating scheduled jobs in Azure WebJobs:

Triggered WebJobs using a settings.job file with a schedule.
Continuous WebJobs using the TimerTrigger attribute.
For less frequent, scheduled tasks (like monthly jobs), using a triggered WebJob with a cron-style schedule is generally the better approach.
For frequent or continuous tasks, such as tasks that need to run at short intervals (e.g., every minute), a continuous WebJob with a TimerTrigger is more appropriate.
