### ISSUE TITLE
FileTrigger autoDelete not working properly

### ISSUE THREAD

**Issue by leontyr** [Azure/azure-webjobs-sdk-extensions#91]
Hi, 

I'm not sure if it's the right place for this. I might have found a bug.

I'm using FileTrigger to upload images to Azure storage blob. The upload works fine. However, the autoDelete only deletes about 20 images and then stops. I'm testing it on the local machine by pasting 150 images into the import folder. The console stops at "Executed: 'Functions.ImportJpg'" with no error.

Also, is there a way to stop the FileTrigger picking up the status file or not create status file at all? The only way I can see is to filter it by a extension. However, that means I have to create separate and almost identical method for each image extension?

Thanks, 

```
class Program
    {
        static void Main()
        {
            JobHostConfiguration config = new JobHostConfiguration();
            config.Tracing.ConsoleLevel = TraceLevel.Verbose;
            FilesConfiguration filesConfig = new FilesConfiguration();
            filesConfig.RootPath = @"D:\temp";

            config.UseFiles(filesConfig);

            JobHost host = new JobHost(config);
            host.RunAndBlock();
        }
    }

public class Functions
    {
public static void ImportJpg(
            [FileTrigger(@"import/{name}", "*.jpg", autoDelete: true)] Stream file,
            [Blob(@"media/{name}")] CloudBlockBlob output,
            string name,
            TextWriter log)
        {
            output.UploadFromStream(file);
            file.Close();
            log.WriteLine(string.Format("Processed input file '{0}'!", name));
        }

        public static void ImportFileErrorHandler([ErrorTrigger] TraceEvent error, string message, TextWriter log)
        {
            // Here you could send an error notification

            log.WriteLine(string.Format("{0} : {1}", message, error.ToString()));
        }
    }
```

**Comment by mathewc** [comment]
Does this repro consistenly? I.e. if I try the steps above will I have a repro?

Based on the way the cleanup process works, I do think I see a reason why this might be happening. The cleanup pass for autoDelete runs on a background timer, and runs ~5 seconds after a file add/edit is detected. It will then look for any files whose companion status file indicates that it has been processed successfully and delete such file groups. **The timer does not auto-reset** - we reset the timer the next time we see some more file events. This was done so we don't have a background file process running when there are no new files being added.

So what I think is happening is you're bulk adding the 150 files at one go, we process all the file events at that time, queueing up the work. However, we only get through about 20 imports before the cleanup runs - the remaining 130 files are still waiting to be processed, and their status files do not indicate completion at that time. So the cleanup process is done and won't check again until another file event occurs.

You can verify my theory by adding one more file - it should result in everything getting cleaned up. Can you try?

**Comment by leontyr** [comment]
Thanks for the prompt reply! 

Yes, it repro consistently and your theory is right. After I've added another file, all of them get deleted.

I think your tweak would work great especially for the files with the same names to be triggered on afterwords and it's much cleaner.

So I guess there's no way to not trigger on status files? If I use *.* as the filter, it keeps creating new status files on status files. And I can't find a way to stop it except creating separated methods for each file extension.

**Comment by mathewc** [comment]
I agree that we should probably automatically exclude the status files from triggering in cases where the filter is *.*. The status files are our control files used to determine when the source files have completed processing, so there aren't any scenarios where you'd want to trigger on them. So I think I'll just exclude them.

The above would address your scenario I believe. As far as the ability to specify multiple file extensions to trigger on, we're using the .NET FileSystemWatcher behind the scenes and the filter that you specify we pass directly to the watcher. It doesn't support multiple extensions (e.g. no "*.jpg|*.png"). I'll think more on whether we could add that support ourselves. Another advanced option to effect such filtering would be for you to derive from `FileProcessor` and override `ShouldProcessFile` to do additional filtering (be sure to call base). You can register your custom processor via `FilesConfiguration.ProcessorFactory`. Note that this would also allow you to work around the fact that we're triggering on *.status files, until we get the fix out for that.

**Comment by mathewc** [comment]
This has been fixed. A prerelease version with the fix can be found on our myget feed (version **2.0.0-alpha-10290**). Thanks for reporting :)

To clarify, I've changed the following:

* we no longer trigger on status files
* changed cleanup logic to be triggered whenever files complete processing (not on the initial file trigger event)
