### ISSUE TITLE
[Timer Extension] Do not cancel CTS when in drain mode

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-webjobs-sdk-extensions#918]
We should not be signaling cancellation during drain mode. Drain mode is intended to allow on-going invocations to finish executing.

Update the timer extension so that the CTS is not being cancelled when drain mode is enabled

**Comment by nzthiago** [comment]
@liliankasem - I suspect this is also happening with the storage queue trigger.

I have a very simple function with a delay of 20 seconds, this is the only function in the app:
![Image](https://github.com/user-attachments/assets/0dd78e6f-e712-47a0-a9d6-196a832362e3)

It has a 20 second delay in it. It seems like drain mode is triggering the cancellation token (see in the logs that the token returns true), and this causes the message to appear in the queue again after a few minutes and this repeats again:

![Image](https://github.com/user-attachments/assets/effb03c7-45be-4de0-8252-e6c472651946)

**Comment by liliankasem** [comment]
@nzthiago this issue is just for tracking the timer issue/PR. For anything else please use the parent issue:

- https://github.com/Azure/azure-webjobs-sdk/issues/2795

**Comment by nzthiago** [comment]
@liliankasem sure, I have posted it there too. I hoped to capture the relevance here so that this could get addressed at the same time for all triggers impacted and not just Timer.

**Comment by liliankasem** [comment]
I understand, but this issue was created to just track the PR that is open right now, this will close when the PR is merged. I don't want any information to get lost which is why it's important to not track related issues here 🙂

> this could get addressed at the same time

I consider this a different work item so I would open a new issue so that it can be added to the team's backlog.


_Edit:_ @nzthiago speaking to Fabio, as the host team does _not_ maintain the WebJobs extensions, the recommendation is to open an issue with the team that owns those extensions. For Queues, the repo is here: https://github.com/Azure/azure-sdk-for-net.

I will be doing the same for all of the other extensions mentioned in that parent as well.

**Comment by nzthiago** [comment]
Ahh, I see, I was hoping a fix would **not** be needed for each trigger (which is what @soninaren tried with the referenced issue #2795 a while back. Seems he stopped it from happening at some level but each individual trigger kept on sending the cancellation token?). I'll work on raising this same request then for other triggers.

**Comment by liliankasem** [comment]
> Ahh, I see, I was hoping a fix would **not** be needed for each trigger (which is what [@soninaren](https://github.com/soninaren) tried with the referenced issue #2795 a while back. Seems he stopped it from happening at some level but each individual trigger kept on sending the cancellation token?). I'll work on raising this same request then for other triggers.

Ah yup, it is definitely something that each trigger needs to address on its own as they are using the CT and cancelling it when StopAsync is called. Cosmos, Storage, ServiceBus, EventHub (and now Timer) have been already fixed. I raised issues for RabbitMQ, SignalR, and Kafka.
