### ISSUE TITLE
OneDrive Connector issues

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-webjobs-sdk-extensions#95]
1. when a new file is added to OneDrive and /datasets/default/triggers/onnewfile?folderId={folderid} is called. The return header does not include the full file path in x-ms-file-path and only includes the file name.
2. new file trigger does not work when new files are added to the top root folder of OneDrive.

**Comment by vip32** [comment]
@safihamid i am curious, where do i find this onedrive connector? is that part of this extensions repo?

**Comment by safihamid** [comment]
Yes it's not part of this repo. this issue is fixed now. closing it. thanks

**Comment by vip32** [comment]
in what repo can i find it? thx

**Comment by safihamid** [comment]
It's not on github. it's on internal msft onebranch.
